### ISSUE TITLE
Support quantity and unit_amount instead of just amount

### ISSUE THREAD

**Issue by nvictorme** [stripe/stripe-firebase-extensions#1]
# Feature request

- Extension name: `firestore-stripe-invoices`

## Is your feature request related to a problem? Please describe.

I'd like to be able to pass 'quantity' and 'unit_amount' instead of 'amount'. Not every item quantity = 1.

## Describe the solution you'd like

OrderItems should use quantity and unit_amount instead of just amount
## Describe alternatives you've considered

implementing my own solution.

## Additional context
![image](https://user-images.githubusercontent.com/18505860/87860244-dc87d700-c909-11ea-8279-ff449a377b4d.png)

**Comment by thorsten-stripe** [comment]
Thanks, @nvictorme, that's a good idea, I'll work on adding support for line item quantities.

One quick question: would you mind posting the invoice doc that resulted in the screenshotted error?

**Comment by thorsten-stripe** [comment]
This is slotted for the next release on Thursday PT.

Thanks again @nvictorme for submitting! :)
