### ISSUE TITLE
Support Firebase Emulator

### ISSUE THREAD

**Issue by tudor07** [stripe/stripe-firebase-extensions#100]
- Extension name: `firestore-stripe-subscriptions`

FIrebase has great [emulator](https://firebase.google.com/docs/emulator-suite) tools.
How to integrate this Stripe extension with the emulator?

**Comment by thorsten-stripe** [comment]
They do, e.g. https://github.com/stripe/stripe-firebase-extensions/blob/next/package.json#L13

But the extension emulators are still in closed alpha, you will have to wait for these to be released by the firebase team.
