### ISSUE TITLE
Can't update to latest version 0.1.8

### ISSUE THREAD

**Issue by shidcordero** [stripe/stripe-firebase-extensions#104]
# Bug report

Error shown when trying to update the extension

## Describe the bug

![image](https://user-images.githubusercontent.com/26376208/99744766-4829bd00-2b13-11eb-8b18-294ef5fc5d93.png)

## To Reproduce

Update extension

## Expected behavior

Should successfully update

## Screenshots

see at describe the bug

## System information

- OS: Windows 10 64bit
- Browser (if applies) Edge

**Comment by thorsten-stripe** [comment]
Can you please retry updating, Firebase sometimes has some hiccups there but generally retrying the update resolves that. 

cc @jhuleatt

**Comment by shidcordero** [comment]
Tried to re-update and a new error shows

![image](https://user-images.githubusercontent.com/26376208/99753932-4a474800-2b22-11eb-803a-72f23666fcfe.png)

**Comment by thorsten-stripe** [comment]
I'm not able to reproduce this, therefore I don't think it's related to the extension itself. Please reach out to Firebase for further support.
![image](https://user-images.githubusercontent.com/23213994/99754102-a7db9480-2b22-11eb-97cf-a31b7c11bb4a.png)

**Comment by shidcordero** [comment]
yeah, you're right. only a firebase issue
