### ISSUE TITLE
FR: Create checkout session with trial from the Prices API

### ISSUE THREAD

**Issue by fbarthelery** [stripe/stripe-firebase-extensions#105]
# Feature request

firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.

`trial_from_plan` has been deprecated and doesn't work anymore with Checkout. There is no way to create a checkout session with a trial.

## Describe the solution you'd like

Allow to set `subscription_data.trial_end` or `subscription_data.trial_period_days` in the checkout_session document. Maybe set the whole `subscription_data` object

**Comment by fbarthelery** [comment]
My bad. It looks like I missed a few things during my tests. `trial_from_plan` works fine with the legacy settings.

**Comment by spenco100** [comment]
While this is a closed and documented issue, are there plans to remove the legacy support from trials?

**Comment by dijour** [comment]
Is there a way to add a trial to the subscription checkout session? Bumping this, as I'm not sure I see a way to do this in `createCheckoutSession`.

**Comment by jsteele-stripe** [comment]
Closing in favour of #274.
