### ISSUE TITLE
Add support for Pricing model: Volume pricing

### ISSUE THREAD

**Issue by dave-k** [stripe/stripe-firebase-extensions#106]
# Feature request
- Extension name: `firestore-stripe-subscriptions`

Need support for Pricing model: Volume pricing
Units: 2
Per Unit: 500

<img width="595" alt="volume-pricing" src="https://user-images.githubusercontent.com/5447484/100167511-19de1180-2e74-11eb-8556-f8bc6fb46853.png">

## Describe the solution you'd like

Support Pricing model: Volume pricing

**Comment by DCSnip3r** [comment]
I would also like to see this feature. Standard pricing alone is a bit too restrictive

**Comment by DCSnip3r** [comment]
Could I get info on why this is not possible to do with createCheckoutSession? Do Stripe checkout sessions not support this feature natively, or is this something the function could do with some modifications? I'm wondering if I can help with a solution, or what I should anticipate when creating my own checkout sessions that support volume pricing

**Comment by t-kaufmann** [comment]
Are there any plans on implementing volume pricing in the near future? This would be pretty important for me as volume pricing is essential in our application, otherwise I'd have to search for other solutions.

**Comment by thorsten-stripe** [comment]
Yes, Checkout now supports the other pricing models and we're working on adding support for these. Please follow along here https://github.com/stripe/stripe-firebase-extensions/issues/84
