### ISSUE TITLE
How to force user to pay for changing the plan?

### ISSUE THREAD

**Issue by shidcordero** [stripe/stripe-firebase-extensions#108]
# Bug report

How to force user to pay for changing the plan?

## Describe the bug

 I was researching about how the user will be able to pay immediately once they want to change a plan. Currently, the previous plan will be active and cant be change. I found on this link(https://stripe.com/docs/billing/subscriptions/upgrade-downgrade) that I need to set `proration_behavior` to `always_invoice`. How can I do it using this extension?

**Comment by thorsten-stripe** [comment]
Up- and downgrading happens within the customer portal. You can configure the behavior in the settings: https://dashboard.stripe.com/test/settings/billing/portal
![image](https://user-images.githubusercontent.com/23213994/103669185-ff3ea280-4fb2-11eb-9e5c-3ffc4266364c.png)
