### ISSUE TITLE
Webhook sending updates for all subscriptions in Stripe, not only for products in the customer portal triggers 400 errors

### ISSUE THREAD

**Issue by Miki-AG** [stripe/stripe-firebase-extensions#109]
# Bug report

- Extension name: firestore-stripe-subscriptions

## Describe the bug

We manage multiple products in Stripe. Some of them are visible in the customer portal but some others are not. The Stripe Webhook sends updates regardless, causing errors (Firebase Function logs, ext-firestore-stripe-subscriptions-handleWebhookEvents):

❗️[Error]: Webhook handler for  Stripe event [xxxxx] of type [customer.subscription.updated] failed: User not found! 

Stripe needs anything between a HTTP 200 to 299 for the webhook to be considered successfully delivered. As a result Stripe will send an email warning and eventually will stop sending notifications to the webhook.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create some products A and B in Stripe
2. Add only product B to the customer portal
3. The extension will receive updates for subscriptions to plan A, responding with error 400 to Stripe

## Expected behavior
If, as a result of a webhook call a user is not found in firebase, then log "user is not found" in the Firebase function log, but send a HTTP 200 to 299 back to Stripe to acknowledge the message.

## Screenshots

n/a

## System information

n/a

## Additional context

Warning email sent by Stripe:

Hi there,

We’re contacting you because we’ve had some trouble sending requests to a webhook endpoint associated with your xxx account in test mode. Webhooks are used to notify your server about events that happen in your Stripe account, such as a payout completing or an invoice being created. The failing webhook endpoint is https://xxx/ext-firestore-stripe-subscriptions-handleWebhookEvents.

You or someone on your team has added that endpoint in your Stripe webhook settings, which you can view and edit here: https://dashboard.stripe.com/account/webhooks.

Please note that in most cases a failing webhook does not impact your payments or payouts. However, if you use subscriptions we rely on your webhook endpoint to notify you of new invoices. These invoices may be delayed for up to three days if your webhook is unable to successfully receive them. If you use Checkout, you may be handling the `checkout.session.completed` event as part of your purchase fulfillment process as described here: https://stripe.com/docs/payments/checkout/fulfillment#webhooks. If you do, failure to handle these events may interfere with purchase fulfillment.

We’ve attempted to notify the endpoint 8 times since November 30, 2020 at 03:27PM. If this endpoint is important to your application, please try and fix the issue. If you do not need the webhook endpoint you can delete it from your Stripe webhook settings. We will stop sending notifications to your webhook by December 9, 2020 around 03:27PM.

Here is the summary of errors we have received when sending you webhooks:
* 8 requests had other errors while sending the webhook.

You need to return anything between a HTTP 200 to 299 for the webhook to be considered successfully delivered.
For more details on the errors, you can find your events page here: https://dashboard.stripe.com/test/events.

You can also always review the history of webhooks and failed request logs right from your dashboard: https://dashboard.stripe.com/test/events.

For more in depth information about how to use webhooks, we recommend taking a look at our documentation: https://stripe.com/docs/webhooks.

Yours,

The Stripe team

**Comment by thorsten-stripe** [comment]
I've got a PR open to change to always 200 and logging instead:
![image](https://user-images.githubusercontent.com/23213994/103741564-4ae56080-5034-11eb-8194-6a4dcf817438.png)

This will roll out with v0.1.9
