### ISSUE TITLE
Trial period is not set on customer creation

### ISSUE THREAD

**Issue by aliaksandr-yanchuk** [stripe/stripe-firebase-extensions#11]
# Bug report

- Extension name: firestore-stripe-subscriptions

## Describe the bug

When customer entity is created in Stripe, the subscription (for selected product / price) doesn't have trial period set. It also results in "active" status of subscription object put in firestore and not "trialing". If you add trial days in created subscription from Stripe dashboard, status is getting changed correctly to "trialing".

## To Reproduce

1. In Stripe dashboard create a Product, which has price with Trial days more than 0.
2. In your firebase-stripe integrated application initialize checkout.
3. Check your firestore for created customer entity in "customers" collection and see that subscription has "active" status without trial information set.

## Expected behavior

"trialing" status correctly set like in description above.

**Comment by thorsten-stripe** [comment]
Thanks for reporting this @aliaksandr-yanchuk. I cam across this as well earlier today and have a PR ready to fix it: https://github.com/stripe/stripe-firebase-extensions/pull/10.

This fix will be released on Thursday morning PT time.
