### ISSUE TITLE
Make interfaces available as an npm package

### ISSUE THREAD

**Issue by jaytavares** [stripe/stripe-firebase-extensions#112]
# Feature request

- Extension name: [Both]

## Is your feature request related to a problem? Please describe.

Nope!

## Describe the solution you'd like

It'd be super helpful if the Stripe interfaces (e.g. Subscription, Tax Rates, etc.) were available through an npm package. They're all already included within the source of this repo; however, since extensions are installed server-side within Firebase, they're not available within our code.

## Describe alternatives you've considered

Copy and paste the type files from this repo into my codebase.

## Additional context

--

Thanks!

**Comment by thorsten-stripe** [comment]
Most of the interfaces are internal to the server-side functions. Can you describe your use-case for needing these in your code base? Do you have additionally functions that interact with the data?

**Comment by jmcdl** [comment]
Not OP, but we use the Price, Product and Subscription interfaces in a React hook that retrieves subscription options and customer subscription status.

**Comment by amotarao** [comment]
YES! I want packages for many case.
It's useful with TypeScript.

For example from https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#get-the-customers-subscription

```ts
// TheComponent.tsx
import { Subscription } from 'stripe-firebase-extensions' // <- here

db.collection('customers')
  .doc(currentUser.uid)
  .collection('subscriptions')
  .where('status', 'in', ['trialing', 'active'])
  .onSnapshot(async (snapshot) => {
    // In this implementation we only expect one active or trialing subscription to exist.
    const doc = snapshot.docs[0];
    console.log(doc.id, ' => ', doc.data() as Subscription); // <- here
  });
```

**Comment by hiranya911** [comment]
This is likely a dependency management issue. The library is expecting a certain version of `@firebase/firestore` while a different one is installed with the app. Can somebody who can repro this issue please share their dependency tree with us (i.e. `npm ls` output)? Or even better, share a small, minimal repro that we can try locally.

**Comment by hiranya911** [comment]
We now have https://www.npmjs.com/package/@stripe/firestore-stripe-payments available in alpha. Please try it out and let us know if it meets your requirements.

**Comment by jaytavares** [comment]
@hiranya911 That package looks great. Thanks!
