### ISSUE TITLE
'Failed to retrieve function source code' errors while installing/updating

### ISSUE THREAD

**Issue by jaytavares** [stripe/stripe-firebase-extensions#113]
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug

While attempting to upgrade the extension to 0.1.8, the upgrade process fails and leaves the extension in an unusable state. UPDATE: I've now seen the same error message while trying to install the extension (both 0.1.8 and 0.1.7 across multiple Firebase projects.)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Extensions
2. Click on 'Update Extension'
3. Proceed with process...

or:

1. Go to extensions
2. Click install on Stripe Subscriptions extension
3. Follow installation procedure to end

## Expected behavior

An extension installation/upgrade without error, leaving a functioning extension.

## Screenshots

<img width="756" alt="Screen Shot 2020-12-10 at 2 17 41 PM" src="https://user-images.githubusercontent.com/711127/101818882-80a92f00-3af2-11eb-9321-1fac8cae2e07.png">

* See below for full error text *

## System information

- Error text: 
>; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-subscriptions/resources/createCustomer: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Failed to retrieve function source code"}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-subscriptions/resources/onCustomerDataDeleted: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Failed to retrieve function source code"}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-subscriptions/resources/onUserDeleted: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Failed to retrieve function source code"}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-subscriptions/resources/createPortalLink: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Failed to retrieve function source code"}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-subscriptions/resources/createCheckoutSession: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Failed to retrieve function source code"}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-subscriptions/resources/handleWebhookEvents: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Failed to retrieve function source code"}

## Additional context

Initially seen while updating to v0.1.8 from v0.1.7; however, since seen while attempting first-time installation in another Firebase project.

**Comment by jaytavares** [comment]
Looks like this issue might be affecting all new installations of the extension... 🤔 Using the Firebase CLI tool, I tried installing another instance of the extension using v0.1.7 in an attempt to roll back; I'm seeing the same issue:

<img width="930" alt="Screen Shot 2020-12-10 at 2 27 02 PM" src="https://user-images.githubusercontent.com/711127/101819866-cdd9d080-3af3-11eb-9d72-8778e5f88018.png">

<img width="761" alt="Screen Shot 2020-12-10 at 2 22 59 PM" src="https://user-images.githubusercontent.com/711127/101819629-85baae00-3af3-11eb-91b8-89dbd00e63b3.png">

**Comment by jaytavares** [comment]
I saw #104, it's not the same errors that I'm seeing, but might be similar. I've reached out to Firebase support for assistance.

**Comment by jaytavares** [comment]
hmm, I actually can't install the extension at all. Not even in a separate Firebase project. @thorsten-stripe, are you seeing this behavior? I've reached out to Firebase support, but it might be a couple business days before I hear back.

**Comment by dave-k** [comment]
I have the same issue. The extension was working this morning.

<img width="1197" alt="ext-error" src="https://user-images.githubusercontent.com/5447484/101841272-7854f200-3afa-11eb-86cd-715b8d5ab564.png">

Cloud functions "Unknown function status"

![ext2-error](https://user-images.githubusercontent.com/5447484/101841409-b6521600-3afa-11eb-9e29-80c7efd9335f.png)

**Comment by SuneelFreimuth** [comment]
I can corroborate. I just installed the Firebase Stripe Extension and the Cloud Functions the extension creates are pointing at invalid source objects, seemingly causing the "Failed to retrieve function source code" error.
![image](https://user-images.githubusercontent.com/35514810/101844713-ed77f580-3b01-11eb-97fb-20e64eb6ecb1.png)
Error is "Archive not found in the storage location".
If I deploy using `gcloud functions deploy ext-firestore-stripe-subscriptions-createCheckoutSession`, I get
```
Deploying function (may take a while - up to 2 minutes)...failed.
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: could not resolve storage source: googleapi: Error 404: No such object: gcf-sources-1083565983701-us-central1/ext-firestore-stripe-subscriptions-createCheckoutSession-7645d6a9-1a8e-46da-8335-40907373cbb6/version-4/function-source.zip, notFound
```

**Comment by SuneelFreimuth** [comment]
> Looks like this issue might be affecting all new installations of the extension...  Using the Firebase CLI tool, I tried installing another instance of the extension using v0.1.7 in an attempt to roll back; I'm seeing the same issue:
> 
> <img alt="Screen Shot 2020-12-10 at 2 27 02 PM" width="930" src="https://user-images.githubusercontent.com/711127/101819866-cdd9d080-3af3-11eb-9d72-8778e5f88018.png">
> 
> <img alt="Screen Shot 2020-12-10 at 2 22 59 PM" width="761" src="https://user-images.githubusercontent.com/711127/101819629-85baae00-3af3-11eb-91b8-89dbd00e63b3.png">

I saw this error a few times while doing the configuration. When it showed up, I retried saving the configuration and it wouldn't show up.

**Comment by Calvin087** [comment]
I thought I was going crazy not being able to find this issue anywhere on the internet. Thought it was just me. Consistent errors upon installing the extension using the CLI

![Screenshot 2020-12-10 at 17 17 18](https://user-images.githubusercontent.com/58273749/101905598-fcb97a80-3bb7-11eb-97df-d985313aaf8c.png)

**Comment by hand-dot** [comment]
I'm in the exact same situation.
It worked fine until a few days ago, but yesterday it started acting weird.

However, the same error occurred when I installed Sync with Mailchimp, so maybe this is not a stripe problem but a firebase problem.

Can I install other extensions?
I was not able to.

**Comment by rosariopfernandes** [comment]
Hey everyone, this bug seems to be happening for all Firebase Extensions.
The recommendation is to install or upgrade extensions through the CLI, as per [tinaliang's comment here](https://github.com/firebase/extensions/issues/529#issuecomment-742754020):
> Sorry you've been having the issues. Install should be working via the CLI now. We're working on fixing installs through the Console and will post another update when it's been rolled out. In the meantime, please use the CLI for all installs/udpates.

**Comment by jaytavares** [comment]
I think Firebase might have fixed the issue. I was able to install the Stripe subscriptions extension in a new project with success. I also updated the extension in one project. For that one, after updating, I also had to delete the cloud functions it had originally created and "reconfigure" the extension to cause it to recreate the functions.

**Comment by SuneelFreimuth** [comment]
> I think Firebase might have fixed the issue. I was able to install the Stripe subscriptions extension in a new project with success. I also updated the extension in one project. For that one, after updating, I also had to delete the cloud functions it had originally created and "reconfigure" the extension to cause it to recreate the functions.

The extension now works for me as well; the functions fetch their source code correctly.

**Comment by cjavilla-stripe** [comment]
Thanks for the updates folks. It looks like this was resolved by Firebase, so I'm going to close for now. Please feel free to re-open if the issue reoccurs.

**Comment by zaheddec** [comment]
seeing the same issue in v0.1.10
https://github.com/stripe/stripe-firebase-extensions/issues/145

**Comment by Machdata** [comment]
Having the same issue with 
https://firebase.google.com/products/extensions/firebase-firestore-bigquery-export?authuser=0
There is no more export extension only stream collections 
I installed extension it was mirroring for. a few days then it stopped
I tried reinstalling the error persiists
The extension is not creating the tables anymore

**Comment by adprojects202** [comment]
Seeing same issue
