### ISSUE TITLE
Add support for dynamic tax rates when GA

### ISSUE THREAD

**Issue by cjavilla-stripe** [stripe/stripe-firebase-extensions#115]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

`dynamic_tax_rates` are in beta so we can't pass that to every Checkout Session creation. Once this is GA we should fast follow to add support.

## Describe the solution you'd like

Add the dynamic_tax_rates field in the Checkout Session creation flow.

**Comment by dthib** [comment]
Hi, 
First of all, thanks for this nice extension!
I am also interested in the dynamic tax feature. 
Is there any roadmap somewhere? Maybe an idea for the v1 release? And is there a documentation with the known limitations apart from this issues? I have seen somewhere that all billing plans were not supported but it seems that it's not the case anymore right?
Thanks again, 
Best

**Comment by thorsten-stripe** [comment]
Dynamic tax rates is already supported via `line_items`:

```js
const docRef = await db
    .collection('customers')
    .doc(currentUser)
    .collection('checkout_sessions')
    .add({
      allow_promotion_codes: true,
      line_items: [
        {
          price: 'price_1HCUD4HYgolSBA35icTHEXd5',
          quantity: 1,
          dynamic_tax_rates: ['txr_1IJJtvHYgolSBA35ITTBOaew'],
        },
      ],
      success_url: window.location.origin,
      cancel_url: window.location.origin,
      metadata: {
        tax_rate: '10% sales tax exclusive',
      },
    });
```

Adding docs here: https://github.com/stripe/stripe-firebase-extensions/pull/135
