### ISSUE TITLE
Race Condition in Firestore DB Updates

### ISSUE THREAD

**Issue by MGItkin** [stripe/stripe-firebase-extensions#119]
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug
I've encountered a race condition that caused a transient state of a Stripe subscription to overwrite the current state. This caused the user subscription document in Firestore to be out of sync with the Stripe subscription API.

Looking into the logs (see "Additional context") it appears that a long function invocation of `ext-firestore-stripe-subscriptions-handleWebhookEvents` of 5249 ms is the culprit. From looking at the [manageSubscriptionStatusChange handler],(https://github.com/stripe/stripe-firebase-extensions/blob/master/firestore-stripe-subscriptions/functions/src/index.ts#L287) it appears to do a few things after retrieving the latest subscription and before updating Firestore. I believe we could resolve this by saving the webhook event creation time (`"created": 1608712474,`) to Firestore and use it to discard old events in a DB transaction.

## To Reproduce

Note: This is not easily reproducible in production as it is a race condition

1. Start Stripe checkout normally using this extension
2. Complete Stripe checkout
3. Check the appropriate user subscriptions collection in the Firestore DB

## Expected behavior

I expected that Stripe subscription documents in the Firestore DB stay in sync with Stripe's API

## Screenshots

N/A

## System information

N/A

## Additional context

**Function Logs (ext-firestore-stripe-subscriptions-handleWebhookEvents)**
```
8:16:33.785 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
Function execution started
8:16:33.823 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
⚙️ Handling Stripe event [evt_1HygCTErBnhaIPeS6d2vQz8W] of type [customer.subscription.created].
8:16:36.104 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
Function execution started
8:16:36.248 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
⚙️ Handling Stripe event [evt_1HygCVErBnhaIPeSPdtuVZjv] of type [customer.subscription.updated].
8:16:37.654 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
🔥📄 Added doc [sub_IZpsDXp5atMNtN] to collection [subscriptions] in Firestore.
8:16:37.911 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
Function execution started
8:16:37.949 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
⚙️ Handling Stripe event [evt_1HygCWErBnhaIPeS937cMqLh] of type [checkout.session.completed].
8:16:38.067 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
🚦 Added custom claim [stripeRole: PREMIUM] for user [UyJaYUR6x2WK7g6em0MF5qFxygQ2].
8:16:38.342 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
🔥📄 Added doc [sub_IZpsDXp5atMNtN] to collection [subscriptions] in Firestore.
8:16:38.367 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
✅Successfully handled Stripe event [evt_1HygCVErBnhaIPeSPdtuVZjv] of type [customer.subscription.updated].
8:16:38.369 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
Function execution took 2266 ms, finished with status code: 200
8:16:38.692 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
🚦 Added custom claim [stripeRole: null] for user [UyJaYUR6x2WK7g6em0MF5qFxygQ2].
8:16:39.031 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
✅Successfully handled Stripe event [evt_1HygCTErBnhaIPeS6d2vQz8W] of type [customer.subscription.created].
8:16:39.034 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
Function execution took 5249 ms, finished with status code: 200 
8:16:39.352 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
✅Successfully handled Stripe event [evt_1HygCWErBnhaIPeS937cMqLh] of type [checkout.session.completed].
8:16:39.355 AM
ext-firestore-stripe-subscriptions-handleWebhookEvents
Function execution took 1445 ms, finished with status code: 200
```

**Stripe Logs**
```
​ | Succeeded | customer.subscription.updated | evt_1I1SpRErBnhaIPeSqK8oquWt | Dec 23, 2020, 12:36 AM | ​ | ​ | More options
​ | Succeeded | customer.subscription.updated | evt_1I1SoBErBnhaIPeSqj1m7s1X | Dec 23, 2020, 12:35 AM | ​ | ​ | More options
​ | Succeeded | customer.subscription.updated | evt_1I1SnnErBnhaIPeSPZ77FwJL | Dec 23, 2020, 12:34 AM | ​ | ​ | More options
​ | Succeeded | customer.subscription.updated | evt_1I1SgcErBnhaIPeSd8USlBbx | Dec 23, 2020, 12:27 AM | ​ | ​ | More options
​ | Succeeded | customer.subscription.updated | evt_1I1SWiErBnhaIPeSJ6LPOcOC | Dec 23, 2020, 12:17 AM | ​ | ​ | More options
```

**Comment by thorsten-stripe** [comment]
Unfortunately Stripe events are not guaranteed to be created in sequence, so we can't rely on the `created` timestamp and need to retrieve the object to get the correct status. I've got a PR open that refactors the webhook handler to bring the subscription retrieval as close as possible to the Cloud Firestore write. This should hopefully eliminate this problem.

**Comment by MGItkin** [comment]
Is that really true? There is no timestamp associated with these events that can be used to determine the ordering? If that is true, then how is this Stripe dashboard of webhook events populated? Is this also not guaranteed to have the correct ordering?
![image](https://user-images.githubusercontent.com/11808956/104205163-f0a52080-53e2-11eb-949a-d897f4550a08.png)

I agree that your PR would reduce the likelihood of this race condition but, without guaranteed ordering of Stripe events, the consumer of these events could never be 100% sure that they are reading and recording the latest status.

**Comment by thorsten-stripe** [comment]
@MGItkin that's correct, the webhook logs in the Stripe Dashboard are also not guaranteed to be sequential. 

> without guaranteed ordering of Stripe events the consumer of these events could never be 100% sure that they are reading and recording the latest status

That's why you need to retrieve the object to get its current status.

**Comment by MGItkin** [comment]
@thorsten-stripe Ok, then. Is there anywhere where I can file a feature request with Stripe? I strongly believe there should be some way to provide guaranteed order to the event updates. Even in your latest PR, additional network latency on the request to update Firestore could cause the Function with the latest Subscription object to lose the race condition. I admit that this situation is rarer after your fix but, the race condition still exists.

In any case, thank you for providing this fix.
