### ISSUE TITLE
Add Firestore document on "invoice.payment_succeeded" Stripe event

### ISSUE THREAD

**Issue by scott-mccartney** [stripe/stripe-firebase-extensions#124]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

The `invoice.payment_succeeded` events are not handled by the Stripe Firebase extension, meaning that developers using the extension cannot use this event to trigger a Firebase function to run custom logic.

## Describe the solution you'd like

On `invoice.payment_succeeded` event, write to a `invoices` collection with the invoice details so that developers can use that document write as a Firebase function trigger.

## Describe alternatives you've considered

Alternatives are available by manually connecting to webhooks and handling specific events, but this use case may be common enough to justify configuration via the Firebase extension.

## Additional context

N/A

**Comment by thorsten-stripe** [comment]
Hey @scott-mccartney would you mind outlining your use case? What custom logic are you looking to run and therefore what information would you want available in Cloud Firestore?

We don't have any immediate plans to add this, but will leave it open for others to voice their interest. In the meantime, you can write a custom function and point the additional events to that. Here an example of a Firebase Cloud Functions webhook handler: https://github.com/stripe-samples/firebase-mobile-payments/blob/main/functions/index.js#L119-L174

**Comment by scott-mccartney** [comment]
Hi @thorsten-stripe, I have a user signed up for a monthly subscription and my desire here is to get a notification (i.e. a new Firestore document) whenever that user is charged their recurring payment every month. 

If a document was written to, let's say, an `invoices` collection, developers can listen to that document creation to trigger a Firebase function for further custom logic. In addition, that payment/invoice information could be beneficial for both users & developers to have stored in Firestore.

My specific use case would be to generate a new `Order` whenever a user is successfully charged each month. I've accomplished this by borrowing some code from this extension, making a new Firebase function, and then generating a new webhook in Stripe to call that endpoint for `invoice.payment_succeeded` events. `payment_intent.succeeded` may also work.
