### ISSUE TITLE
customer record not sync with stripe customers

### ISSUE THREAD

**Issue by pfloresl** [stripe/stripe-firebase-extensions#126]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

When the user logins, I create a document in the customer collection in firestore, document is the uid of the user and i add an email field, but i do not see a record added to stripe.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

i execute the following code in my react app,

`this.dbStore
                .collection('customers')
                .doc(authUser.uid)
                .set({ email: authUser.email })
                .then((res) => {
                  alert('created');
                })`
## Expected behavior

I confirm that the document is created.
But i do not see it on stripe.

Btw, the products that i add on stripe do get sync to my firestore collection.

also i had to change security rules for now because it would not let me create the document otherwise.

## System information
browser chrome,

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by pfloresl** [comment]
Read the source of and understood. Deleted my authenticated user and began working.

**Comment by thorsten-stripe** [comment]
Glad you got it working. If you have more questions regarding your integration you can jump on our technical chat on IRC: https://webchat.freenode.net/#stripe
