### ISSUE TITLE
Unable to verify trial period in firebase database

### ISSUE THREAD

**Issue by shaolinufo** [stripe/stripe-firebase-extensions#128]
# Bug report

firestore-stripe-subscriptions

## Describe the bug

I enabled trial for stripe product and the credit card went through, however there is no 'subscription' collection created in my firebase database. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable legacy trial period in Stripe under product pricing
2. Start Checkout session and enter in card details
3. Card goes through and trial is captured in stripe, but not in firebase database

## Expected behavior

'Subscription' collection should be created in firebase database so I can use logic to verify that the user has started free trial

## Screenshots
Only checkout session collection, and no 'subscription' collection
![nosub](https://user-images.githubusercontent.com/57123844/105624830-86747e80-5dd9-11eb-84d2-498b61a925e0.JPG)

Should be:
![image](https://user-images.githubusercontent.com/57123844/105624871-d6534580-5dd9-11eb-900b-8b32daac1340.png)

## System information

- OS: Windows
- Browser Chrome

**Comment by thorsten-stripe** [comment]
I'm not able to reproduce this:
![image](https://user-images.githubusercontent.com/23213994/105803419-66f77480-5fd8-11eb-8858-03a516993860.png)


It sounds like you're missing some webhook events: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#configure-stripe-webhooks or some permissions on your restricted key: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/PREINSTALL.md#additional-setup

Please check your Cloud Functions for any error logs.
