### ISSUE TITLE
Sync metadata object from the Stripe subscription object to Cloud Firestore

### ISSUE THREAD

**Issue by rikelk** [stripe/stripe-firebase-extensions#13]
# Feature request

- firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

Stripe API Subscription object has a metadata object to store custom key-value pairs informations. Metadata data object is currently not synced to firestore subscription object.

## Describe the solution you'd like

Add the abilty to attach a metadata object from the beginning of the subscrption process (checkout session) to finally save it to newly created firestore subscrption object. 

## Additional context

In my situation, a customer may create multiple items. For each item, customer needs a subscrption in order to activate the service. Metadata allows me to link item and subscritpion for a given customer.

**Comment by thorsten-stripe** [comment]
Thanks for outlining your use case @rikelk! To confirm, you want to provide the metadata on the client side as follows:

```js
const docRef = await db
    .collection('customers')
    .doc(currentUser)
    .collection('checkout_sessions')
    .add({
      price: formData.get('price'),
      success_url: window.location.origin,
      cancel_url: window.location.origin,
      metadata: {
        item: 'item1',
      },
    });
```

And then for it to be synced to the subscriptions doc in Cloud Firestore, correct?
![image](https://user-images.githubusercontent.com/23213994/88822658-b6f6a980-d1f6-11ea-9637-d6bdc44c0939.png)

**Comment by rikelk** [comment]
Thank you very much ! this is exactly that! :)

**Comment by thorsten-stripe** [comment]
Great, this will go out with the next release cycle on Thursday morning PT time :)
