### ISSUE TITLE
Support one time product

### ISSUE THREAD

**Issue by dthib** [stripe/stripe-firebase-extensions#133]
# Feature request

## Is your feature request related to a problem? Please describe.

For our company, we would like to support both one time product and subscription. For the same service, there will be two offers:
- One with one-time offer for one year without subscription (pay all once)
- One with monthly subscription.

## Describe the solution you'd like

I have seen in the code (and as the extension name suggests :)), that the checkout are done in subscription mode. It would be nice to be able to configure checkout in payment mode and benefit from all other features (customers sync with stripe, webhook to save checkout status, etc.)

## Describe alternatives you've considered

I have tested to use a checkout configuration with:
- a one time product
- a free monthly fee
But it seems a bit artificial...

Thanks for considering,
Best,
Thibaut

**Comment by thorsten-stripe** [comment]
> One with one-time offer for one year without subscription (pay all once)

To me this sounds like a yearly subscription. Any reason why you can't model it as such?

**Comment by dthib** [comment]
Agreed, kind of. But in term of commitment it's not the same thing. And
sometimes it can be really business killer (particularly for our market
population).

Another way I was thinking of: use the subscription cancel_at property but
it seems impossible to set it in the checkout. And if I set it after using
an update, the customer will not be aware of this autocancellation. Any
advice?

Besides, my business is a bit an edge case but there are other that are
not: for instance sell both a digital book per unit and as a monthly
subscription.

I am doing some testing to deploy another cloud function with a slightly
adapted code but it's a bit a pity to my mind. However, I certainly don't
see all the implications.

Thanks again,
Best

**Comment by dthib** [comment]
Besides, I would be happy to contribute to this extension. Is it possible and in particular how can I deploy the modified extension if i create a branch ?
Thanks again

**Comment by thorsten-stripe** [comment]
@dthib you could alternatively do a $0 yearly subscription paired with the one time product: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#adding-multiple-prices-including-one-time-setup-fees This way you still get the benefit of using subscriptions but hopefully without your customers dropping off.

> Besides, I would be happy to contribute to this extension. Is it possible and in particular how can I deploy the modified extension if i create a branch ?

I'm afraid you can't yet because this is this in private alpha on the Firebase side.

I'm going to close this out as it seems to be too edge case for use to want to support broadly.

**Comment by dthib** [comment]
Hi @thorsten-stripe ,
Yes, i have already tested this as well. it's not perfect but it works. 
The other option i have tested as well is to deploy the slightly adjusted version of your cloud function in order to handle payment checkout. I am a bit disapointed to close it because it's not a lot of code and as mentioned it worth it if you want to sell both one time product & subscription (for instance sell both a digital book per unit and as a monthly
subscription as mentioned above).
Anyway, nice & useful work

**Comment by rafekun** [comment]
I agree with @dthib. Supporting one time product is helpful for many devs.

**Comment by thorsten-stripe** [comment]
See the related discussion here: https://github.com/stripe/stripe-firebase-extensions/issues/39#issuecomment-671809586

**Comment by thorsten-stripe** [comment]
One time payments are supported as of version 0.1.12: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-0112---2021-04-29

You can update the extension in your Firebase console to enable this.
