### ISSUE TITLE
Sync all customer data with stripe

### ISSUE THREAD

**Issue by dthib** [stripe/stripe-firebase-extensions#137]
# Feature request

- Extension name:`firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

I would like to be able to keep in sync customer information with stripe (https://stripe.com/docs/api/customers/create?lang=node). In particular, address and tax informations (tax_exempt, tax_id_data) but i guess other information can be useful depending on the usage.

## Describe the solution you'd like

listen to admin.firestore().collection(config.customersCollectionPath).doc(uid) changes and update stripe customer accordingly.

## Describe alternatives you've considered

I can deploy my own cloud function to do the job but i think it can be useful to others.

Thanks,
Best regards

**Comment by dthib** [comment]
@thorsten-stripe any feedback for this issue ?

**Comment by thorsten-stripe** [comment]
@dthib the customer object includes PII that we don't want to sync by default due to GDPR considerations. Therefore I want to keep it to the minimalist lookup table that we have at the moment. If you want to manage customer data in Firebase, you should do so yourself and with full GDPR compliance for your use case.

**Comment by dthib** [comment]
@thorsten-stripe i totally understand the concern. But as there is a SYNC_USERS_ON_CREATE option, why not add a full_sync mode in addition to existing mode? This way, the extension is totally sync for users wanting full sync with GDPR compliance of course.
Best

**Comment by dthib** [comment]
In addition, what push me towards this full sync is the need to have a valid customer address for invoices.
Best !
