### ISSUE TITLE
[Bug] Subscriptions for metered billing plans not syncing

### ISSUE THREAD

**Issue by DariusKopka** [stripe/stripe-firebase-extensions#138]
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug

The webhook handle function throw follow exception:

ext-firestore-stripe-subscriptions-handleWebhookEvents
❗️[Error]: Webhook handler for Stripe event [evt_1ILRo4E9U7tLkcTd4NyR9z2m] of type [customer.subscription.created] failed: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field "quantity"). If you want to ignore undefined values, enable `ignoreUndefinedProperties`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to stripe dashboard create a webhook for the webhook handle extension function
2. Create a costumer and products
3. Create a new abo, 'customer.subscriptions.create'
4. See error in the webhook logs and in the firebase functions log

## Expected behavior

Created subscription collection in customer in firebase.

I think the issue is :

quantity: subscription.items.data[0].quantity

in your code , i think this muss work

quantity: subscription.quantity

**Comment by thorsten-stripe** [comment]
I updated to the newest Stripe API version where the quantity param has been moved: https://stripe.com/docs/api/subscriptions/object#subscription_object-items-data-quantity

It works fine for me on https://stripe-subs-ext.web.app/. I wonder if this might be related to metered pricing.

Could you please comment below the details about your pricing plan and the code snippet that you use to create the checkout session?

**Comment by DariusKopka** [comment]
My pricing plan is: bundle1: 99,00€/month -> 300units, bundle2: 199,00€/month -> 1000units, bundle3: 299,00€/month -> 100000000 units. I dont create a checkout session in firebase. I am send a new customer over webhook to firebase and the subscription sync over webhook to firebase. I thin i have create the webhook with the old api an letter i have updated the firebaseextenssion.

**Comment by thorsten-stripe** [comment]
I was able to reproduce this error when using a metered billing pricing plan. I'll work on a fix. Unfortunately until then metered billing plans will not sync to Cloud Firestore!

**Comment by thorsten-stripe** [comment]
Unfortunately Firebase has not yet deployed version 0.1.11, sorry!

I'll keep this open until v0.1.11 has been deployed
