### ISSUE TITLE
Usage based pricing and identity verification

### ISSUE THREAD

**Issue by techronin** [stripe/stripe-firebase-extensions#139]
# Feature request

- Extension name: [e.g. `firestore-stripe-subscriptions`]

A clear and concise description of what you want and what your use case is.

it would be ideal to have the full suite of Stripe products available in Firebase, however in my particular case Im interested in usage based pricing

## Describe the solution you'd like

Usage based pricing allows me to charge customers for what they use in my app, eg like rate limiting API's or purchasing singular services that are not bundled into a flat monthly fee.

Perhaps this is already available, but there is no clear tutorial or documentation on how to impliment this. I would like to see a video or some documentation on how to configure Firebase to read these types of Products from Stripe

I'm considering simply using the Stripe identity verification tool instead of Firebase. It might even be a good idea to integrate this KYC into Firebase as this would allow for more use cases to be built.

**Comment by thorsten-stripe** [comment]
> Usage based pricing allows me to charge customers for what they use in my app, eg like rate limiting API's or purchasing singular services that are not bundled into a flat monthly fee.

Usage based pricing is already supported, see https://github.com/stripe/stripe-firebase-extensions/issues/134#issuecomment-783490547

Documentation on how to report usage can be found here: https://stripe.com/docs/billing/subscriptions/metered-billing#reporting-usage This is something you need to implement yourself as it tends to be very custom depending on your use case and can't be easily standardized.

> I'm considering simply using the Stripe identity verification tool instead of Firebase. It might even be a good idea to integrate this KYC into Firebase as this would allow for more use cases to be built.

Identity verification is a use-case not related to subscriptions and wouldn't fit into this extension. But of course you can implement it with Cloud Functions yourself based on your needs.
