### ISSUE TITLE
Lost subscription items in firebase

### ISSUE THREAD

**Issue by dthib** [stripe/stripe-firebase-extensions#140]
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug

If a subscription with two items is created, the items structure is lost in firebase. Only the list of prices is saved. It means in particular that the 2nd item quantity is lost. 
See https://github.com/stripe/stripe-firebase-extensions/blob/a33c2ad0f79d14c2102d6adbbeccba04b76ddb44/firestore-stripe-subscriptions/functions/src/index.ts#L360 with the hard-coded index 0.
it means also that item metadata are lost as well.

## To Reproduce

Create a subscription with two items programmatically or directly in the stripe dashboard.

## Expected behavior

I would expect to keep the same data model as stripe to ease understanding and avoid loosing some information (only replace data types: for instance timestamp and document ref in order to leverage firebase capacities).

**Comment by thorsten-stripe** [comment]
Quantity used to be a top-level param on the subscription, only has been removed in the most recent API version. However, I decided to keep it around for backwards compatibility.

I'll add the subscription items with the next release.

**Comment by dthib** [comment]
great thanks !
