### ISSUE TITLE
Stripe extension: Bill based on a non-predefined value 

### ISSUE THREAD

**Issue by railerbailer** [stripe/stripe-firebase-extensions#141]
# Feature request

- Extension name: firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.
My app are running ads for clients and I want to be able to charge based on revenue spent on ads. E.g. App spends $400 on ads, then I want to charge 2.3%, not a set number.

## Describe the solution you'd like

I would like to be able to specify the amount for next charge in stripe

## Describe alternatives you've considered

Skipping the extension and manually installing from Stripe.

**Comment by thorsten-stripe** [comment]
@railerbailer this doesn't sound like a subscription but rather a simple invoicing use case. You might be better off using our invoices extension instead: https://firebase.google.com/products/extensions/firestore-stripe-invoices

If you want to use subscriptions for this, two options:

1. You use metered billing: this works if you always charge 2.3%. Then you can just report the units (400) and have Stripe apply the correct invoice item at the end. https://stripe.com/docs/billing/subscriptions/examples#usage-based-pricing
2. You subscribe the customer to a $0 subscription and then add an invoice item to their customer object within the billing period: https://stripe.com/docs/api/invoiceitems/create Any invoice items added to a customer object will automatically be added to their next invoice which will be created by the $0 subscription.
