### ISSUE TITLE
Failed to retrieve function source code

### ISSUE THREAD

**Issue by zaheddec** [stripe/stripe-firebase-extensions#145]
Firebase stripe subscriptions extension was working fine until i upgraded to V0.1.10. Firebase is giving Failed to retrieve function source code.
<img width="1017" alt="Screen Shot 2021-03-02 at 12 40 10 AM" src="https://user-images.githubusercontent.com/30424148/109603757-4ac38780-7af0-11eb-8f45-7e611984ae19.png">

**Comment by thorsten-stripe** [comment]
I'm afraid this is an issue on the Firebase side. Please reach out to their support team.
