### ISSUE TITLE
config for not asking a billing address?

### ISSUE THREAD

**Issue by nemet4ndrea** [stripe/stripe-firebase-extensions#149]
Is there a config for not asking a billing address? If we do not send anything as mail just email why do we as a billing address?

Thanks!

**Comment by thorsten-stripe** [comment]
Heya, sorry, this is only documented in the changelog atm: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-018---2020-11-19

[feat] - The extension now defaults to collecting the customer's billing address during checkout and sets it as the address on the Stripe customer object. If you don't want to collect it, you can pass `billing_address_collection: auto` to the checkout session doc creation.
