### ISSUE TITLE
Support  subscription_data.coupon in createCheckoutSession

### ISSUE THREAD

**Issue by robertreppel** [stripe/stripe-firebase-extensions#15]
# Feature request

- Extension name: firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.

Would be nice to be able to support coupons. 

## Describe the solution you'd like

1. Add the coupon value when creating a checkout session:

```
  const docRef = await db
    .collection('customers')
    .doc(currentUser)
    .collection('checkout_sessions')
    .add({
      price: formData.get('price'),
      success_url: window.location.origin,
      cancel_url: window.location.origin,
      subscription_data: { coupon: "MYVALUABLECOUPON" }
    });
```
2. In src/functions  ```exports.createCheckoutSession```, add the coupon to the parameters for checkout.sessions.create . 

Would be nice to have (... assuming this approach works....?).  

Best regards,

Robert

**Comment by thorsten-stripe** [comment]
@robertreppel thanks for suggesting this. We're working on a feature with Checkout that will allow users to insert a coupon/promo code into the Checkout interface directly. Would this be sufficient? Or do you require a programmatic way (unrelated to user input) of applying coupon codes?

**Comment by robertreppel** [comment]
That would be perfect. I wasn't looking for a programmatic way to do it; an enhancement to the Checkout interface would be ideal.

**Comment by thorsten-stripe** [comment]
Great, thanks for the feedback everyone! We're very close with this. I'm hoping we can get it into the Thursday release, will keep y'all posted.

**Comment by robertreppel** [comment]
Awesome! Works great and exactly what I was looking for. Thanks Thorsten, much appreciated!

**Comment by calacianu** [comment]
Hi @thorsten-stripe is this feature implemented? or still in backlog :)
thank you

**Comment by jsteele-stripe** [comment]
@calacianu What feature are you asking about?

**Comment by calacianu** [comment]
@jsteele-stripe - the possibility to add coupons to checkout_session :)

**Comment by jsteele-stripe** [comment]
@calacianu You can, via [`allow_promotion_codes`](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-allow_promotion_codes). It's unlikely that this extension will support the `coupons` parameter for reasons previously outlined.

**Comment by ryanwhitemedia** [comment]
Commenting here hopefully can get an answer, have a use case where we need to pass through a coupon to track affiliates but it is breaking. Can someone direct me to why we can't pass through the coupon parameter? We need it to automatically be applied in our case.
