### ISSUE TITLE
One-time payment

### ISSUE THREAD

**Issue by bharden** [stripe/stripe-firebase-extensions#151]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

I love you extension. I have been using it practically since it launched. I do have one feature request. I would really like to be able to use your extension to make one time payments through stripe. I have a subscription based website but we have started offering some products for one time purchase and it would be really nice if I could run everything through the extension. I sincerely hope that I have just missed something and there is a way to do this using the extension. Please tell me if there is

**Comment by thorsten-stripe** [comment]
@bharden thanks for the kind words. See some reasoning on one-time payments here: https://github.com/stripe/stripe-firebase-extensions/issues/39#issuecomment-671809586 and please add your use-case there, and would be great if you could share you website so I can have a look.

**Comment by thorsten-stripe** [comment]
One time payments without subscriptions are supported as of version 0.1.12: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-0112---2021-04-29

You can update the extension in your Firebase console to enable this.
