### ISSUE TITLE
Delete Stripe customer objects only at the end of the month (after all outstanding payments have been collected)

### ISSUE THREAD

**Issue by t-kaufmann** [stripe/stripe-firebase-extensions#152]
# Feature request

- Extension name: firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.

Deleting a user from Firebase Authentication also deletes the Stripe customer object. If the user has outstanding payments (e.g. the user is on a metered billing plan and always pays at the end of the month), all payments will be lost. 

## Describe the solution you'd like

It would be great if there was an option for the extension to only delete the customer object at the end of the month (or when all outstanding payments have been collected). 

## Describe alternatives you've considered

Currently, the only alternative for this problem seems to be to not delete Stripe customer objects via the extension at all, meaning that I have to disable the user.delete cloud function.

## Additional context

N/A

**Comment by thorsten-stripe** [comment]
Could you just wait with the user deletion in Firebase until their subscription has ended? Why would you need to delete the user earlier?

**Comment by t-kaufmann** [comment]
You are right, this would be possible. In some cases though this might lead to some strange beahaviour. Assuming a user deletes his account, he could technically still sign in with his old credentials for the rest of the month as the account is still linked to Firebase Authentication (only the Firestore data would be deleted). This might suggest that the user wasn't actully deleted..

Other than that, a delayed deletion wouldn't be a problem.
