### ISSUE TITLE
Tax rates on customer portal

### ISSUE THREAD

**Issue by dancixx** [stripe/stripe-firebase-extensions#154]
Hi guys

can you help me with tax rates. So when the customer pays first i can pass the tax_rates property for checkout-session, but when would change the subscription plan cant see the tax_rates and after the change didnt get the tax_rates information in response json. Do you have any idea how can i solve this? Of course the tax wont be on the invoice too.

Thx for help.

**Comment by thorsten-stripe** [comment]
@dancixx sorry, this one slipped through the cracks.

In the customer portal currently only "static" tax rates are supported that you specified during the checkout session creation: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#applying-static-tax-rates

In Stripe checkout it will look like this:
![image](https://user-images.githubusercontent.com/23213994/112848348-90b54080-90da-11eb-824d-24e077e5f862.png)

And in the customer portal like this: 
![image](https://user-images.githubusercontent.com/23213994/112849684-e0e0d280-90db-11eb-9d26-f00147e3e1bf.png)

**Comment by thorsten-stripe** [comment]
It works as long as you've specified the `tax_rates` on the initial checkout session creation, e.g.

```js
const docRef = await db
  .collection('${param:CUSTOMERS_COLLECTION}')
  .doc(currentUser)
  .collection('checkout_sessions')
  .add({
    price: 'price_1GqIC8HYgolSBA35zoTTN2Zl',
    tax_rates: ['txr_1HCjzTHYgolSBA35m0e1tJN5'],
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
```

**Comment by dancixx** [comment]
Does this work with createPortalLink method too?

**Comment by thorsten-stripe** [comment]
@dancixx no, you don't specify this when creating the portal link. The tax rate is stored on the subscription and the portal reads it from there.

**Comment by dancixx** [comment]
@thorsten-stripe It is interesting, because I can see the tax data on firestore subs doc but on customer portal on subs update no tax data. :(

**Comment by thorsten-stripe** [comment]
Can you provide some screenshots please?

**Comment by dancixx** [comment]
@thorsten-stripe 
First is the existing subs in firestore there is the tax_rates data
![Képernyőfotó 2021-03-29 - 16 49 27](https://user-images.githubusercontent.com/56868953/112855030-bb899f80-90ae-11eb-816e-0acb92c8889f.png)

Second: on customer portal on subs update there is no tax data, just can see 'adót nem tartalmaz' (sry for lang)
![Képernyőfotó 2021-03-29 - 16 49 40](https://user-images.githubusercontent.com/56868953/112855067-c3494400-90ae-11eb-8351-6e3633a4c996.png)

Thrid: on checkout session you can see the VAT correctly.
![Képernyőfotó 2021-03-29 - 16 50 49](https://user-images.githubusercontent.com/56868953/112855245-ec69d480-90ae-11eb-8f2d-418f5eb18cdd.png)

These are my callbacks for methods:
```
export function checkoutSession({ firebase, firestore }, priceId, teamId, tierLevel, product, user) {
    return async function () {
        console.log({product})
        try {
            const docRef = await firestore
                .collection('profiles')
                .doc(user.uid)
                .collection('checkout_sessions')
                .add({
                    billing_address_collection: 'required',
                    price: priceId,
                    tax_rates: ['txr_1HxioRABw9RvoAv3vLypvhDB'],
                    success_url: window.location.origin + '/success',
                    cancel_url: window.location.origin,
                    allow_promotion_codes: true,
                    default_tax_rates: ['txr_1HxioRABw9RvoAv3vLypvhDB'],
                    metadata: {
                        userUid: user.uid,
                        teamUid: teamId,
                        tierLevel: tierLevel,
                        productId: product.id,
                        stripe_metadata_subsUid: product.stripe_metadata_subsUid,
                        stripe_metadata_team: product.stripe_metadata_team,
                        stripe_metadata_tierLevel: product.stripe_metadata_tierLevel
                    }
                });

            docRef.onSnapshot(async (snap) => {
                const { error, sessionId } = snap.data();
                if (error) {
                    alert(`An error occured: ${error.message}`);
                }
                if (sessionId) {
                    const stripe = await loadStripe('pk_test_51HxiKAABw9RvoAv3LwjXhz3XDTJ3zCzcN3rLhkaOQyHOpjmOU1jsgnwcVa8xsHWOrr2HfFL4ZjUN71oHukcK0k6U00lt6OEdg8');
                    stripe.redirectToCheckout({ sessionId });
                }
            });
        } catch (error) {
            console.log(error);
        }
    };
}

export function createPortalLink() {
    return async function () {
        try {
            const functionRef = fb.app().functions('us-central1').httpsCallable('ext-firestore-stripe-subscriptions-createPortalLink');
            const { data } = await functionRef({ returnUrl: window.location.origin });
            console.log({ data });
            window.location.assign(data.url);
        } catch (error) {
            console.log(error);
        }
    };
}
```

**Comment by dancixx** [comment]
@thorsten-stripe can see some issue there?

**Comment by thorsten-stripe** [comment]
@dancixx sorry for the delay here :( This is an issue with how Stripe invoices handle proration for invoice items. I've added a workaround here that should hopefully work for you: https://github.com/stripe/stripe-firebase-extensions/pull/170

**Comment by dancixx** [comment]
@thorsten-stripe I updated the new version, and I watched the changelog but I didnt find which point should I use or should I change anything, if not then is there no changes in my case.

**Comment by thorsten-stripe** [comment]
@dancixx correct, this was an internal change only: https://github.com/stripe/stripe-firebase-extensions/pull/170/files#diff-70e8f3204cac2da7d57e95d6985978367a24a4f399fdd4099d1a9fbe3f724b21R154-R160

So for new subscriptions your code above should work, the important step is setting the top-level `tax_rates` param (example: ), which you are doing.

You can see this in action in the demo: https://stripe-subs-ext.web.app

On the invoice you will then see the tax that was applied: 
![image](https://user-images.githubusercontent.com/23213994/116503366-74c6d980-a8e8-11eb-9693-70c718452c55.png)
![image](https://user-images.githubusercontent.com/23213994/116503399-8f00b780-a8e8-11eb-8c04-ee84e7f54658.png)

**Comment by dancixx** [comment]
@thorsten-stripe thank you very much it worked.

I have only one more question, when I set the properties for the checkout session for subscription mode, should set the "mode" params set, or only when I use "payment" mode, and this is the same with the tax_rates, I think it works with default_tax_rates too. So my concept can be seen below, is it correct?

```
const docRef = await firestore
                .collection('profiles')
                .doc(user.uid)
                .collection('checkout_sessions')
                .add({
                    billing_address_collection: 'required',
                    price: priceId,
                    tax_rates: ['txr_1HxioRABw9RvoAv3vLypvhDB'],
                    success_url: window.location.origin + '/success',
                    cancel_url: window.location.origin,
                    allow_promotion_codes: true,
                    metadata: {
                        userUid: user.uid,
                        teamUid: teamId,
                        tierLevel: tierLevel,
                        productId: product.id,
                        stripe_metadata_subsUid: product.stripe_metadata_subsUid,
                        stripe_metadata_team: product.stripe_metadata_team,
                        stripe_metadata_tierLevel: product.stripe_metadata_tierLevel
                    }
                });
```

**Comment by thorsten-stripe** [comment]
@dancixx `mode` defaults to `subscription` only if you want to do one-time payments you have to specify `mode: payment`.  But you can also supply `mode: subscription` it's just not required.

`tax_rates` needs to be `tax_rates` and is then mapped to `default_ tax_rates` by the extension.
