### ISSUE TITLE
Portallink on specified url

### ISSUE THREAD

**Issue by dancixx** [stripe/stripe-firebase-extensions#155]
Hi

can you give support to inject specified url in createPortalLink function? Can be useful if the customer should change the subscription and push direct on the update screen.

Thanks for helping. :)

**Comment by thorsten-stripe** [comment]
Hello, I'm afraid I'm not sure what you're asking. Can you please clarify and maybe add an example?

**Comment by dancixx** [comment]
Hi, 

i go to the customer portal i got this screen first.
![Képernyőfotó 2021-03-15 - 18 11 24](https://user-images.githubusercontent.com/56868953/111192883-dbeb3180-85b9-11eb-906a-ddf97058ffd3.png)

Then i go for the next step choose new subscription item, and got this screen.
![Képernyőfotó 2021-03-15 - 18 12 23](https://user-images.githubusercontent.com/56868953/111193004-ff15e100-85b9-11eb-9a78-43d85c36a7b0.png)

The last step is to choose new subs plan, and got this screen:
![Képernyőfotó 2021-03-15 - 18 13 19](https://user-images.githubusercontent.com/56868953/111193132-2076cd00-85ba-11eb-8d32-7ad0a88eb81d.png)

would be great if i can redirect the customer on the last screen after he choose the new plan in user profile.

**Comment by thorsten-stripe** [comment]
The user will have to click the return link to get back to your page
![image](https://user-images.githubusercontent.com/23213994/111331060-8000d580-86ab-11eb-8643-9cce1ec99212.png)

**Comment by dancixx** [comment]
In our platform all user has a screen like this. If user wants upgrade an existing subscription plan he has to click on manage your account, then update plan and then choose a new plan so there are 3 unnecessary steps to achieve the new plan. So my request was that would be great to give the createportal mehtod custom url which redirect the user on the last step.

Now i got an url like this:
https://billing.stripe.com/session/_J7uKCll1nj6VYaFhq9WJsvjuhsGWKV3

but i need something like this on first click:
https://billing.stripe.com/session/_J7uKCll1nj6VYaFhq9WJsvjuhsGWKV3/subscriptions/sub_J7f4oXndjqn5Xi/preview/price_1IUrJ2ABw9RvoAv3DVVCIkzD

![Képernyőfotó 2021-03-16 - 16 04 51](https://user-images.githubusercontent.com/56868953/111331607-5925ad80-8671-11eb-8967-7da542d6d995.png)

**Comment by thorsten-stripe** [comment]
Ah okay, understood. That functionality does not come out of the box. You would have to append `/subscriptions/sub_J7f4oXndjqn5Xi/preview/price_1IUrJ2ABw9RvoAv3DVVCIkzD` to the session URL yourself.

**Comment by dancixx** [comment]
Sorry for unclear explanation, but yes exactly i need this option, but creatportal method cant give just a retunrUrl property and i dont want too override your extension because it is awesome. :)
