### ISSUE TITLE
Images broken in preinstall

### ISSUE THREAD

**Issue by jhuleatt** [stripe/stripe-firebase-extensions#156]
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug

The images in `PREINSTALL.md` don't display in [github](https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/PREINSTALL.md) or in the [extension details page](https://firebase.google.com/products/extensions/firestore-stripe-subscriptions).

## Expected behavior

The images should show in both places. Should we re-host them somewhere else?

### Extension details page:

<img width="503" alt="Screen Shot 2021-03-16 at 11 59 22 AM" src="https://user-images.githubusercontent.com/3759507/111340500-1226c080-864f-11eb-8c0d-bb3bf83d55b4.png">

### Github:

<img width="599" alt="Screen Shot 2021-03-16 at 11 59 44 AM" src="https://user-images.githubusercontent.com/3759507/111340530-1b179200-864f-11eb-87d3-10909b493828.png">

**Comment by thorsten-stripe** [comment]
Looks like they are back 👍
