### ISSUE TITLE
Add customer email to firestore on createCustomerRecord

### ISSUE THREAD

**Issue by DCSnip3r** [stripe/stripe-firebase-extensions#157]
# Feature request

firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.

I'm planning to extend functionality with Firestore's "Send Email" extension, which requires there to be an "email" field in the customer documents in order to work. The current createCustomerRecord function, triggered by user creation, creates a record with the customer's stripe ID and their stripe link, but it would be great if it could also add the customer's email address to the document at the same time.

## Describe the solution you'd like

Insert `email: email,` after line 62 in index.ts

## Describe alternatives you've considered

I can create another firestore trigger to retrieve the customer email and then add it to the record, but this requires more reads writes and code. 

It would be better if the Send Email extension could look up the email from the auth list instead of the linked record, but this does not seem likely to occur

**Comment by thorsten-stripe** [comment]
Yes, that sounds sensible. Will add with the next version, but can't yet say when exactly.

**Comment by thorsten-stripe** [comment]
This has been added as of version 0.1.12: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-0112---2021-04-29

You can update the extension in your Firebase console to enable this.
