### ISSUE TITLE
RedirectToCheckout on Mobile Apps

### ISSUE THREAD

**Issue by gmacdev** [stripe/stripe-firebase-extensions#159]
# Feature request

- Extension name: [`firestore-stripe-subscriptions`]

## Is your feature request related to a problem? Please describe.

What if we want to open the checkout page from an Android App to a mobile browser? Is there a way or can we create one?

## Describe the solution you'd like

We want to do a redirectToCheckout call from our Android App (which opens the checkout page on a mobile browser) using the session ID the extension created for us after creating a checkout session in firestore.

## Additional context

All we need to know is how to open the checkout page i.e how we can implement redirectToCheckout js call on the Android app which would generate a URL for the checkout page to redirect the user to the same via a mobile browser. (or a similar implementation)

## Why

This helps independent app developers who don't have any knowledge of implementing JS on a website or just want to launch the checkout directly from their app into a mobile browser. (due to the Play store policy of no 3rd party in-app purchase should be allowed inside the app). This is a similar approach other apps have implemented (like Spotify) using Adyen payment implementation on their website for the checkout. Here we just launch the stripe checkout page in a mobile browser instead of any website.

**Comment by thorsten-stripe** [comment]
This is likely not allowed, see https://github.com/stripe/stripe-firebase-extensions/tree/next/firestore-stripe-subscriptions#recommended-usage

That being said, if you have a legitimate use case, you will still need to host a static page that uses Stripe.js to call `redirectToCheckout` with the session ID created from the extension.
