### ISSUE TITLE
Remove automatic Stripe Customer deletion

### ISSUE THREAD

**Issue by jaytavares** [stripe/stripe-firebase-extensions#160]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

The functionality to delete Stripe Customer objects in response to Firebase Auth User deletion has resulted in a critical loss of our production data! While migrating Auth users between Firebase projects, the "Run Subscription Payments with Stripe" extension deleted all of our Stripe Customers. According to the [Stripe API documentation](https://stripe.com/docs/api/customers/delete), Stripe Customer deletion is permanent:

> Permanently deletes a customer. It cannot be undone. Also immediately cancels any active subscriptions on the customer.

We have opened a case with Stripe support; hopefully they will be able to recover our lost data! 🤞

This feature (which cannot be disabled) was introduced in PR #5 in response to issue #3. I don't think it is acceptable to have such destructive functionality baked in to this extension.

## Describe the solution you'd like

Remove the functionality to delete Stripe Customers automatically in response to Auth User deletion. At a _minimum_, provide a configuration option that defaults to disabled.

## Describe alternatives you've considered

No alternative. See above.

## Additional context

The Stripe Firebase extensions are "Created and tested by Stripe, these official Stripe Firebase extensions are reliable and secure." according to the repo README. They're clearly intended to be used in a production environment. It seems as though a feature this potentially destructive has the opportunity to cause more harm than good. If a user really needs to delete Stripe customers, the solution is as easy as a one line cloud function: 

```typescript
export const deleteStripeCustomer = functions.firestore.document('[users path]/{uid}').onDelete(async snap => {
    await stripe.customers.del(snap.data().stripeId)
  })
```

**Comment by thorsten-stripe** [comment]
While this behavior is clearly outlined in the [postinstall docs](https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#delete-user-data) I do recognize that not everyone will read the docs. Therefore as of version 0.1.12, the default behavior has been changed to "Do not delete": https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-0112---2021-04-29

You can update the extension in your Firebase console to enable this.

**Comment by jaytavares** [comment]
> While this behavior is clearly outlined in the [postinstall docs](https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#delete-user-data) I do recognize that not everyone will read the docs. Therefore as of version 0.1.12, the default behavior has been changed to "Do not delete": https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-0112---2021-04-29
> 
> You can update the extension in your Firebase console to enable this.

Thank you for this update. I'm not thrilled with your implication that this problem resulted because I didn't read the documentation. I did. I knew that deletion of firebase users in production would delete their corresponding Stripe customers. It wasn't my intention to delete them, it happened by accident. My concern here is that good engineering practices dictate that we plan for disaster and enabling such destructive behavior by default doesn't really jibe with that. Thanks again for adding that config option.

**Comment by JakeMalis** [comment]
Wait so you knew exactly what would happen (since you read the documentation), yet seem surprised/annoyed by the fact that exactly what the documentation said happened? 😂

**Comment by thorsten-stripe** [comment]
@jaytavares sorry for my phrasing, I didn't mean to imply that you didn't read the docs, and I absolutely realize that this can happen by accident, and I also appreciate your feedback and sharing this incident with us in order to avoid others running into it!

**Comment by jaytavares** [comment]
No worries, @thorsten-stripe 👍
