### ISSUE TITLE
Customer / subscription webhooks not working

### ISSUE THREAD

**Issue by apeiniger** [stripe/stripe-firebase-extensions#161]
# Bug report

- Extension name: firestore-stripe-subscriptions@0.1.11

## Describe the bug

I installed the Firestore / Stripe extension and when I create new products in Stripe it syncs alright and I can see the collection in Firestore. The sync of customers and subscriptions is not working though.

## To Reproduce

When I checked the webhook logs in the Stripe dashboard I saw the following:

![image](https://user-images.githubusercontent.com/2005574/113106337-f0a70680-9202-11eb-964d-c3e941891630.png)

I then went to the Google Cloud console and added "allUsers" to the corresponding cloud function (as found in one other issue here). Then I retried the webhooks and the following came up:

![image](https://user-images.githubusercontent.com/2005574/113106459-16cca680-9203-11eb-90f6-cc8817445416.png)

This is the error in the function logs:

![image](https://user-images.githubusercontent.com/2005574/113107843-ab83d400-9204-11eb-9251-071e76b20868.png)

Could it be a problem that I created the customer in Stripe via the Stripe dashboard?

## Expected behavior

I expected that all webhooks and functions would work right out of the box.

## Screenshots

See above.

## System information

Installed via Chrome on Mac

**Comment by thorsten-stripe** [comment]
The main problem is that your webhook handler was not working when the checkout session was being created. The checkout session is what creates the customer lookup record when it doesn't exist already. 

So creating a new checkout session for this user should set up the record and make future lookups work.

**Comment by thorsten-stripe** [comment]
> Could it be a problem that I created the customer in Stripe via the Stripe dashboard?

Actually that might be the issue. You need to let the extension create the customer object and add the lookup table.
