### ISSUE TITLE
Q: Approach for website with subscriptions & physical products offers

### ISSUE THREAD

**Issue by nemet4ndrea** [stripe/stripe-firebase-extensions#164]
Can we use firebase-stripe-extension to also checkout one time payments, not installation payments or fees. Like for e.g. if I build a website where people buy subscriptions to consume content monthly, and now I want to add a small shop to it to sell some swag products/apparel what approach should I embrace? I want to keep the code for subscription if possible.

Thanks!

**Comment by thorsten-stripe** [comment]
I'd recommend keeping sales of physical goods separate as you need more sophisticated tax and fulfillment management. You can also refer to this previous discussion: https://github.com/stripe/stripe-firebase-extensions/issues/39

But for selling apparel, I'd recommend something like WooCommerce, Shopify, WIX etc.

**Comment by thorsten-stripe** [comment]
One time payments without subscriptions are supported as of version 0.1.12: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-0112---2021-04-29

You can update the extension in your Firebase console to enable this.
