### ISSUE TITLE
Webhooks have stopped working completely

### ISSUE THREAD

**Issue by sulmanazhar2** [stripe/stripe-firebase-extensions#165]
# Bug report

firebase-stripe-extensions

## Describe the bug

My webhooks inside stripe have stopped working for no reason. I didn't change any setting but from today it has stopped working completely.

These are my webhooks but they all have stopped working

![image](https://user-images.githubusercontent.com/54376322/114960623-ddda3600-9e80-11eb-820f-da9fb999ff50.png)

## Expected behavior

They should work

## Screenshots

They last worked yesterday

![image](https://user-images.githubusercontent.com/54376322/114960763-25f95880-9e81-11eb-9e0e-10cf7d165de9.png)

**Comment by sulmanazhar2** [comment]
Sending test webhooks with dummy data is working

Test webhooks from here

![image](https://user-images.githubusercontent.com/54376322/114961194-fbf46600-9e81-11eb-84f3-73a508e36365.png)

**Comment by thorsten-stripe** [comment]
This is likely related to some webhook delivery issues earlier: https://twitter.com/stripestatus/status/1382880735942434817

Please get in touch with support for more details and help: https://webchat.freenode.net/#stripe or https://support.stripe.com/
