### ISSUE TITLE
Support collection of business names 

### ISSUE THREAD

**Issue by cvoadmin** [stripe/stripe-firebase-extensions#166]
# Feature request

- Extension name: firestore-stripe-subscriptions

## Describe the solution you'd like

Collection of company/business names as an optional field.

**Comment by thorsten-stripe** [comment]
This is not yet supported by Stripe Checkout, but will be supported in the future. I'll keep this open to track it.

**Comment by thorsten-stripe** [comment]
This is now supported by setting `tax_id_collection: true,`

![image](https://user-images.githubusercontent.com/23213994/130755068-a1f17ace-d2f2-4933-b338-76de9eceec7b.png)

**Comment by cvoadmin** [comment]
What is the best approach of you use a 0% ID? I'm not sure what to make of the Stripe Tax fees. We are not enrolled.
