### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by jakubtomas108** [stripe/stripe-firebase-extensions#167]
Hey guys. 

First of all, thank You very much for this extension, it saved me a lot of time. 

I had one bad encounter with sync. Created a user, everything went through, subscription created (confirmed by stripe dashboard), but firestore didn't sync. So i refreshed several times, but nothing. It happened only one time. Did some of you encountered this behavior before? Is there a way to manually sync in case the firestore user doesn't have a subscription collection created by the extension (without writing custom BE code)?

Thanks

**Comment by jakubtomas108** [comment]
i know what i can do - i can write one BE function, that will create stripe portal session in case the the subscription collection is missing

**Comment by thorsten-stripe** [comment]
The sync issue might have been related to https://github.com/stripe/stripe-firebase-extensions/issues/167

However, the customer does not need a subscription for you to create a customer portal session. As long as the customer ID exists in Cloud FIrestore, the extension is able to create a session using the `createPortalLink` callable function.
