### ISSUE TITLE
Feature request: Loading spinner onclick in Subscribe button

### ISSUE THREAD

**Issue by cvoadmin** [stripe/stripe-firebase-extensions#168]
# Feature request

- Extension name: firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.

There's a redirect delay whenever you click the Subscribe button. It grays out for a few seconds pre redirect, which confuses the customer.

## Describe the solution you'd like

A loading spinner on-click inside the button will increase conversion.

**Comment by thorsten-stripe** [comment]
This is not something the extension handles. You will have to add this on your end to your button.
