### ISSUE TITLE
Please add changelog for different versions

### ISSUE THREAD

**Issue by RezaRahmati** [stripe/stripe-firebase-extensions#175]
# Feature request

- Being able to see what is changed in newer version to decide if we should upgrade the extension or not

## Is your feature request related to a problem? Please describe.

Right now in firebase it shows there is a newer version, but we are not blindly upgrade unless there are new features that we need or defects fixed that affect us  

## Describe the solution you'd like

Add changelog and releases to git repo.

**Comment by thorsten-stripe** [comment]
What are you missing from the current changelogs?

* https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md
* https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-invoices/CHANGELOG.md

These are also linked from the Firebase console for easier discovery. Are you not seeing them there?
![image](https://user-images.githubusercontent.com/23213994/116955594-926bb880-acc5-11eb-8b16-30e7e37b8841.png)

**Comment by RezaRahmati** [comment]
@thorsten-stripe  Thank you for your reply, I think I wasn't able to find it because usually there is a release link in github, that shows versions + change log, I wasn't able to see it.

For example see this one
![image](https://user-images.githubusercontent.com/10086092/117005494-50d31180-acb5-11eb-9af8-24bbae65b850.png)

and this is how I see this repo
![image](https://user-images.githubusercontent.com/10086092/117005550-621c1e00-acb5-11eb-8bbf-a188abcecc3a.png)
