### ISSUE TITLE
 Webhook handler for event of type [price.created] failed: 'rak_plan_read' permission

### ISSUE THREAD

**Issue by DCSnip3r** [stripe/stripe-firebase-extensions#176]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

Error logged while creating a tiered price:

`ext-firestore-stripe-subscriptions-handleWebhookEvents

❗️[Error]: Webhook handler for  Stripe event [] of type [price.created] failed: The provided key 'rk_test_*****************************************************************************************************' does not have the required permissions for this endpoint on account '******************'. Having the 'rak_plan_read' permission would allow this request to continue. 

`

## To Reproduce

Create a product with volume-tiered pricing in Stripe Dashboard

## Expected behavior

Why does it need this key? 

## System information
n/a

## Additional context

Seems like a simple resolution to add another permission to the rk_test key, just need to add to the reconfiguration instructions

**Comment by DCSnip3r** [comment]
Checked my endpoint and it was disabled. I may have created some kind of failure condition or not updated the extension, causing the endpoint to disable.

**Comment by DCSnip3r** [comment]
I jumped the gun on closing this issue. With my webhook back in action, I'm still getting this same permission error. Does this have anything to do with updating the extension?

**Comment by DCSnip3r** [comment]
I jumped the gun on closing this issue. With my webhook back in action, I'm still getting this same permission error. Does this have anything to do with updating the extension?

**Comment by thorsten-stripe** [comment]
You will need to update your restricted key in the Stripe Dashboard (https://dashboard.stripe.com/apikeys) and allow it to read plan objects as outlined in the docs: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/PREINSTALL.md#additional-setup
