### ISSUE TITLE
Customer details are nulls on first payment

### ISSUE THREAD

**Issue by dancixx** [stripe/stripe-firebase-extensions#179]
At the first payment are the customer details nulls. When I start the checkout session, I didn't get the customer_address, name, etc. in the response because all of them are nulls. I think this is caused by the that the billing information copy method executes after the first payment. After the customer.updated event didn't trigger the invoice.updated or finalized events again when I look at it in the events log.

**Comment by thorsten-stripe** [comment]
Correct, that information is only synced upon checkout session completion: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/functions/src/index.ts#L433-L439

**Comment by thorsten-stripe** [comment]
I'm afraid that's not possible, because these details are only collected after you have redirected to Stripe Checkout.
