### ISSUE TITLE
StripeRole remove 'role' from custom claims

### ISSUE THREAD

**Issue by Arystosedes** [stripe/stripe-firebase-extensions#18]
Bug report
firestore-stripe-subscriptions

To Reproduce
1. Create user in firestore app and set custom user claims like: admin.auth().setCustomUserClaims(user.uid, { role: 'admin' });
2. Use stripe to make a subscription for a product with firebaseRole metadata
3. If success => sign out and sign in again
4. Check user.getIdTokenResult() - 'role' will be removed
5. If you set 'role' again, it will remove stripeRole from custom claims

Expected behavior
'StripeRole' shouldn't replace/delete other custom claims.

 As can I see (https://firebase.google.com/docs/auth/admin/custom-claims#set_and_validate_custom_user_claims_via_the_admin_sdk) this is expected behavior. 

It means this extension is unusable if you need to use other custom claims (you need to choose between custom claims created by firebase or stripe). I need both (stripeRole to match the subscribed plan with appropriate document in firebase collection where I defined specific limits for that plan).

**Comment by jhuleatt** [comment]
I believe the extension could fix this by modifying the current code:

```ts
await admin.auth().setCustomUserClaims(uid, { stripeRole: role });
```

To first check existing custom claims and merge them:

```ts
const { existingCustomClaims } = await admin.auth().getUser(uid);
await admin.auth().setCustomUserClaims(uid, { ...existingCustomClaims, stripeRole: role });
```

**Comment by Arystosedes** [comment]
@jhuleatt Not sure if I'm understanding correctly. The extension could fix this (extension bug), or I need to fix my code? If my code.. I need stripeRole (in my case) only to know which product user paid for (to set app limits then). Besides of that, I need to use setCustomUserClaims when user sign in to my app (with firebase functions functions.auth.user().onCreate()..) to set user role like admin/moderator/editor etc).

Not sure, what should I do with your proposals, but of course thx for trying to help :)

**Comment by thorsten-stripe** [comment]
Thanks for reporting @Arystosedes, this is definitely a bug in the extension and not expected behaviour. I'll fix it.

**Comment by ajgagnon** [comment]
Thanks for the fast action on this! Just checked out the pull request and it looks good to me too. Anything I can do to help test/get this pushed? Sort of at a roadblock with this since we need our custom claims intact.

**Comment by thorsten-stripe** [comment]
@ajgagnon we're currently on a weekly release schedule, aiming to release Thursday AM PT time. However you can update the extension from local source, to do so:

1. Clone this repository to your local machine
1. Run `npm install`
1. Switch to `firestore-stripe-subscriptions/fix/merge-customClaims` branch
1. Run `npm run ext:update --ext=firestore-stripe-subscriptions --project=<YOUR FIREBASE PROJECT>`
1. Follow the steps in the terminal

This will update your extension with the local code.

**Comment by rosariopfernandes** [comment]
@thorsten-stripe I'm afraid that won't work, since that feature is currently in alpha.

**Comment by ajgagnon** [comment]
You mean this is in beta?

```
npm run ext:update --ext=firestore-stripe-subscriptions --project=<YOUR FIREBASE PROJECT>
```

I'm assuming there's no workaround at the moment, until possibly Thursday when this is updated, correct?

**Comment by rosariopfernandes** [comment]
@ajgagnon Unfortunately yes, that's the only possible way.

**Comment by ajgagnon** [comment]
Okay thanks!

**Comment by thorsten-stripe** [comment]
Very sorry for that! I'll work with the team to get this into the Thursday release. Sorry again for getting your hopes up 🙈

**Comment by ajgagnon** [comment]
All good! I appreciate the responsiveness! 

Looking forward to the Alpha feature as well! :)
