### ISSUE TITLE
option to avoid multiple subscriptions 

### ISSUE THREAD

**Issue by conde2** [stripe/stripe-firebase-extensions#183]
# Feature request

firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.

My use case is that I'm offering subscriptions plans to users, but they can subscribe multiple times to different subscriptions, I would like to avoid this situation by adding a parameter that will not allow purchase multiple subscriptions

## Describe the solution you'd like

I would prefer one option when setting up the extension where you define if you would allow multiple subscriptions or not.

## Describe alternatives you've considered

Other option would be add it to the checkout_sessions one parameter that would fail in case there is already one subscription

```
    .doc(userId)
    .collection('checkout_sessions')
    .add({
      price: priceUid,
      success_url: window.location.origin,
      cancel_url: window.location.origin,
      multiple: false
    }));
```

**Comment by thorsten-stripe** [comment]
This is something that would live in your app logic. You basically check if the user has an active subscription and if they do, you would not present them with the option to create another subscription. 

You can see this implemented in the demo: https://github.com/stripe-samples/firebase-subscription-payments/blob/master/public/javascript/app.js#L128-L152
