### ISSUE TITLE
Local development including extensions using emulator suite

### ISSUE THREAD

**Issue by Spitzbua** [stripe/stripe-firebase-extensions#189]
# Bug report

- Extension name: firestore-stripe-subscriptions

## Describe the bug

For the development of new features we use the emulator suite to ensure that there is no impact on the production environment. As far as I know the function emulator does not support Firebase extension. It only emulates functions that are included in the local functions\index.js. 
Now we would like to add the new supported one-time-payments to the application. 

In the package.json there are commands to start the Firebase emulator but I am not sure how this should work:

https://github.com/stripe/stripe-firebase-extensions/blob/next/package.json

However, when executing the command "cd firestore-stripe-subscriptions/ && firebase ext:dev:emulators:start --test-params=../.env --project=stripe-subs-ext", several errors occur:
- error: unknown option '--test-params'
 -error: ext:dev:emulators:start is not a Firebase command

We need a way to develop and test the purchase flow locally in combination with the Stripe test environment (api keys, endpoints, webhooks).

Can you show me a way to achieve this? Is there a best practice here?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Checkout https://github.com/stripe/stripe-firebase-extensions
2. Execute npm run dev:subs in project

## Expected behavior

The emulator will be started and the functions will be initialized within the function emulator.

## System information

- OS: Windows 10
- Browser Chrome

**Comment by jhuleatt** [comment]
@Spitzbua those commands are currently only documented and supported for developers in the [extension publishers’ early access program](https://firebase.google.com/docs/extensions/overview-use-extensions#early_access_partner_extensions). However, you can probably figure out how to unlock them by poking around in the [firebase/extensions repo](https://github.com/firebase/extensions/blob/cde67fc0f903422e253d3275f966a6bd0863d456/.github/workflows/test.yml#L31) 👀 

I'd recommend:

1. Filing your feature request on the [firebase-tools repo](https://github.com/firebase/firebase-tools), which is where emulator commands are implemented, and
2. Joining the early access program to learn more about emulators + extensions
