### ISSUE TITLE
FR: Make subs and OTP's selectable

### ISSUE THREAD

**Issue by cvoadmin** [stripe/stripe-firebase-extensions#190]
# Feature request

- Extension name: firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.

`An error occured: You specified payment mode but passed a recurring price. Either switch to subscription mode or use only one-time prices.`

## Describe the solution you'd like

I'd like both subscriptions and one-time-prices to be selectable if there's no javascript workaround.

**Comment by thorsten-stripe** [comment]
https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#adding-multiple-prices-including-one-time-setup-fees

**Comment by cvoadmin** [comment]
Is this the right solution if you have 2 subscriptions and 4 OTP's?
`An error occured: You must provide at least one recurring price in `subscription` mode when using prices.`

**Comment by thorsten-stripe** [comment]
- If you're using only recurring prices, mode needs to be `subscription` (that's the default)
- If you're using recurring + one time prices, mode needs to be `subscription` (that's the default) 
- If you're using only one-time prices, mode needs to be `payment` docs: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#collecting-one-time-payments-without-a-subscription example: https://github.com/stripe-samples/firebase-subscription-payments/blob/master/public/javascript/app.js#L187-L189
