### ISSUE TITLE
Tax rates saved to wrong location

### ISSUE THREAD

**Issue by chetbox** [stripe/stripe-firebase-extensions#191]
# Bug report

- Extension name`firestore-stripe-subscriptions`

## Describe the bug

Tax rates seem to be stored in the wrong place in Firestore.

The documentation says to add the following Firestore rules, which suggest that a `tax_rates` subcollection is added to each product:

```
    match /stripe_products/{id} {
      allow read: if true;

      match /prices/{id} {
        allow read: if true;
      }
      
      match /tax_rates/{id} {
        allow read: if true;
      }
    }
```

None of our products have a `tax_rates` subcollection; Instead we have a product with an ID of `tax_rates` that has a `tax_rates` subcollection.

## To Reproduce

1. Add subscription products on Stripe dashboard
2. Add a tax rate on Stripe dashboard

## Expected behavior

- There is no `tax_rate` product.
- `stripe_products/{id}` have a `tax_rate` subcollection

## Screenshots

![Screenshot from 2021-06-03 12-17-43](https://user-images.githubusercontent.com/292958/120638275-d5a57c80-c467-11eb-869a-4607073614bb.png)

Is looks to me like this document should not be here.

![Screenshot from 2021-06-03 12-42-26](https://user-images.githubusercontent.com/292958/120639399-341f2a80-c469-11eb-97ec-d3f6d8f8b322.png)

There are no `tax_rates` subcollections on products.

## System information

- Extension version 0.1.12
- Stripe test mode
- Webhook has all permissions in documentation, including `tax_rates.create` and `tax_rates.delete`.

## Additional context

I see that Stripe has the ability to add `default_rax_rates` to a subscription but I can't find a way to set that on the Stripe dashboard. If I set `default_tax_rates` on a subscription product will the relevant tax rates be applied automatically in the customer portal? Will it also create the `/stripe_products/{id}/tax_rates` subcollection with all relevant tax rates?

I think this issue may describe more than one related-but-not-the-same problems but I'm a little confused how to configure and use tax rates with this extension.

**Comment by thorsten-stripe** [comment]
The tax rate subcollection is added to a single product with id `tax_rate` which has the sole purpose to hold that subcollection. E.g. /products/tax_rates/tax_rates/txr_1HCjzTHYgolSBA35m0e1tJN5. This is how you query them:

```js
const taxRates = await db
  .collection("products")
  .doc("tax_rates")
  .collection("tax_rates")
  .get();

```

So the route in the rules is correct. Hope that makes sense. 

The `tax_rates` that you pass to the checkout session doc creation are set as the `default_tax_rates` for the subscription. That way they are applied also when changes occur in the customer portal. See this related thread: https://github.com/stripe/stripe-firebase-extensions/issues/154#issuecomment-828936078
