### ISSUE TITLE
Custom claim stripeRole is not set on the user

### ISSUE THREAD

**Issue by MitchelSt** [stripe/stripe-firebase-extensions#193]
# Bug report

- Extension name: stripe-firebase-extensions

## To Reproduce

1. Add a new product firebaseRole with value 'premium'
2. Check if product with metadata field is added to firestore
3. Make a payment for this specific product (using the price_hash in a test environment)
4. Check if payment was made successfully
5. Run the following snippet in React

`async function getCustomClaimRole() {
  await firebase.auth().currentUser.getIdToken(true);
  const decodedToken = await firebase.auth().currentUser.getIdTokenResult();
  console.log(decodedToken.claims.stripeRole);
}`

6. Console logs undefined (just logging claims, obviously, also doesn't show it)
7. Logout, clear application data, sign in again => same as 6

## Expected behavior

user.claims.stripeRole should contain a value

## System information

- OS: Windows
- Browser: Chrome

**Comment by thorsten-stripe** [comment]
Do you have your webhook handler configured correctly? If so you should see this in the logs for the `ext-firestore-stripe-subscriptions-handleWebhookEvents` function:

```
🚦 Added custom claim [stripeRole: premium] for user [ly9Vm...].
```

Can you double check your webhook configuration and the function logs please?

**Comment by MitchelSt** [comment]
I just re-configured everything from scratch, checked the logs; but without success.

Could this perhaps be the case since I'm using it since one-time payments are not supported?

**Comment by thorsten-stripe** [comment]
@MitchelSt custom claims are not supported for one-time products, only for recurring products

**Comment by RORO-ML** [comment]
> Do you have your webhook handler configured correctly? If so you should see this in the logs for the `ext-firestore-stripe-subscriptions-handleWebhookEvents` function:
> 
> ```
> 🚦 Added custom claim [stripeRole: premium] for user [ly9Vm...].
> ```
> 
> Can you double check your webhook configuration and the function logs please?

I have the same problem, claims are not setting at all for me. Checked the webhook 2 times & nothing in the logs related to custom claims.

**Comment by andrewsrichardson** [comment]
did anyone find a clean way of doing this?

lifetime plans of premium subscriptions seems like it would be a common use-case

**Comment by sabindev** [comment]
@thorsten-stripe im also experiencing the same issue

**Comment by udit99** [comment]
@thorsten-stripe me too!
