### ISSUE TITLE
Source link from Firebase Ext page links to `master` not `next`

### ISSUE THREAD

**Issue by jthegedus** [stripe/stripe-firebase-extensions#194]
# Bug report

- Extension name: all

## Describe the bug

The links to the source code from the Firebase Extensions explore page link to `master`. Is this correct given `next` is the default branch?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://firebase.google.com/products/extensions/firestore-stripe-invoices
2. Click on `Source code` link on right-hand side
3. Get taken to GitHub but on `master` branch which shows being behind `next` by X commits.

## Expected behavior

Be taken to the `default` branch, or the branch of the latest release tag.

## Impact

Lowest possible.

**Comment by thorsten-stripe** [comment]
Yes, `master` is the code that is deployed when installing the extension.
