### ISSUE TITLE
Best way to importing existing stripe customers & products to firebase?

### ISSUE THREAD

**Issue by DCSnip3r** [stripe/stripe-firebase-extensions#199]
# Question

Is there a suggested method of importing an existing set of stripe customers to an empty firestore?
What about importing products and prices?

Wondering how much will be taken care of via webhook updates if I change to the live keys where my customers are.

**Comment by thorsten-stripe** [comment]
You would have to write a script that adds (or you manually add) the necessary mapping in the `customers` collection:

- Path: `/customers/{uid}`
- Data: 
```js
{ stripeId: 'cus_xxx' }
```

As long as this information is present, the extension will be able to perform all actions for authenticated users with the correct Stripe customer ID.
