### ISSUE TITLE
[Question] Programmatically Customize Customer Portal

### ISSUE THREAD

**Issue by varand-pez** [stripe/stripe-firebase-extensions#200]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

So I read [this suggestion already](https://github.com/stripe/stripe-firebase-extensions/issues/88#issuecomment-720308869), but I'd like to programmatically fix the count while opening the customer portal and not allow customer to modify it.
Think about ordering [n] number of items per month but that number is set in the app based on certain logic.
I want quantity to be set while calling `ext-firestore-stripe-subscriptions-createPortalLink` function.

## Describe the solution you'd like

I'd like to be able to pass quantity in object
```
    functionRef({
      returnUrl: `${window.location.origin}${LINK_SETTINGS}`,
      quantity: n
    });
```

I tried this and few other variation of it but no luck
```
    functionRef({
      features: {
        subscription_update: {
          default_allowed_updates: [quantity],
          enabled: true,
          proration_behavior: "none",
        },
      },
      returnUrl: `${window.location.origin}${LINK_SETTINGS}`,
    });
```

I was wondering if this is doable? or is it better to delete the subscription and create new one with every update? (doesn't sound logical to me)

**Comment by thorsten-stripe** [comment]
This is not possible. If you want to control subscription updates to this extent, you will need to make updates via the API instead of the customer portal: https://stripe.com/docs/billing/subscriptions/change
