### ISSUE TITLE
Handle Duplicate Users

### ISSUE THREAD

**Issue by TMcLoone** [stripe/stripe-firebase-extensions#202]
# Bug report

firestore-stripe-subscriptions

## Describe the bug

Webhooks fails with error 'user not found'. If the user it is trying to find is anything other than 1. For some reason, we have a duplicated user with duplicate stripeId. 

## Expected behavior

Correctly error report that duplicate user is found. If duplicate user found, perhaps check for checkout sessions in user records to find the correct user. 

## Additional context

https://github.com/stripe/stripe-firebase-extensions/blob/114d09c6f4d3310acd3cc67702991ad02808047d/firestore-stripe-subscriptions/functions/src/index.ts#L325

**Comment by thorsten-stripe** [comment]
I think this is out of scope for the extension. Please remove your duplicate users and make sure only one customer object exists per user.
