### ISSUE TITLE
Add checkout session metadata to one time payments

### ISSUE THREAD

**Issue by WithoutRegret** [stripe/stripe-firebase-extensions#203]
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug

When I pass metadata with a single payment the same way I pass metadata for a subscription, I would expect the metadata to show up for the Stripe payment. I can see the correct metadata passed to the checkout session document, but it doesn't flow through to the payment document.

## Additional context

I've only quickly skimmed through the code, but it looks like the metadata for one time payments might be getting lost here?
https://github.com/stripe/stripe-firebase-extensions/blob/114d09c6f4d3310acd3cc67702991ad02808047d/firestore-stripe-subscriptions/functions/src/index.ts#L154-L160

**Comment by WithoutRegret** [comment]
Looking into the Stripe documentation:
https://support.stripe.com/questions/using-metadata-with-checkout-sessions

Maybe the above snippet should be something like this:
```
 if (mode === 'subscription') { 
   sessionCreateParams.subscription_data = { 
     trial_from_plan, 
     metadata, 
     default_tax_rates: tax_rates, 
   }; 
 } else {
   sessionCreateParams.payment_intent_data = { 
     metadata, 
   }; 
 }
```

**Comment by japser36** [comment]
This same code change was brought up in #181
