### ISSUE TITLE
Store: price.nickname in firestore

### ISSUE THREAD

**Issue by linjohnjohn** [stripe/stripe-firebase-extensions#21]
# Feature request

firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.

Price data stored in firestore should include the price's description as well. This use case is useful using the description to name different pricing tiers to display to customers. 

## Describe the solution you'd like

Update the insertPriceRecord handler for price.create and price.update to also store price.nickname

## Describe alternatives you've considered

An alternative is to look at price.interval and display "Monthly" or "Annually" to customers depending on what price.interval is

## Additional context

N/A

**Comment by thorsten-stripe** [comment]
This has been added to the next release for Thursday PT.
