### ISSUE TITLE
Handle customer.subscription.updated webhook event type

### ISSUE THREAD

**Issue by KaiSpencer** [stripe/stripe-firebase-extensions#211]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

When a user changes their subscription in the customer portal, currently the users subscription document remains with details of the original subscription. (I display current user basic plan info in my site without having to generate a customer portal link and then redirect etc driven from the firestore document)

## Describe the solution you'd like

When a user changes their subscription in the customer portal, the subscription document should be updated to reflect the new subscription details.

## Describe alternatives you've considered

Custom function myself to handle this webhook event, happy to do this an merge upstream. Not sure if there were any plans for this event type.
Stripe api directly to receive the current subscription information.

**Comment by thorsten-stripe** [comment]
It does: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/functions/src/index.ts#L579

Do you get any logs in your Stripe Dashboard for the `customer.subscription.updated` events? Also check the logs of the Firebase functions, they might give you a hint what's wrong in your configuration.

**Comment by KaiSpencer** [comment]
Ah yes, I found an error with the price app ID which was causing the update to fail. ! :+1:

**Comment by scole954387** [comment]
> It does: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/functions/src/index.ts#L579
> 
> Do you get any logs in your Stripe Dashboard for the `customer.subscription.updated` events? Also check the logs of the Firebase functions, they might give you a hint what's wrong in your configuration.

This link no longer works.  I'm trying to figure out how to determine if the customer paused their subscription and I see the subscription update webhook is processed in the logs however I see no change in firestore that shows it paused.  Any suggestions?
