### ISSUE TITLE
Creating separate charges and transfers

### ISSUE THREAD

**Issue by dancixx** [stripe/stripe-firebase-extensions#224]
# Feature request
- Extension name: firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.
Creating separate charges and transfers

We are building a platform where others can sell their products and would be great if we can create separate charges immediately after the purchase.  

## Describe the solution you'd like

Basic stripe solution for separate charges and transfers.
https://stripe.com/docs/connect/charges-transfers

**Comment by thorsten-stripe** [comment]
Stripe connect is currently out of scope for this extension. Will leave this issue open to track broader interest, though.

**Comment by jsteele-stripe** [comment]
Closing as a duplicate of #184.
