### ISSUE TITLE
Tax ID collection requires updating business name on the customer

### ISSUE THREAD

**Issue by t-kaufmann** [stripe/stripe-firebase-extensions#225]
# Bug report

- Extension name: firestore-stripe-subscriptions

## Describe the bug
I am aware that a similar issue #222 already exists but I was not sure if the approach/reason behind this bug is the same.

Stripe checkout with `tax_id_collection` enabled leads to the following error: _An error occured: Tax ID collection requires updating business name on the customer. To enable tax ID collection for an existing customer, please set `customer_update[name]` to `auto`._

## To Reproduce

My checkout object (I also tried using `tax_id_collection: true` but that resulted with the same error): 

```
...

let checkoutSession: ICheckoutSession = {
      line_items: lineItems,
      success_url: window.location.origin + "/",
      cancel_url: window.location.origin + "/subscription",
      tax_id_collection: {
        enabled: true,
      },
      customer_update: {
        name: "auto",
        address: "auto",
      },
};

...

//adding session to Firestore
this.db.collection("users").doc(userUid).collection("checkout_sessions").add(checkoutSession);

...

//checking out with the retured ID
stripe.redirectToCheckout({ sessionId }); 

```

## Expected behavior

Opening the checkout page.

## System information

- OS: Windows
- Browser (if applies): Chrome

## Additional context

I followed the documentation [here](https://stripe.com/docs/tax/checkout/tax-ids#create-session) and [here](https://github.com/stripe/stripe-firebase-extensions/blob/master/firestore-stripe-subscriptions/CHANGELOG.md )

**Comment by thorsten-stripe** [comment]
Yes, it's the same as https://github.com/stripe/stripe-firebase-extensions/issues/222. Will close this as duplicate.
