### ISSUE TITLE
Issue with creating customer portal

### ISSUE THREAD

**Issue by hesamalavi** [stripe/stripe-firebase-extensions#226]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

I am having some issues with creating a customer portal.
The customer portal link only works if the user is authenticated and has just paid (the session where they go to checkout), and in session.
As soon as the user signs out and signs back in the link to the customer portal does not work anymore, and I get "Unhandled Runtime Error
Error: Missing required param: customer."

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

This is how I am creating a checkout session and creating link to customer portal:
`import firebase from '../src/firebase/config';
import getStripe from './initializeStripe';
import NProgress from 'nprogress';
// import firebase from '@firebase/app';
require('firebase/functions');

export async function createCheckoutSession(uid: string) {
    NProgress.start();
    const firestore = firebase.firestore();

    const checkoutSessionRef = await firestore
        .collection('users')
        .doc(uid)
        .collection('checkout_sessions')
        .add({
            price: process.env.NEXT_PUBLIC_STRIPE_PRODUCT_PRICE,
            success_url: 'https://mantrahub.co/mantras',
            cancel_url: 'https://mantrahub.co/auth',
        });

    checkoutSessionRef.onSnapshot(async snap => {
        const { error, sessionId } = snap.data();
        if (error) {
            // Show an error to your customer and
            // inspect your Cloud Function logs in the Firebase console.
            alert(`An error occured: ${error.message}`);
        }
        if (sessionId) {
            const stripe = await getStripe();
            stripe.redirectToCheckout({ sessionId });
        }
    });
}

const app = firebase.app();
export async function goToBillingPortal() {
    const functionRef = app
        .functions('us-central1')
        .httpsCallable('ext-firestore-stripe-subscriptions-createPortalLink');
    const { data } = await functionRef({
        returnUrl: `${window.location.origin}/profile`,
    });
    window.location.assign(data.url);
}`

This is the page that has the button to go to customer portal:

`import React, { useState } from 'react';
import firebase from 'firebase/app';
import 'firebase/firestore';
import 'firebase/auth';
import { useAuth } from '../contexts/AuthUserContext';
import { goToBillingPortal } from '../../stripe/createCheckoutSession';
console.log(goToBillingPortal);
const Profile = () => {
    const { user, signout } = useAuth();
    const [isBillingLoading, setBillingLoading] = useState(false);
    return (
        <button
            onClick={() => {
                setBillingLoading(true);
                goToBillingPortal();
            }}
        >
            Manage Billing
        </button>
    );
};

Here is the Firestore rules:

`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{uid} {
      allow read, write: if request.auth.uid == uid;

      match /checkout_sessions/{id} {
        allow read, write: if request.auth.uid == uid;
      }
      match /subscriptions/{id} {
        allow read, write: if request.auth.uid == uid;
      }
    }

    match /products/{id} {
      allow read: if true;
      allow write: if false;

      match /prices/{id} {
        allow read: if true;
        allow write: if false;
      }

      match /tax_rates/{id} {
        allow read: if true;
      }
    }
  }
}`
export default Profile;`
## Expected behavior

For users to be able to go to customer portal after their customer checkout session 

## Screenshots
![Screen Shot 2021-07-21 at 2 20 54 pm](https://user-images.githubusercontent.com/10669468/126430528-12d410d1-4f92-43aa-b587-481f3ed2172b.png)
![Screen Shot 2021-07-21 at 6 01 49 pm](https://user-images.githubusercontent.com/10669468/126453521-fb06a67b-05ca-4baa-a36d-0c4d307cdecc.png)

![Screen Shot 2021-07-21 at 2 25 50 pm](https://user-images.githubusercontent.com/10669468/126430750-14121064-a5eb-4062-8d22-159c1ef69a5f.png)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by thorsten-stripe** [comment]
Sorry for the delay here. Do you see any logs in the `createPortalLink` function in your Firebase console?

**Comment by tanosugi** [comment]
Same error occurred for me. following logs were reported in the firebase console. It's very helpful if you fix it.


12:09:21.356 
ext-firestore-stripe-subscriptions-createPortalLink
Function execution started

12:09:21.360 
ext-firestore-stripe-subscriptions-createPortalLink
Function execution took 5 ms, finished with status code: 204

12:09:21.373 
ext-firestore-stripe-subscriptions-createPortalLink
Function execution started

12:09:21.376 
ext-firestore-stripe-subscriptions-createPortalLink
Callable request verification passed

12:09:21.662 
ext-firestore-stripe-subscriptions-createPortalLink
**❗️[Error]: Customer portal link creation failed for user [xwYCKQYhObcd9M3BOaMfcsdNxzA3]: Missing required param: customer.**

12:09:21.663 
ext-firestore-stripe-subscriptions-createPortalLink
Function execution took 291 ms, finished with status code: 500

**Comment by tanosugi** [comment]
I found that reason of this problem is that I set firestore document "customers" when user login.
It was solved I changed my code as follows.
```
  firebaseApp.firestore().collection("customers").doc(authResult.user.uid).set(
    {
      uid: authResult.user.uid,
      email: authResult.user.email,
      name: authResult.user.displayName,
      provider: authResult.user.providerData[0].providerId,
      photoUrl: authResult.user.photoURL,
    },
+    { merge: true }
  );
```
 
I am not sure hesamalavi is at same situation or not.

**Comment by dackers86** [comment]
Thanks for the update @tanosugi.

I'll close this issue as a solution has been found. 

Happy to re-open if another resolution is required or if this can be considered a potential documentation update (for example).
