### ISSUE TITLE
Vague error in webhook events

### ISSUE THREAD

**Issue by TrillyWonka** [stripe/stripe-firebase-extensions#227]
# Bug report

- Extension name: ext-firestore-stripe-subscriptions-handleWebhookEvents

## Describe the bug

I've just started working on a new project and I've connected up Firebase to Stripe to do some testing. I have configured the extension to create a checkout session for a one time payment. I create a checkout session and make a test payment. The payment is successful and the event is sent back to Firebase via webhook. Everything seems to have worked, but I'm left with a response in the Stipe Webhook logs of:

{ "error": "Webhook handler failed. View function logs in Firebase." }

Then when I check the Firebase logs I have the following error: 

❗️[Error]: Webhook handler for Stripe event [{event_id}] of type [checkout.session.completed] failed: Cannot read property 'enabled' of undefined

Based on the docs I speculated it might have been related to Tax ID Collection, which I was not specifying because I don't require it. I tried specifying the Tax ID Collection but this didn't solve the problem either.

## System information

Firebase / React web app, testing in Chrome 

Thanks team,

**Comment by thorsten-stripe** [comment]
Thanks for reporting this, it's indeed a bug, we need to do optional chaining here: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/functions/src/index.ts#L633

That being said, it shouldn't affect the functionality, so should be safe to ignore until we get it fixed.

**Comment by TrillyWonka** [comment]
Thanks Thor, good to know.
