### ISSUE TITLE
sales tax(consumption tax) cannot specified default_tax_rates

### ISSUE THREAD

**Issue by gouteru** [stripe/stripe-firebase-extensions#23]
# Bug report

- Extension name:  firestore-stripe-subscriptions

## Describe the bug

sales tax (consumption tax 10% in Japan) can not be specified with this extention.

## To Reproduce

Just use this extention. Stripe Checkout charges without tax.

## Expected behavior

[Strip API reference](https://stripe.com/docs/payments/checkout/set-up-a-subscription#tax-rates)
default_tax_rates with specific TAX_RATE_ID should be able to specify on either FIrebase Stripe Extention console or within createCheckoutSession function.  Or, it should be able to specify with the client function.

**Comment by thorsten-stripe** [comment]
This will be added to the next release on Thursday PT.

**Comment by gouteru** [comment]
Thanks! I will be update to the upcoming release.
