### ISSUE TITLE
Custom claim not removed when subscription expires

### ISSUE THREAD

**Issue by FezVrasta** [stripe/stripe-firebase-extensions#232]
# Bug report

firestore-stripe-subscriptions

## Describe the bug

When a Stripe subscription expires, the user claims are not updated and they still result subscribed.

## To Reproduce

- Subscribe
- Wait for expiration
- Observe claims are not updated

## Screenshots

![CleanShot 2021-08-13 at 12 43 10@2x](https://user-images.githubusercontent.com/5382443/129345690-e30a80a7-6a45-4e11-835a-ad5f64533236.jpg)
![CleanShot 2021-08-13 at 12 44 35@2x](https://user-images.githubusercontent.com/5382443/129345849-8633332d-0152-46c2-8f1a-b0163b5d9df8.jpg)

**Comment by thorsten-stripe** [comment]
Can you please check the logs on your `customer.subscription.deleted` events: https://dashboard.stripe.com/events?type=customer.subscription.deleted It should look like this:

![image](https://user-images.githubusercontent.com/23213994/129731054-592e57ce-fda3-4b8b-a7de-78a51faef553.png)

**Comment by FezVrasta** [comment]
If I click on your link it goes to the Events tab, not the Webhooks one, and I see delete events.

But if I go in the webhooks tab I don't see any delete events, only create and update, and in the event types I only see:
```
tax_rate.created
tax_rate.updated
customer.updated
customer.deleted
customer.created
checkout.session.completed
price.created
price.deleted
price.updated
product.created
product.deleted
product.updated
```

**Comment by thorsten-stripe** [comment]
It looks like you're missing the necessary subscription events: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#configure-stripe-webhooks

**Comment by FezVrasta** [comment]
Thanks, is there any way to force a synchronization to update the status of all the expired subscriptions?

**Comment by thorsten-stripe** [comment]
I'm afraid once the subscription has been canceled it can't be updated in Stripe so no way to trigger a new event for it.

**Comment by FezVrasta** [comment]
So I have no way to fix this issue for the existing customers?

**Comment by thorsten-stripe** [comment]
Depending on how many subscriptions you have, you might want to sync their status manually or alternatively write a script that syncs them.

**Comment by FezVrasta** [comment]
How can I sync it manually?

**Comment by FezVrasta** [comment]
I ended up using a script like this:


```
const admin = require('firebase-admin');

const serviceAccount = require('./serviceAccountKey.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'xxxxxxxxxxx',
});

// This is the list of active subscriptions, converted to json
const subs = require('./subs.json');

const processed = [];

const map = async (list, callback) => {
  const promises = [];

  list.forEach((item) => {
    promises.push(callback(item));
  });

  await Promise.all(promises);
};

const run = async () => {
  const customers = await admin.firestore().collection('customers').get();

  await map(customers, async (doc) => {
    const customer = doc.data();

    const log = subs.find((sub) => sub['Customer ID'] === customer.stripeId);

    if (log == null || log['Status'] !== 'active') {
      const sub = await admin
        .firestore()
        .collection('customers')
        .doc(doc.id)
        .collection('subscriptions')
        .get();

      await map(sub, async (subDoc) => {
        const subData = subDoc.data();

        if (subData.status === 'active') {
          const user = await admin.auth().getUser(doc.id);

          await admin.auth().setCustomUserClaims(doc.id, {
            ...user.customClaims,
            stripeRole: 'basic',
          });

          await admin
            .firestore()
            .collection('customers')
            .doc(doc.id)
            .collection('subscriptions')
            .doc(subDoc.id)
            .update({
              status: 'canceled',
              canceled_at: admin.firestore.FieldValue.serverTimestamp(),
            });

          processed.push({
            userId: doc.id,
            stripeId: customer.stripeId,
            subscriptionId: subDoc.id,
            active: true,
            customClaims: user.customClaims,
          });
        }
      });
    }
  });

  console.log(JSON.stringify(processed, null, 2));
};

run();

```
