### ISSUE TITLE
firestore-stripe-subscriptions: metadata object is removed from subscription

### ISSUE THREAD

**Issue by alexcastillo** [stripe/stripe-firebase-extensions#233]
Hi, and thank you for the awesome work!

# Bug report

- Extension name: firestore-stripe-subscriptions

## Describe the bug

When a `subscription` document in Firestore is updated by the extension, the metadata object is updated to `null`.

I should note I'm updating the subscription object with metadata directly via custom cloud function, and not adding the metadata object via `checkout_sessions`.

## To Reproduce

1. Complete a subscription cancelation in Stripe

## Expected behavior

The metadata object in the subscription document remains untouched.

**Comment by thorsten-stripe** [comment]
Are you writing metadata directly to Cloud Firestore? If so it will be overwritten as the subscription object in Stripe is the source of truth. 

You can update the subscription object in Stripe instead, or write your metadata to a separate doc in Firestore.

**Comment by alexcastillo** [comment]
Yes, I'm writing metadata directly to Cloud Firestore. Shouldn't the extension do a merge?

**Comment by thorsten-stripe** [comment]
@alexcastillo if the extension did a merge, then the metadata from the subscription object wouldn't be synced correctly. E.g. metadata keys that were remove would simply persist in Cloud Firestore.

**Comment by alexcastillo** [comment]
Makes sense, thank you. How can I update the subscription object in Stripe?
