### ISSUE TITLE
On Firebase user creation about 2% of users do not get stripe ID back in their Document/profile

### ISSUE THREAD

**Issue by kbringsjord** [stripe/stripe-firebase-extensions#238]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

Hello, I am using the stripe firebase extension and it works very well and greatly appreciate all of your efforts. However, about 2% of the time when users signup and a user document is created the extension neglects to put the stripe id into their profile. It does however consistently make stripe profiles for them and put the firebase uid in their stripe meta.

## To Reproduce

Utilize the webhook in extension to automatically tie firebase and stripe user profiles together. 

## Expected behavior

100% of time stripeid into user profile on document creation

## System information

web (mobile/desktop)

**Comment by kbringsjord** [comment]
stripe/firestore-stripe-subscriptions@0.1.13
No i do not see any errors. 
I entered the collection name of users.
Seems to actually be happening more than 2% of time now

**Comment by kbringsjord** [comment]
This issue seems to also no be affecting the subscription's updating.  Would anyone from the stripe team have 15 minutes to do a zoom session?

**Comment by thorsten-stripe** [comment]
Unfortunately we can't do a zoom session, but you can hop on our technical chat for help: https://stripe.com/go/developer-chat

Please also update the Firebase extension to the latest version and check the Stripe webhook logs and Firebase function logs.

**Comment by dackers86** [comment]
hi @kbringsjord 

Are you still experiencing these issues, did upgrading to the latest version provide a solution?

**Comment by Loocos** [comment]
> hi @kbringsjord
> 
> Are you still experiencing these issues, did upgrading to the latest version provide a solution?

Hi @dackers86,

I'm encoutering the issue with the version 0.3.4.
I'm not able to figure out why sometimes it doesn't works

**Comment by Loocos** [comment]
Ok my bad, I miss reading the README 😄

> This project has now being officailly transferred to [Invertase](https://github.com/invertase), who will maintain this extension going forward. Please see https://github.com/stripe/stripe-firebase-extensions/issues/524 for more details. It is now reccomended to uninstall the stripe/firestore-stripe-payments extension and install invertase/firestore-stripe-payments from the Firebase Extension Hub.
> 
> Alternativley, you can also use the following link to convert your current installation to the Invertase version
> 
> https://console.firebase.google.com/project/_/extensions/install?instanceId=STRIPE_EXTENSION_INSTANCE_ID&ref=invertase%2Ffirestore-stripe-payments@0.3.5

Gonna have a try
