### ISSUE TITLE
products listing code not working with firebase 9 

### ISSUE THREAD

**Issue by NavidAhmad-UOM** [stripe/stripe-firebase-extensions#245]
# Bug report
db.collection('${param:PRODUCTS_COLLECTION}')
  .where('active', '==', true)
  .get()
  .then(function (querySnapshot) {
    querySnapshot.forEach(async function (doc) {
      console.log(doc.id, ' => ', doc.data());
      const priceSnap = await doc.ref.collection('prices').get();
      priceSnap.docs.forEach((doc) => {
        console.log(doc.id, ' => ', doc.data());
      });
    });
  });

when i tried to use this code i got erorr that "doc.ref.collection('prices').get();" ref.collection does not exist , then how i can access prices

**Comment by jsteele-stripe** [comment]
@NavidAhmad-UOM Indeed, the API for the Firebase SDK has changed significantly between versions 8 & 9. The key differences are outlined [here](https://firebase.google.com/docs/web/modular-upgrade).

What you want will instead look something like this:

```js
const q = query(collection(db, "products"), where("active", "==", true));

const querySnapshot = await getDocs(q);

querySnapshot.forEach((doc) => {
  console.log(doc.id, " => ", doc.data());
});
```
