### ISSUE TITLE
Stripe Subscription - Before installing this extension... More info needed

### ISSUE THREAD

**Issue by VinLucero** [stripe/stripe-firebase-extensions#25]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

Context: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/README.md

From the main README for Stripe Firebase Extension Subscriptions one needs to first:
"Before installing this extension, set up the following Firebase services in your Firebase project:

Cloud Firestore to store customer & subscription details.
Firebase Authentication to enable different sign-up options for your users."

No details are provided on how to properly pre-configure Firestore or Authentication or how to reconfigure them after I did the initial install. I would expect this information to be available after installation in the Cloud Console > Extensions > "How this extension works" page:

https://console.firebase.google.com/u/1/project/clowte-prototype/extensions/instances/firestore-stripe-subscriptions?tab=config

(There is also no information after installation if it was successful [was Firestore / Auth setup for me? Or what to do next?])

**Comment by thorsten-stripe** [comment]
Thanks for the feedback @VinLucero! I've added clearer instructions to the pre-install docs and also added them to the top of the postinstall docs. These improvements will roll out with the next release on Thursday PT.
