### ISSUE TITLE
User subscriptions not updated after cancels subscription via stripe customer portal

### ISSUE THREAD

**Issue by dwanderton** [stripe/stripe-firebase-extensions#250]
# Bug report

firestore-stripe-subscriptions

## Describe the bug

When a user cancels their subscription using the stripe customer portal, the stripe webhook fires a `customer.updated`  call to firebase function which respond with:
```
{
  "received": true
}
```
However the event object doesn't seem to contain information that indicates the end of the subscription, and the customer object in firestore maintains an active subscription, even after the customer's subscription expires (not necessarily the same time as the cancelation). The custom claims are not updated either.

## To Reproduce

Install extension. 
Have customer pay and sign up, then cancel the subscription.
The subscription stays as active in firestore, custom claims are not updated either.

## Expected behavior

When customer subscriptions end in stripe, the subscription should be updated in firestore. custom claims should be removed/ reset.

## Additional context

Every other webhook seems to work. all `canceled_at` and `ended_at` stay as `null` in firestore customer subscriptions.

**Comment by cjavilla-stripe** [comment]
@dwanderton sorry for the delayed response. I wonder if the webhook endpoint is listening for the customer.subscription.updated event. Can you share the ID for the event that wasn't handled in firebase?

**Comment by hunterperattre** [comment]
customer.subscription.updated, add that to the web hook and youre good to go. the stipe extension will update on canceled subscription
