### ISSUE TITLE
Add support for cart abandonment recovery

### ISSUE THREAD

**Issue by doppio** [stripe/stripe-firebase-extensions#254]
# Feature request
Stripe [supports recovering abandoned carts](https://stripe.com/docs/payments/checkout/abandoned-carts) by passing in a couple of additional arguments when creating a session.

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.
We would like to be able to send promotional emails to users who create a Checkout session then fail to complete payment. Stripe Checkout supports this, but I don't see a way to pass in the required arguments using this Firebase extension.

## Describe the solution you'd like
It would be nice to just add a parameter to our Firebase checkout session documents like "abandonment_recovery: true".

## Describe alternatives you've considered
I wonder if this extension could take any extra fields on the checkout session Firestore document and automatically pass them along as arguments to the Stripe Checkout API. It would be great if the extension didn't have to manually add support for all unsupported parameters, especially if new parameters are added to the Checkout API in the future.

**Comment by heyarviind** [comment]
I don't think the extension would be able to add extra arguments. The user has to make the changes in the connected accounts and after that extension can take benefit from that extra information.

**Comment by jsteele-stripe** [comment]
> It would be great if the extension didn't have to manually add support for all unsupported parameters, especially if new parameters are added to the Checkout API in the future.

@doppio Great suggestion, and something we may considering doing. However there are certain Checkout Session parameters that shouldn't be passed from the client which is why we oped the build the extension this way.
