### ISSUE TITLE
Support multiple line items

### ISSUE THREAD

**Issue by thorsten-stripe** [stripe/stripe-firebase-extensions#27]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

Currently the CheckoutSession creation only allows passing in one price ID, but there will likely be use cases where one wants to provide multiple pricing plans or add a [one-time setup fee](https://stripe.com/docs/payments/checkout/set-up-a-subscription#adding-setup-fee).

## Describe the solution you'd like

To support this, we should allow to optionally pass in the whole [`line_items` array](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-line_items), instead of just a price ID.

**Comment by Sankarrockzz** [comment]
Yes, this is something that is needed and obvious. I offer multiple products subscription and my customers want to make multiple-subscription via one CheckoutSession. 

In simple words, multiple product subscriptions in one CheckoutSession

**Comment by thorsten-stripe** [comment]
This has been added to the next release on Thursday, 2020-08-20.
