### ISSUE TITLE
Add support for trials

### ISSUE THREAD

**Issue by Georg7** [stripe/stripe-firebase-extensions#274]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Describe the solution you'd like
Support for trials. Current documentation suggests: 
```const docRef = await db
  .collection("users")
  .doc(currentUser)
  .collection("checkout_sessions")
  .add({
    price: "price_1GqIC8HYgolSBA35zoTTN2Zl",
    trial_from_plan: false,
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
```
But Stripe doesn't seem to support this implementation any more (for Checkout): 

<img width="387" alt="Screenshot 2021-10-20 at 11 00 37 AM" src="https://user-images.githubusercontent.com/7827962/138021144-ff5146ed-2a69-4bfc-940c-69e98c369176.png">

## Describe alternatives you've considered

Working with coupons, which has negative implications on the conversion rate.

## Additional context
Since the extension currently only supports "pricing plans that bill a predefined amount at a specific interval" it's not clear how to support free trials without coupons.

**Comment by cyrildiagne** [comment]
Facing the same problem. Is there any solution or workaround?

**Comment by noelmansour** [comment]
While it's "no longer recommended", it still works. Set the free trial on the price and then use, `trial_from_plan: true` when creating the checkout session.

**Comment by cjavilla-stripe** [comment]
Need to add support for trial_period_days https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-subscription_data-trial_period_days

**Comment by scole954387** [comment]
I just finished implementing the redirectToCheckout via an online tutorial and it works great with the legacy trial under the product however as this issue identifies it's not working with the firebase extension to be able to use the trial_period_days.  Looking forward to this fix.  Any estimated time?  Thanks

**Comment by jsteele-stripe** [comment]
I'm not sure we'll ever add support for either the [`trial_period_days`](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-subscription_data-trial_period_days) or [`trail_end`](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-subscription_data-trial_end) parameters because of concerns outlined [here](https://github.com/stripe/stripe-firebase-extensions/pull/182#issuecomment-837738725).

Leaving this open as the primary trial support issue.

**Comment by scole954387** [comment]
Is there no way to find a solution to this concern rather than avoid implementing it because of the concern?

**Comment by jsteele-stripe** [comment]
@scole954387 Is there something preventing you from using [`trial_from_plan`](https://site-admin.stripe.com/docs/api/subscriptions/create#create_subscription-trial_from_plan)? This works with the extension assuming you have a default trial period set on your Price object (via Dashboard).

**Comment by scole954387** [comment]
Does it work with Firebase v9?  Do you have any examples of it working that I can review in React/NextJS.  Nothing is preventing me from using it except for my lack of knowledge as I'm still learning.

**Comment by jsteele-stripe** [comment]
@scole954387 It does, sure! I guess something like this would work with v9 of the Firebase SDK:

```js
const createCheckoutSession = async (user, price) => {
  const checkoutSessionRef = await addDoc(
    collection(doc(db, 'users', user.uid), 'checkout_sessions'),
    {
      cancel_url: window.location.origin,
      price,
      success_url: window.location.origin,
      trial_from_plan: true
    }
  )


  onSnapshot(checkoutSessionRef, async (doc) => {
    const { url } = doc.data()


    if (url) {
      window.location.assign(url)
    }
  })
}
```

**Comment by aerotoad** [comment]
@jsteele-stripe I got it to work with the legacy trial days setting on the price page. Nonetheless, I think it's not future proof to rely on this parameter when Stripe itself is warning devs not to use it.
I understand the security concerns that come with putting such an important setting in the client side of things, but there has to be a way to use the recommended stripe setting without it. Maybe using the remote config function from firebase to set the allowed trial periods and then sending that key in the request to be replaced by the function with the correct value in days.
This way we don't rely on the frontend to send the days and authenticated access to the settings is required to get a valid key that represents the trial days on the server.

**Comment by terrencekuo** [comment]
using "coupons" and the "add free trial" works for me, but my checkout page still requires customers to enter "credit info" for payment. is there a way to not require payment if the price is 0 while using this extension?

not sure how to apply the info in:
https://stripe.com/docs/billing/subscriptions/trials

which states:
"When creating a subscription with a trial period, no payment method is required for the customer. An immediate [invoice](https://stripe.com/docs/api/invoices) is still created, but for $0."

doesn't seem to apply when using this extension?

<img width="985" alt="image" src="https://user-images.githubusercontent.com/9170148/162247180-42870083-b94b-42ba-89ba-c577eee09097.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/9170148/162247240-2124c74c-23e4-48aa-b052-1a688e428efd.png">

**Comment by jsteele-stripe** [comment]
@terrencekuo That's not a limitation of this extension, but Checkout itself. It's currently not possible to complete a Checkout Session without collecting payment information, regardless of if an immediate payment is required.

**Comment by mesqueeb** [comment]
@jsteele-stripe how to 
> Set the free trial on the price

I can't find it in the stripe dashboard on my products config page

**Comment by Logaritma26** [comment]
what I understand is currently we have no option but to use legacy trial on subscription from dashboard and use `trial_from_plan: true` while making request, is there any update for a way not to use legacy trial and get the same result ?

**Comment by jsteele-stripe** [comment]
@Logaritma26 This extension will likely never support the `trial_period_days` or `trial_end` parameters available on Checkout because of reasons previously outlined. Recommendation is to use `trial_from_plan` parameter.

**Comment by alex-i0** [comment]
@jsteele-stripe  There's no longer the legacy option for setting a trial in Stripe. So `trial_from_plan` workaround is no longer valid.

**Comment by ozair-dev** [comment]
> @jsteele-stripe There's no longer the legacy option for setting a trial in Stripe. So `trial_from_plan` workaround is no longer valid.

Yeah that's a bummer. I suppose I have to use a custom implementation for trial period in my app.
