### ISSUE TITLE
403 webhook error on wordpress website ? miscongifuration ?

### ISSUE THREAD

**Issue by Prasad-Omprakash** [stripe/stripe-firebase-extensions#278]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by cjavilla-stripe** [comment]
Not enough context to investigate. Closing.
