### ISSUE TITLE
Using a path like stripe/customers while installing breaks installation due to onCustomerDataDeleted regex error

### ISSUE THREAD

**Issue by agcty** [stripe/stripe-firebase-extensions#28]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]
firestore-stripe-subscriptions

## Describe the bug
When you install the extension and provide a path like "stripe/customers" installation will result in an error due to the path not matching the regex in onCustomerDataDeleted. Seems like every other function works

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Click install extension
2. Installation wizard will ask you about config settings
3. Use stripe/products for products path and stripe/customers for customer path

## Expected behavior

Path should be allowed

**Comment by thorsten-stripe** [comment]
I was able to reproduce this on my account:
![image](https://user-images.githubusercontent.com/23213994/89408481-04bd6580-d753-11ea-9c47-8fb1fb87a2d4.png)

```txt
; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-subscriptions/resources/createCheckoutSession: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"event_trigger","description":"Expected value stripe/customers/{uid}/checkout_sessions/{id} to match regular expression [^/]+/[^/]+(/[^/]+/[^/]+)*"}]}],"statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/stripe-subscriptions-firebase/locations/us-central1/functions","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-subscriptions/resources/onCustomerDataDeleted: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"event_trigger","description":"Expected value stripe/customers/{uid} to match regular expression [^/]+/[^/]+(/[^/]+/[^/]+)*"}]}],"statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/stripe-subscriptions-firebase/locations/us-central1/functions","httpMethod":"POST"}}
```

@jhuleatt @laurenzlong any idea what's happening here? Are paths supported in the extension.yaml file? Do I need to specify a `validationRegex` like here: https://github.com/firebase/extensions/blob/master/firestore-translate-text/extension.yaml#L110?

**Comment by laurenzlong** [comment]
Firestore collections need to be an odd number of segments (i.e. `customers` or `stripe/customers/invoices`). I recommend adding the regex `^[^/]+(/[^/]+/[^/]+)*$` to all the Firestore collection path parameters.

**Comment by thorsten-stripe** [comment]
Thanks @laurenzlong, this is because collections can only be either at the root or within a document, correct? So for `stripe/customers/invoices`, `stripe` is the root collection, `customers` is a document, `invoices` is a sub-collection of the `customers` document. Is that correct?

So using `stripe/products` for products path and `stripe/customers` for customer path is impossible, but using `stripe/mysubsapp/products` for products path and `stripe/mysubsapp/customers` for customer path would be possible. Would that be an antipattern though?

I'll add the `validationRegex` 👍

**Comment by laurenzlong** [comment]
Yep, that's right!

**Comment by laurenzlong** [comment]
And having a more nested collection path like stripe/mysubsapp/customers is
not an antipattern.
