### ISSUE TITLE
Integration with Google Analytics "Purchase" event - Need transaction ID

### ISSUE THREAD

**Issue by DCSnip3r** [stripe/stripe-firebase-extensions#284]
# Feature request
I'm looking to integrate Firebase's google analytics events to the checkout workflow. One of the events I'd like to track is "Purchase". https://developers.google.com/tag-platform/gtagjs/reference/events#purchase

My plan is to set the success_url from the checkout session to contain various parameters that I can feed into this event. 

However,  according to the above docs, a unique transaction ID is required for this event. AFAIK, there is no transaction ID available before creating this checkout_session document. Any suggestions for how to resolve this?

- Extension name: [e.g. `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

Google Analytics Integration

## Describe the solution you'd like

I'd like to be able to log transaction events. I already have a "begin_checkout" event which is simple enough to implement in tandem with creating checkout_sessions. The "purchase" event is a little more difficult

## Describe alternatives you've considered

I can set a random TX ID, but there is probably a better solution. 
I have not tried to leave out the tx id completely because the docs say its required, but this would be sufficient as well.

**Comment by jsteele-stripe** [comment]
@DCSnip3r Have you considered using the `{CHECKOUT_SESSION_ID}` template variable with your `success_url` parameter? Details [here](https://stripe.com/docs/payments/checkout/custom-success-page).

`success_url: "http://yoursite.com/order/success?session_id={CHECKOUT_SESSION_ID}"`

This will ensure the unique Checkout Session ID is returned as a URL query parameter (and can be used with GA).
