### ISSUE TITLE
Customer Portal

### ISSUE THREAD

**Issue by tommtt** [stripe/stripe-firebase-extensions#313]
Hi guys, I want to create a button to allow customers to manage their subscription. Can I do that using this repo?

Something like:

import { customerPortal } from "@stripe/firestore-stripe-payments";

Thanks!

**Comment by leonvisscher** [comment]
Hi @tommtt! I just implemented this myself like this:

```
import { initializeApp } from '@firebase/app';
import { getFunctions, httpsCallable } from '@firebase/functions';

const firebaseConfig = {
  ...
};

const cloudFunctionsDeploymentLocation = "europe-west3"; // Replace with your firebase functions location

const firebaseFunctions = getFunctions(
  initializeApp(firebaseConfig),
  cloudFunctionsDeploymentLocation
);

const openStripePortal = async () => {
    const functionRef = httpsCallable(
      firebaseFunctions,
      'ext-firestore-stripe-payments-createPortalLink'
    );

    const { data } = await functionRef({
      returnUrl: window.location.origin,
    });

    if (data.url) {
      window.location.assign(data.url);
    }
}
```

**Comment by BenJackGill** [comment]
I also vote for adding this to the repo!

**Comment by tommtt** [comment]
> I also vote for adding this to the repo!

In the firebase.js in your react app, just add:

`export async function goToBillingPortal() {
  const functionRef = httpsCallable(functions, 'ext-firestore-stripe-payments-createPortalLink');

  const { data } = await functionRef({ returnUrl: window.location.origin });
  window.location.assign(data.url);
}`

Then you can import and use goToBillingPortal whenever you want in the app :)

**Comment by tommtt** [comment]
don't forget:

`import { getFunctions, httpsCallable } from "firebase/functions";
`
and 

`const functions = getFunctions(firebaseApp, "us-central1")`
