### ISSUE TITLE
Update restricted key instructions

### ISSUE THREAD

**Issue by cjavilla-stripe** [stripe/stripe-firebase-extensions#314]
# Feature request

- firestore-stripe-payments

## Is your feature request related to a problem? Please describe.

In the onboarding for restricted key we say:

> What is your Stripe API key? We recommend creating a new restricted key with write access only for the “Customers”, “Checkout Sessions” and “Customer portal” resources. And read-only access for the “Subscriptions” and “Plans” resources.

Since the two extensions have been merged, I think we also need write access to Invoices and read access to Products from the restricted key.

## Describe the solution you'd like

Update docs

**Comment by DCSnip3r** [comment]
Adding to this, we need updates for permissions regarding "setting up a payment for future use" 

Error messages made it clear that must add SetupIntent write permissions, but there is another permission that is needed that is unclear. 

403 Error: POST /v1/ephemeral_keys

invalid_request_error

The provided key 'rk_test_*********************************************************************************************OrqQzX' does not have the required permissions for this endpoint on account 'acct_1Cr5cpGaWq1l1Ho5'. This is a restricted API key, but the required permissions are not available for use by restricted keys.

**Comment by magicmikek** [comment]
Solved the error by using the Secret Key Stripe provided. A restricted key does not work in this case.

**Comment by DCSnip3r** [comment]
@magicmikek Can you elaborate? Still having this problem

**Comment by BenJackGill** [comment]
/Also “Plans” is not in the list of Stripe API resources. Is that supposed to say something else?

**Comment by jsteele-stripe** [comment]
@BenJackGill That would be `Prices`.
<img width="1204" alt="Screenshot 2022-03-22 at 17 51 01" src="https://user-images.githubusercontent.com/83410553/159544076-aa249199-5d8f-4350-8580-6c0cd5318996.png">

**Comment by jon-freed** [comment]
Yes, please update the README.md to say "Prices" instead of "Plans".

In other words, change the existing phrase from `read-only access for the "Subscriptions" and "Plans" resources.` to `read-only access for the "Subscriptions" and "Prices" resources.`

**Comment by BenJackGill** [comment]
I am just now setting up the extension again for another project, and this problem still persists.

The description needs updating asap because first timers will struggle to find a solution.

**Comment by MOOUDE** [comment]
I am facing the same issue, it only worked when I used the secret key

**Comment by bcthakre** [comment]
Still having the same issue. In my case , neither Restricted key nor secret keys working
