### ISSUE TITLE
How to map a firebase deployed cloud function version to the codebase here

### ISSUE THREAD

**Issue by dawogfather** [stripe/stripe-firebase-extensions#323]
# Bug report

- Extension name: [e.g. `firestore-stripe-payments`]

## Describe the bug

I don't see how I can map extension that I already have installed in my firebase console with 
stripe/firestore-stripe-payments@0.1.15

This verison specifically https://github.com/stripe/stripe-firebase-extensions/blob/master/firestore-stripe-payments/CHANGELOG.md#version-0115---2021-08-26

## To Reproduce
Install a version in firebase console and then wait for a new release of this payments product in this repo

## Expected behavior

I expected to be able to come to this repo and see a tag of 0.1.15 which has the exact code that is being executed in my cloud functions environment right now. 
Is this not the case? Is there any reason why you don't tag the repository on an extension "release"? 

## Screenshots

![image](https://user-images.githubusercontent.com/447826/144337631-c641b1a7-61fa-429a-a262-9f30faf11031.png)

## System information
All

## Additional context

Thanks and apologies in advance if I missed something glaringly obvious.

**Comment by dackers86** [comment]
Hi @dawogfather 

Can I confirm the issue that you experiencing....

1. After installing an extension you are provided with a cloud function.
2. You would then like to call `.httpsCallable("ext-firestore-stripe-payments-createPortalLink");` <-- But this is no longer valid?

**Comment by dawogfather** [comment]
Can’t remember if it was a problem with that specifically. Think I may have had an issue with that but… I think it was more that I wanted to understand what version of the cloud functions I was actually running after previously installing it through the firebase console user interface. The version in there didn’t match a released version on GitHub and so had to use date to determine what I was running.
