### ISSUE TITLE
possibility to create "one-time payments" via mobile passing a list of "prices"

### ISSUE THREAD

**Issue by matheuscabralkk** [stripe/stripe-firebase-extensions#328]
# Feature request

- Extension name: firestore-stripe-mobile-prices-payment

## Is your feature request related to a problem? Please describe.

I'm not able to do "One-time payment" via Mobile passing a list of "prices", because the parameters "amount" and "currency" are mandatory in this case (mobile payments).
I Can't do this with this plugin? If not, stay here my feature request

## Describe the solution you'd like

I would like to be able to pass a "price" list via mobile with the "One-time payment" without having to pass the parameter "amount"

## Describe alternatives you've considered

I think there are no other alternatives

## Additional context

I'm building a mobile Ecommerce where the user can buy one or more products

obs: reading the plugin documentation, I don't think it's possible to do this currently, right?

**Comment by cjavilla-stripe** [comment]
Correct. With mobile, we create a PaymentIntent directly instead of a Checkout Session. PatmentIntents don't accept Price objects, but instead a more primitive amount. You'd need to calculate the total price and send that amount.
