### ISSUE TITLE
Subscribe button doesn't redirect to stripe checkout 

### ISSUE THREAD

**Issue by myerzman** [stripe/stripe-firebase-extensions#329]
# Bug report

- Extension name: [e.g. `firestore-stripe-payments`]

## Describe the bug

Clicking on Subscribe doesn't redirect to stripe subscriptions 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

## Additional context

index.js:27 [2021-12-20T17:50:57.285Z]  @firebase/firestore: Firestore (7.14.6): FIRESTORE (7.14.6) INTERNAL ASSERTION FAILED: Unexpected state

**Comment by cjavilla-stripe** [comment]
Can you share more context? We don't have enough info here to debug.
