### ISSUE TITLE
one-time setup fee for a subscription

### ISSUE THREAD

**Issue by pengustudios** [stripe/stripe-firebase-extensions#33]
# Feature request

- Extension name: firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

## Describe the solution you'd like

1) I would love to be able to add a one-time setup fee to the subscription.
2) Setting up a limited time discounted trial period (instead of totally free) would be amazing as well.

Thanks!

**Comment by danilowoz** [comment]
Hopping for this option too :)

**Comment by thorsten-stripe** [comment]
Thanks for voicing your interest for this, this will be made possible via #27. Please follow along there :)

**Comment by thorsten-stripe** [comment]
This has been added to the next release on Thursday, 2020-08-20.
