### ISSUE TITLE
Save the customer's payment method at the time of payment

### ISSUE THREAD

**Issue by nino-cast** [stripe/stripe-firebase-extensions#340]
# Feature request

Run Payments with Stripe

## Is your feature request related to a problem? Please describe.

I want to save the customer's payment method at the time of payment. Currently, customers have to enter their credit card every time.

## Describe the solution you'd like

We should be able to respond if we can change the [relevant option](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-setup_future_usage) when creating the checkout.

https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-payments/functions/src/index.ts#L105-L130

```js
// example
    const {
      client = 'web',
      amount,
      currency,
      mode = 'subscription',
      price,
      success_url,
      cancel_url,
      quantity = 1,
      payment_method_types,
      shipping_rates = [],
      metadata = {},
      automatic_payment_methods = { enabled: true },
      automatic_tax = false,
      tax_rates = [],
      tax_id_collection = false,
      allow_promotion_codes = false,
      trial_from_plan = true,
      line_items,
      billing_address_collection = 'required',
      collect_shipping_address = false,
      customer_update = {},
      locale = 'auto',
      promotion_code,
      client_reference_id,
      payment_intent_data // add
    } = snap.data();
```

---

Or if there is a way to save payment methods in your existing configuration, please let me know. We thank you for your cooperation.

**Comment by DCSnip3r** [comment]
This is already the default behavior. The only thing is it doesn't set the payment method as default during first checkout.

**Comment by jsteele-stripe** [comment]
> This is already the default behavior. The only thing is it doesn't set the payment method as default during first checkout.

This is not true for Checkout Sessions where `mode: 'payment'`, which this extension [supports](https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-payments/CHANGELOG.md#one-time-payments). You need to explicitly pass the `payment_intent_data.setup_future_usage` parameter. Docs [here](https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=checkout#save-payment-method-details).
