### ISSUE TITLE
Svelte-kit Issue

### ISSUE THREAD

**Issue by limzee** [stripe/stripe-firebase-extensions#344]
# Bug report

- Extension name: firestore-stripe-payments

I get the following error trying setup the extension with Svelte-kit:
**It did work with normal svelte.** This is something I stumbled upon trying to migrate the project to Svelte-kit. 

```
@stripe/firestore-stripe-payments doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore] {
  code: 'invalid-argument',
  customData: undefined,
  toString: [Function (anonymous)]
}

Node.js v17.0.0
```

## To Reproduce

Start a new Svelte-kit project and setup firebase and stripe:

```
export const app = initializeApp(firebaseConfig);

export const payments = getStripePayments(app, {
	productsCollection: 'products',
	customersCollection: 'customers'
});
```

  and attempt to fetch the products using the following code:

```
const fetchproducts = async () => {
	const fetchedProducts = await getProducts(payments, {
		includePrices: true,
		activeOnly: true
	});
	console.log('Products fetched!');
	return fetchedProducts;
};
```

## Expected behavior

Expected the code to fetch the products without the application crashing :)

## Disclaimer
Maybe it's not supposed to work with Svelte-kit hehe

## System information

- OS: macOS m1
- Browser Firefox

**Comment by Bandit** [comment]
`firestore-stripe-payments` is an extension for Firebase, and meant to run in Node.js in a Cloud Function... not in Sveltekit

**Comment by dackers86** [comment]
HI @limzee.

Can you explain what the purpose of this installation was? Did you mean to use https://github.com/stripe/stripe-firebase-extensions/tree/next/firestore-stripe-web-sdk?
