### ISSUE TITLE
Add discounts to invoices

### ISSUE THREAD

**Issue by JHethDev** [stripe/stripe-firebase-extensions#345]
# Feature request

- Extension name:  Send Invoices using Stripe

## Is your feature request related to a problem? Please describe.

No. But I need to add discounts/coupons to invoices.

## Describe the solution you'd like

Either the ability to add a coupon in Stripe admin and add it to the order object or the ability to specific parameters of a discount as an object. {discountPercent: 15, oneTimeUse: true...}

## Describe alternatives you've considered

I tried adding an item with a negative amount to the array of items in the invoice but it errors out in Firebase console and doesn't give any real details.

## Additional context

Here's the error I get in logs when trying to use negative invoice item

```
ext-firestore-stripe-invoices-sendInvoice
Error: 😞[Error] Error when creating the invoice:
    at Object.invoiceCreatedError (/workspace/lib/logs.js:48:19)
    at exports.sendInvoice.functions.handler.firestore.document.onCreate (/workspace/lib/index.js:169:18)
    at process._tickCallback (internal/process/next_tick.js:68:7) undefined
```

**Comment by healthybud** [comment]
We're having the same issues! Have you received any update?

**Comment by healthybud** [comment]
Does anyone from Stripe following this issue thread?
