### ISSUE TITLE
User subscription is charged multiple times

### ISSUE THREAD

**Issue by ImHamzaAnwer** [stripe/stripe-firebase-extensions#348]
I am using this extension in my react app and sometimes the subscription is charged multiple times when user subscribes i am not using any custom logic or custom cloud functions just configured this extension by how its mentioned in documentation. I am just checking out the user to stripe page and user completes thair payment on stripe page

here is the screenshot
![EIH3m](https://user-images.githubusercontent.com/16404443/154013871-9528b87d-baf7-488a-8d32-26c3cddc9651.png)

#### The Code I am using to check out user

` await CUSTOMERS_COLLECTION.doc(user?.uid).collection('checkout_sessions').add({
        price,
        cancel_url: window.location.href,
        success_url: ${window.location.origin}/loading,
        allow_promotion_codes:
          price === "priceId" ||
          price === "priceId" ||
          price === "priceId"
            ? true
            : false,`

**Comment by DCSnip3r** [comment]
Please edit your question to include necessary code to reproduce this issue.

**Comment by muhammadzumair** [comment]
I am facing a similar issue, I am using firebase extension for stripe payments, I have implemented all the configs according to docs, everything seems fine and it's working but for a few users it duplicates the payment multiple times, as seen in the screenshot, a user charged multiple times for the same subscription.
<img width="1301" alt="Screenshot 2022-02-16 at 11 30 41 AM" src="https://user-images.githubusercontent.com/16427058/154209251-1fd0a8ef-cd33-4e6a-961d-735f240d5394.png">

**Comment by jsteele-stripe** [comment]
@muhammadzumair That's not a single subscription though. That's clearly multiple subscription objects/documents that have been created for that same customer/user. It is completely normal for a Stripe customer to have multiple, simultaneous subscriptions.

My _guess_ here is that there's no logic in your application to prevent the same user subscribing multiple times. This extension does **not** provide the safegaurds to prevent that from happening. You would need to handle that in your application.
