### ISSUE TITLE
[FAQ] Products and prices not syncing with Cloud Firestore

### ISSUE THREAD

**Issue by VinLucero** [stripe/stripe-firebase-extensions#35]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

FireStore collections not being created / updated upon reconfiguring customers / products in Extension config.

## To Reproduce

When you are in the Firebase Dev Console and click on Extensions > Stripe Extension Manage Button > Extension Configuration

I deleted my previous collections and renamed them as follows in bold:

Products and pricing plans collection
Description: What is the path to the Cloud Firestore collection where the extension should store Stripe pricing plans?

**products**

Customer details and subscriptions collection
Description: What is the path to the Cloud Firestore collection where the extension should store Stripe customer details?

**customers**

## Expected behavior

I would expect the FireStore collections to be created and/or updated upon clicking Save and reconfiguration completes.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by VinLucero** [comment]
Also seeing this while retrying:

failed to startDeploymentManagerWork for instance id: firestore-stripe-subscriptions, parentId: clowte-prototype: error updating deployment for "projects/clowte-prototype/global/deployments/firestore-stripe-subscriptions" with delete policy "ABANDON": DM HTTP 404 error. Body: { "error": { "code": 404, "message": "The object 'projects/clowte-prototype/global/deployments/firebase-ext-firestore-stripe-subscriptions-t1zkfn' is not found.", "errors": [ { "message": "The object 'projects/clowte-prototype/global/deployments/firebase-ext-firestore-stripe-subscriptions-t1zkfn' is not found.", "domain": "global", "reason": "notFound" } ] } }

**Comment by VinLucero** [comment]
I think that above error is just because I clicked cancel or tried reconfiguring too many times too quickly.

**Comment by thorsten-stripe** [comment]
@VinLucero the way product and pricing information is entered into your Firestore is via webhook events that are sent from Stripe. These events are only emitted when you either create a product/price or when you update it (e.g. update the name or description). 

So if you delete the existing product collection and change the collection path in the extension, you will need to retrigger these events. One way to do this is by archiving the product/price and then unarchiving it or alternative updating the name or description.

![image](https://user-images.githubusercontent.com/23213994/89877517-c8768300-dbf2-11ea-876b-8d8652c28272.png)
![image](https://user-images.githubusercontent.com/23213994/89877622-e643e800-dbf2-11ea-973e-51d31933831c.png)

I'm leaving this open in case others run into this and to track that we should add this to an FAQ somewhere.

**Comment by dackers86** [comment]
Closing. Issue appears to have been resolved.

**Comment by dackers86** [comment]
@VinLucero Can you confirm this is no longer an issue?
