### ISSUE TITLE
How to change subscription plan ? 

### ISSUE THREAD

**Issue by SlZeroth** [stripe/stripe-firebase-extensions#351]
Hi, I have a question about change subscription 

I have two stripe product 
Product 1: Basic membership
* Price 1: 10 USD per month
Product 2: Premium membership
* Price 1: 20 USD per month

I want to change Product 1 to Product 2 price.
but I cant find out how can i change subscription to other one 

in the firebase stripe payment document only describe this code for subscription 

```
const docRef = await db
  .collection('users')
  .doc(currentUser.uid)
  .collection('checkout_sessions')
  .add({
    price: 'price_1GqIC8HYgolSBA35zoTTN2Zl',
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
```

**Comment by Bandit** [comment]
AFAIK you need to [use the customer portal](https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-payments/POSTINSTALL.md#redirect-to-the-customer-portal) to let the user manage their subscription etc, otherwise you have to use Stripe.js or the Stripe API to do it, not this extension

**Comment by jsteele-stripe** [comment]
@SlZeroth Indeed, you'd use the [Customer portal](https://stripe.com/docs/invoicing/customer-portal) to allow your customers to upgrade/downgrade and/or cancel their subscriptions. This extension provides a [createPortalLink function](https://github.com/stripe/stripe-firebase-extensions/blob/54ad37e351113cc6abb4c8ad1d86eff6d83f935e/firestore-stripe-payments/functions/src/index.ts#L306) you can invoke to create a portal session.

**Comment by dbjpanda** [comment]
@SlZeroth And how would you invoke it?
