### ISSUE TITLE
Cannot set webhook secret

### ISSUE THREAD

**Issue by qqhann** [stripe/stripe-firebase-extensions#353]
# Bug report

- Extension name: firestore-stripe-payments@0.2.4

## Describe the bug

When I configure the firebase extensions from the web console, I cannot save the secret, nor create one with the button.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

### Cannot create with the button

1. Go to the firebase web console and configure the extension.
2. Click on the 'Reconfigure extension' button
3. Click on the 'Create secret' button for webhook secret. 
<img width="577" alt="スクリーンショット 2022-03-03 19 08 44" src="https://user-images.githubusercontent.com/17402261/156543802-fc0172d9-f663-47e2-aaf0-4ccf2e0fb8b4.png">
<img width="413" alt="スクリーンショット 2022-03-03 19 08 37" src="https://user-images.githubusercontent.com/17402261/156543816-8cca2eae-161b-4157-8110-0a2218ec83af.png">

### Cannot save the secret

1. Go to the firebase web console and configure the extension.
2. Click on the 'Reconfigure extension' button
3. Fill in the webhook secret
4. Click on the 'Save' button 
5. The secret is not saved

<img width="798" alt="スクリーンショット 2022-03-03 19 09 07" src="https://user-images.githubusercontent.com/17402261/156544130-7b428bd3-3e41-464e-9256-68e60714ee1b.png">

## Expected behavior

Be able to save the webhook secret

## System information

- OS: macOS 12.2.1
- Browser (if applies): Chrome 98

## Additional context

FYI, I just upgraded the extension from 0.1.5 to 0.2.4

**Comment by Bandit** [comment]
This works fine for me. Might be some sort of permission issue with your Firebase user not having access to create secrets? Either way I doubt it's an issue with this extension

**Comment by qqhann** [comment]
Hi. It seems like I didn't understand the firebase UI. I had to fill in the form and then click the update button. 

It worked that way so this is solved. 
Maybe a better description on how to use the UI would be helpful tho.

**Comment by dackers86** [comment]
Thanks @qqhann.

This seems like a rare issue, typically there is no ordered when adding a secret. 

I'll close this issue for now but happy to re-open if it becomes reproducible.
