### ISSUE TITLE
Adding a one-off price to a new subscription fails

### ISSUE THREAD

**Issue by Bandit** [stripe/stripe-firebase-extensions#354]
# Bug report

- Extension name: firestore-stripe-payments

## Describe the bug

Beginning a subscription with a one-off price included fails with an `Invalid value type` error

## To Reproduce

Take a look at the following screenshot from Firestore

![image](https://user-images.githubusercontent.com/30508/156660433-cd5102fc-e8a6-411f-b440-1ccbcdd857fa.png)

Simple `checkout_session` doc with 2 prices attached (1x recurring, 1x one-off) as an array of maps. Error returned:

`Invalid value type: {:"0"=>"price_1JeZSJG3jpBeqZbddfKBWEJV", :"1"=>"price_1JwdSwG3jpBeqZbdvPnsCswO"} must be a string`

## Expected behavior

According to the documentation, adding a one-off price to a new subscription is meant to work (e.g. "one time setup fee"):

https://github.com/stripe/stripe-firebase-extensions/blob/2ad018aeb45564fce06540a952253715aba1ef79/firestore-stripe-payments/POSTINSTALL.md?plain=1#L418-L447

**Comment by jsteele-stripe** [comment]
@Bandit The issue here is your `metadata` [parameter](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-metadata). Checkout Session can only be created with `key: String` pairings.
