### ISSUE TITLE
getProducts returns an empty list

### ISSUE THREAD

**Issue by MarcVanDaele90** [stripe/stripe-firebase-extensions#355]
# Bug report

- firestore-stripe-web-sdk
- 
## Describe the bug
The following code snippet returns an empty list of products
```
  var userCredential = await signInWithEmailAndPassword(auth, <email>, <pwd>)
  const payments = getStripePayments(firebaseApp, {
  productsCollection: "products",
  customersCollection: "customers",
  });
  const products = await getProducts(payments, {
  });
  console.log('#Products ' + products.length);
```
although ` curl https://api.stripe.com/v3/products   -u <my_restricted_key>:      -G` works fine.
Also the following works fine
```
const session = await createCheckoutSession(payments, {
    price: <some_hardcoded_priceId>,
  });
window.location.assign(session.url);
```

Any suggestions on where to start?  
I do see a customer for my email address (with stripeId and stripeLink) in firebase.
Using the secret key, instead of the restricted key in the firebase strip extension configuration does not seem to make a difference.

## Expected behavior

a non empty list of products is expected

## System information
- Linux/Chrome using webpack

**Comment by MarcVanDaele90** [comment]
Issue can be closed.  
I did not configure the webhook (since it was marked optional I guess)

**Comment by dackers86** [comment]
Thanks @MarcVanDaele90.

Extension instructions are based here https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-payments/POSTINSTALL.md.

I'll close for now but happy to re-open if any warning or documentation could improve this process.
