### ISSUE TITLE
Add subscription payments to your web app with Firebase Extensions & Stripe guide code error

### ISSUE THREAD

**Issue by Where44444** [stripe/stripe-firebase-extensions#358]
# Bug report

- Extension name: [e.g. `firestore-stripe-payments`]

## Describe the bug
Thank you so much for the amazing guide! It got me 99% running, I just found an error in the code for part 5 under "Access the Stripe customer portal" when I used ".httpsCallable("ext-firestore-stripe-subscriptions-createPortalLink");" it gave me a "redirect is not allowed for a preflight request" error. I looked up the name of the function in firestore and I could only find ".httpsCallable("ext-firestore-stripe-payments-createPortalLink");" and upon using that in my code it worked perfectly.

## To Reproduce
Follow guide exactly as it says

## Expected behavior
Pressing the button would take the customer to their portal

## System information

- OS: Windows 10
- Browser: Chrome

**Comment by dackers86** [comment]
Hi @Where44444.

This could be a potential bug in the Firebase Extensions installer, however I am so far unable to replicate.

Could you please provide a screenshot for better debugging of the issue?

Thanks!
