### ISSUE TITLE
Firestore Customers table not updating using  firebase.auth().createUserWithEmailAndPassword(email, password)

### ISSUE THREAD

**Issue by VinLucero** [stripe/stripe-firebase-extensions#36]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`] Version 0.1.4

## Describe the bug

Documentation under https://console.firebase.google.com/u/1/project/clowte-prototype/extensions/instances/firestore-stripe-subscriptions?tab=config

Sign-up users with Firebase Authentication
The quickest way to sign-up new users is by using the FirebaseUI library. Follow the steps outlined in the official docs. The extension listens to new users signing up and then automatically creates a Stripe customer object and a customer record in your Cloud Firestore.

Unfortunately, the extension *is not* properly listening for new user sign ups and the firestore Customers table not updating when using  firebase.auth().createUserWithEmailAndPassword(email, password)

I know the sign up process is working though, because the Firebase Console > Authentication table shows them signed up.

Is there a manual config / process to ensure Firebase Auth matches up with the Customers table for the Stripe extension integration? 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by thorsten-stripe** [comment]
@VinLucero I am not able to reproduce this on my end, just tested with `firebase.auth().createUserWithEmailAndPassword(email, password)` and it triggers the `crateCustomer` function is triggered as expected, creating the Stripe customer object and adding it to the Cloud Firestore.

Have you checked the functions logs for the `createCustomer` function? This might give you an indicator for what isn't configured correctly.

**Comment by VinLucero** [comment]
Weird. Confirmed this is now WAI. Sorry for the false bug.

**Comment by thorsten-stripe** [comment]
No worries @VinLucero, glad to hear it's working now :)
