### ISSUE TITLE
Failing to register a ServiceWorker when using `createPortalLink`

### ISSUE THREAD

**Issue by reblim** [stripe/stripe-firebase-extensions#362]
# Bug report

- Extension name: [e.g. `firestore-stripe-payments`]
firestore-stripe-payments

## Describe the bug
When executing this function:
`const functionRef = firebase
  .app()
  .functions('europe-west1')
  .httpsCallable('ext-firestore-stripe-subscriptions-createPortalLink');
const { data } = await functionRef({
  returnUrl: window.location.origin,
  locale: "auto", // Optional, defaults to "auto"
  configuration: "bpc_1JSEAKHYgolSBA358VNoc2Hs", // Optional ID of a portal configuration: https://stripe.com/docs/api/customer_portal/configuration
});
window.location.assign(data.url);`

the following error ocours:
`The script has an unsupported MIME type ('text/html').
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler (Promise/async): "FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost:8080/firebase-cloud-messaging-push-scope') with script ('http://localhost:8080/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). (messaging/failed-service-worker-registration)."`

This used to work good until today.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by jsteele-stripe** [comment]
Can you share the function output from your Firebase logs? This error doesn't seem related to this extension specifically.

**Comment by reblim** [comment]
Hi @jsteele-stripe, 

If I log out the output of the function I get this:
`Promise {<pending>}
[[Prototype]]: Promise
[[PromiseState]]: "rejected"
[[PromiseResult]]: FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost:8080/firebase-cloud-messaging-push-scope') with script ('http://localhost:8080/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). (messaging/failed-service-worker-registration). at WindowController.eval (webpack-internal:///./node_modules/@firebase/messaging/dist/index.esm.js:1449:45) at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:124:23) at Object.eval [as throw] (webpack-internal:///./node_modules/tslib/tslib.es6.js:105:53) at rejected (webpack-internal:///./node_modules/tslib/tslib.es6.js:96:65)
browserErrorMessage: "Failed to register a ServiceWorker for scope ('http://localhost:8080/firebase-cloud-messaging-push-scope') with script ('http://localhost:8080/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html')."
code: "messaging/failed-service-worker-registration"
name: "FirebaseError"
message: "Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost:8080/firebase-cloud-messaging-push-scope') with script ('http://localhost:8080/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). (messaging/failed-service-worker-registration)."
stack: "FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost:8080/firebase-cloud-messaging-push-scope') with script ('http://localhost:8080/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). (messaging/failed-service-worker-registration).\n    at WindowController.eval (webpack-internal:///./node_modules/@firebase/messaging/dist/index.esm.js:1449:45)\n    at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:124:23)\n    at Object.eval [as throw] (webpack-internal:///./node_modules/tslib/tslib.es6.js:105:53)\n    at rejected (webpack-internal:///./node_modules/tslib/tslib.es6.js:96:65)"
[[Prototype]]: Error
constructor: ƒ FirebaseError(code, message)
length: 2
name: "FirebaseError"
prototype: Error {constructor: ƒ}
arguments: [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.s (<anonymous>:1:83)]
caller: [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.s (<anonymous>:1:83)]
[[FunctionLocation]]: index.cjs.js?cd51:677
[[Prototype]]: ƒ Error()
[[Scopes]]: Scopes[4]
[[Prototype]]: Object`

**Comment by reblim** [comment]
`The script has an unsupported MIME type ('text/html').`

**Comment by jsteele-stripe** [comment]
I don't think this is an issue specific to this extension, but more a configuration issue for your local development environment. [This](https://stackoverflow.com/questions/66641382/the-script-has-an-unsupported-mime-type-text-html) seems related.

**Comment by jsteele-stripe** [comment]
@reblim Going to close this out! Please re-open if you have any follow-up questions.
