### ISSUE TITLE
Allow collection of customer phone number

### ISSUE THREAD

**Issue by LeQuadratico** [stripe/stripe-firebase-extensions#365]
# Feature request

- Extension name: firestore-stripe-payments

## Is your feature request related to a problem? Please describe.

I would like to collect the phone number of the customer on the checkout page in order to be able to contact them in case of an emergency. Adding 
`phone_number_collection: {enabled: true},` to the checkout_sessions document as shown in [the docs](https://stripe.com/docs/payments/checkout/phone-numbers) does not work.

## Describe the solution you'd like

Pass the `phone_number_collection` value on to stripe.

## Describe alternatives you've considered

The phone number could be collected before the checkout, but this would add an unnecessary step for the customer (since the billing adress is collected in checkout) and needs an additional auth system.

## Additional context

In issue #26 , @thorsten-stripe wrote 2020 that the phone number is not collected. However, this seems to have changed, since the payment objects have a "phone" value and [the docs](https://stripe.com/docs/payments/checkout/phone-numbers) mention a way to collect the phone number.
![image](https://user-images.githubusercontent.com/45048954/159458888-833b095a-efd4-490f-8019-aa5b230c222a.png)

**Comment by jsteele-stripe** [comment]
@LeQuadratico Are you expecting the phone value to be set on the `billing_details.phone` [field](https://stripe.com/docs/api/charges/object#charge_object-billing_details-phone)? If so, that's not the case. As outlined [here](https://stripe.com/docs/payments/checkout/phone-numbers#after-session), the value is set on both the Checkout Session [object](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-customer_details-phone) and the Customer [object](https://stripe.com/docs/api/customers/object#customer_object-phone).

**Comment by jsteele-stripe** [comment]
@LeQuadratico Oops, yes. We'll need to add support for that parameter! My bad.
