### ISSUE TITLE
Custom user fields saved in firestore are lost after checkout

### ISSUE THREAD

**Issue by calacianu** [stripe/stripe-firebase-extensions#367]
# Bug report

- Extension name: [stripe-firebase-extensions](https://github.com/stripe/stripe-firebase-extensions)

## Describe the bug

After creating a new document in the `users` collection with custom fields, those fields are lost after the checkout.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create a new document in the users collection.
2. create a checkout session
3. complete the checkout session
4. custom data from the created document is deleted

## Expected behavior

Custom data from the created document should be merged with the data from Stripe

**Comment by jsteele-stripe** [comment]
@calacianu Is this still an issue you can replicate?

**Comment by calacianu** [comment]
no, sorry. my bad, I closed the issue
