### ISSUE TITLE
Allow subscription extension to be added to existing database

### ISSUE THREAD

**Issue by leerob** [stripe/stripe-firebase-extensions#37]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

If you already have a Firestore database + Firebase Authentication, it's not possible to adopt this extension without deleting all of your users.

## Describe the solution you'd like

Instead of listening for customers on create, we could do `createOrRetrieve` instead.

## Describe alternatives you've considered

Deleting all my users 😢 

## Additional context

Luckily, I found this in my dev environment so deleting the users wasn't a big deal. I can see how this might bite other people with existing prod databases, though!

**Comment by thorsten-stripe** [comment]
Thanks @leerob I actually forgot that I had added this with version `0.1.2` already: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/functions/src/index.ts#L102-L106

See changelog entry about "just in time customer creation": https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-012

Do you remember which version you tested with?

**Comment by leerob** [comment]
Yep, that must have been it!

![image](https://user-images.githubusercontent.com/9113740/89907354-2fc01300-dbb2-11ea-817a-280b5210b094.png)
