### ISSUE TITLE
`getCurrentUserPayments` throws an error

### ISSUE THREAD

**Issue by aabounegm** [stripe/stripe-firebase-extensions#379]
# Bug report

- Extension name: [`firestore-stripe-web-sdk`](https://github.com/stripe/stripe-firebase-extensions/tree/next/firestore-stripe-web-sdk)

## Describe the bug

Calling the `getCurrentUserPayments` function from `@stripe/firestore-stripe-payments` throws the following error:
```
payment.ts:282 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at Object.fromFirestore (payment.ts:282:68)
    at bh.data (index.esm2017.js:17862:40)
    at bh.data (index.esm2017.js:17918:22)
    at payment.ts:340:26
    at index.esm2017.js:17952:15
    at index.esm2017.js:13422:53
    at Un.inorderTraversal (index.esm2017.js:3873:49)
    at Bn.inorderTraversal (index.esm2017.js:3777:26)
    at Cu.forEach (index.esm2017.js:13422:24)
    at Vh.forEach (index.esm2017.js:17951:29)
```

Looking at the line (`payment.ts:282`) from where it throws, it seems that it tries to read `data.prices`, but there is no property `prices` on the object (as can be seen in the screenshot below from Firestore)

## To Reproduce

Here is a minimal snippet from the part of my code where it throws this error:

```ts
import { getApp } from "@firebase/app";
import { getCurrentUserPayments } from "@stripe/firestore-stripe-payments";

const app: FirebaseApp = getApp();
const payments = getStripePayments(app, {
  productsCollection: "subscription-plans",
  customersCollection: "users",
});

async function getSubscriptionDetails(sub: Subscription) {
  const product = await getProduct(payments, sub.product);
  const price = await getPrice(payments, sub.product, sub.price);
  const payment = await getCurrentUserPayments(payments, { status: 'succeeded' }); // fails here
  return {
    ...sub,
    product,
    price,
    payment,
  };
}
```

## Expected behavior

I expected it to return the user's payment information to extract the payment method from it (since this info is available on Firestore).

## Screenshots

![image](https://user-images.githubusercontent.com/11016151/165506920-b6428145-b83c-46ec-9d4f-984894a0c5d5.png)

## System information

- OS: **Windows 10**
- Browser: **Chrome** (v100)

## Additional context

I use `getCurrentUserSubscriptions` to get a list of the user's subscriptions. Then, I need to also display the payment method the user used for this subscription (last 4 digits of card + expiration). 
I also tried using `getCurrentUserPayment(payments, paymentId)`, but I couldn't figure out a way to get the `paymentId`. The JSDoc hint suggests that the second parameter is called `subscriptionId`, but using `sub.id` didn't work. Even if I hardcode the ID from Firestore, it still throws the same error as above.

My target is to display the payment method associated with a subscription to give the user the option to update it if needed.

**Comment by samuelkarani** [comment]
Same issue here!

**Comment by samuelkarani** [comment]
Apparently deleting  the entire payments collection resolves the issue

**Comment by dackers86** [comment]
Hi @aabounegm.

Apologies for the late response to this.  The example screenshot suggests that no `prices` data has been added to the payment.

Does this happen consistently? Can you confirm what `version` of the Stripe Extension you are using as this information should be included when syncing from Stripe.

**Comment by aabounegm** [comment]
Hello,
I only tried with one test account, but since it was completely new I had no reason to try again since there are no variables to change, and hence I wouldn't expect a different outcome, but I understand that I should have probably tested more.

Firebase shows that I am using version `0.2.4`. It also shows that there is an update available (I'm not sure why it doesn't send a notification about that). I will update and try again.

I'm not quite sure what you mean by the missing pricing information, but I can see the following under the `subscriptions` subcollection, and it is a subscription and not a one-time payment (even shows the "next charge" date and the billing interval)
![image](https://user-images.githubusercontent.com/11016151/169168198-ccb756e2-b480-444e-832c-4241c1851d94.png)

**Comment by dackers86** [comment]
Ok, thanks. Ignore on the price vs subscriptions! I misread the generated `document` for subscriptions when looking for pricing data. That would be great if you can retry.

In the meantime I will try to reproduce the error based on the sample code provided.

**Comment by dackers86** [comment]
Hi @aabounegm.

I am still working on an a test harness, but noticed something in the documentation.

Can you include `includePrices:true` in your own example? Source: https://github.com/stripe/stripe-firebase-extensions/tree/next/firestore-stripe-web-sdk

**Comment by aabounegm** [comment]
I did and it indeed populated the `prices` array in the product, but I don't see how that's relevant to the problem. The whole issue lies in the `getCurrentUserPayments` function.
Additionally, I do not know how to get the ID of the `Payment` associated with a particular subscription in order to use `getCurrentUserPayment`, but that's a separate question

**Comment by samuelkarani** [comment]
I face this issue with clean re-install of the extension, for one time payments, using lineItems created on the fly (not price/products existing in stripe)

```
"@firebase/app": "^0.7.24"
"@stripe/firestore-stripe-payments": "^0.0.6"
"firebase": "^9.8.1"
```

**Comment by dackers86** [comment]
@aabounegm @samuelkarani  It appears that there is a bug in the `firestore-stripe-payments` extension.

When updating the prices from the the `checkout_session`, this update applies to the `payments` and `subscription` sub-collections depending on the session `mode`. 

`mode = payment`

payments collection: updated
subscription collection: not updated

`mode = subscription`

payments collection: not updated
subscription collection: updated

For subscription a fix may be needed to update both collections with `prices` information.

**Comment by aabounegm** [comment]
Hmm, and is there a workaround we can do to mitigate this problem for now or do we have to wait for Stripe to fix the issue?

**Comment by dackers86** [comment]
You could create a custom webhook for a checkout session completed event to populate the prices array as a short term fix. You can view the expected output in the webhook section of your Stripe Dashboard. 

Alternatively, the best solution would be to use the cli to update the extension when we have had the opportunity to post a PR. 

Manually adding the prices into the subscriptions collection could be a temporary solution and to backfill missing data on previous records (although I appreciate that this isn't ideal!)
