### ISSUE TITLE
UX: On smaller screen sizes, applying promo code requires users to select "View Details" first 

### ISSUE THREAD

**Issue by robertreppel** [stripe/stripe-firebase-extensions#38]
# Feature request

Should the field for entering the promo code be on the main redirect checkout screen instead of requiring to select "View Details" in order to see it?

## Is your feature request related to a problem? Please describe.

Users would need to know to select "View Details" in order to apply a promo code:

![view-details-promocode](https://user-images.githubusercontent.com/471404/89716520-77506000-d962-11ea-8579-f1e152a4c901.png)

## Describe the solution you'd like

Add the field to the main screen which has the CC info, etc?

## Describe alternatives you've considered

Pointing out to users that they can find to promo code field under "View Details" if it isn't visible.

**Comment by thorsten-stripe** [comment]
@robertreppel this is something that isn't controlled by the extension but rather by the hosted Checkout page. I'm going to forward your feedback to the team internally 👍
