### ISSUE TITLE
Cant set Webhook Secret

### ISSUE THREAD

**Issue by pmosedale** [stripe/stripe-firebase-extensions#381]
firestore-stripe-payments

I am trying to add in the Webhook secret, but Firebase is not showing any field for doing this - this also applies to the API Key.

I have tried uninstalling and reinstalling again, but makes no difference.

<img width="964" alt="Screen Shot 2022-04-29 at 6 27 35 pm" src="https://user-images.githubusercontent.com/82461738/165928050-170912b0-1718-4baa-92b7-ff069ebc4762.png">

**Comment by SimonMckeon** [comment]
Can confirm the same thing is happening for me. I have a Stripe API key as I created it on initial setup, but I cannot see or edit either the API key or webhook secret when reconfiguring the extension.

When viewing the extension:
![image](https://user-images.githubusercontent.com/9499258/165938483-b735575c-6a5c-48ee-a855-9832009625de.png)

When reconfiguring the extension:
![image](https://user-images.githubusercontent.com/9499258/165938553-2e78e944-c7b0-4bf2-9cfa-5e33cab5099c.png)

**Comment by SimonMckeon** [comment]
@dackers86 I do.

The 'firestore-stripe-payments-STRIPE_API_KEY' secret was created successfully in the initial extension setup, and I can see it as expected in the secret manager. 

I can visit the API's management page of the project and see that the Secret Manager API is enabled.

![image](https://user-images.githubusercontent.com/9499258/165948907-50e44065-cc47-436d-a36a-22ed322ee93c.png)

**Comment by varand-pez** [comment]
This is also happening to me, after updating to latest extension version.
I have 2 `xxx.xxx.xxxx.STRIPE_WEBHOOK_SECRET` keys but both empty in version. but I can see `STRIPE_API_KEY` has green check under `version` tab.

@dackers86  Are you suggesting that we can configure the secret from here? can I get rid of the extra `STRIPE_WEBHOOK_SECRET` we need only one right?

**Comment by seenakhoee** [comment]
Hi Team,
![Screen Shot 2022-04-30 at 7 40 33 AM](https://user-images.githubusercontent.com/16523191/166110078-c9c419ed-e66a-4890-a221-0590fc94d674.png)

I'm also effected.
Please help as I need webhooks for my project.

**Comment by williamoanta** [comment]
I am also in the same situation with a production account! I have already spent 6 hours trying to solve this problem, including:

1. Configure the Extension from the CLI
2. Deleting and recreating keys in Secret Manager with proper permissions.
3. Reinstalling extension.

This is critical and requires a fix or revert ASAP.

**Comment by dackers86** [comment]
HI @williamoanta 

Did your solution to use `` as per https://github.com/stripe/stripe-firebase-extensions/issues/382 work in this scenario?

Aren you able to reconfigure secrets through the cli, I am currently trying to replicate the issues.

First impressions are that there is an issue with the Firebase console, a GET request appears to show a `404` error when attempting to find the `secret` value.

**Comment by williamoanta** [comment]
@dackers86 I can go through the CLI config but it doesn't solve the problem. I still cannot connect, and I do not get any error logs on Stripe or Firebase Functions.

**Comment by williamoanta** [comment]
@dackers86 I have also tried to install previous versions of the extension from CLI, and for versions 0.2.4 to 0.2.0 I encounter the same problem. On version 0.1.9 I am able to see the two inputs for secrets when I am configuring the extension. Also, a difference is that the secrets are not obfuscated with dots (like a password) in 0.1.9.

**Comment by seenakhoee** [comment]
Team the good news is, the Webhook secret can be set from the CLI. I just set it. Workaround for now. :)

**Comment by williamoanta** [comment]
@seenakhoee did you need to provide any other permissions or you just provided the Secret Manager's secret URL?

**Comment by einjunge99** [comment]
> Team the good news is, the Webhook secret can be set from the CLI. I just set it. Workaround for now. :)

Can you provide an example please? I'm also stuck with this and I want to give it a try, but I'm not familiar with it

**Comment by varand-pez** [comment]
Is there a way we can configure the secret via `console.cloud.google.com` under `secret-manager`?

**Comment by dackers86** [comment]
Hi All.

This is a confirmed issue from the Google team for the `Firebase Console` and will be fixed through a scheduled update. 

If you could use the `cli` for now, an update will appear here when the console issues have been resolved.

**Comment by williamoanta** [comment]
@einjunge99 when you install the extension and provide your API Key, you have the button "Create Secrete" in the console, by pressing it it creates a Secret for Stripe API Key. Then you can navigate in GCC on the same project to the Secret Manager, where you can create a second Secret which has the same configuration as the one provided by the extension.

In the end you will have something similar to this:

<img width="1661" alt="image" src="https://user-images.githubusercontent.com/13750935/166152720-72c26688-12eb-4eeb-90e1-c60d2ebe54a4.png">

Then, you use the firebase CLI with this command ```firebase ext:configure firestore-stripe-payments --project=YOUR-PROJECT-NAME``` to reconfigure the extension. When it asks for the two secrets, here you do not pass the values, but the link to the secret which you can get via "Copy Resource ID" as it is shown below:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/13750935/166152786-0693aca5-9fe0-40cc-90b2-eeacbbd806f5.png">

Then, once the extension is updated you can go in the console and you will see your web hook there as filled, but you won't be able to modify it from the console. 

That should be all.

**Comment by dackers86** [comment]
All. 

An update has now been applied to the Firebase Console. Secrets should now be working as expected.
