### ISSUE TITLE
New secret version causes webhooks to fail

### ISSUE THREAD

**Issue by trafnar** [stripe/stripe-firebase-extensions#382]
- Extension name: `firestore-stripe-payments`

I had the extension working correctly, but I needed to update my webhook and api secret keys. I updated them in the google secret manager, which created new "versions", now my webhooks all fail with an error message like:

```
Could not fetch secret "projects/xxxxxx/secrets/firestore-stripe-payments-STRIPE_API_KEY/versions/1" for environment variable "STRIPE_API_KEY". Instance startup will now abort.
```

I assume this is because the version is no longer 1. Is there a way to tell the relevant cloud function that the version of my api key secrets has changed?

**Comment by williamoanta** [comment]
Yes there is. Just reconfigure your extension using the Firebase CLI.

**Comment by dackers86** [comment]
This has been confirmed as a console error, an update is expected soon. 

Please see https://github.com/stripe/stripe-firebase-extensions/issues/381#issuecomment-1114202627 for more details / tracking of these updates.

**Comment by dackers86** [comment]
Closing. Please see https://github.com/stripe/stripe-firebase-extensions/issues/381#issuecomment-1115340041 for further information.
