### ISSUE TITLE
Support metadata on line_items

### ISSUE THREAD

**Issue by sarbogast** [stripe/stripe-firebase-extensions#389]
# Feature request

- Extension name: `firestore-stripe-payments`

## Is your feature request related to a problem? Please describe.

As described in the documentation's section "Setting metadata on the subscription", if I add metadata at the checkout_session level, I can recover this metadata in the subscription, which is very useful. But I get an error if I try to add metadata in line_items elements, even though it would also be very useful when I subscribe to several prices at the same time. For example, I would like to create a checkout session that lets me add subscriptions for different types of users, each type of user having its own product and price. But then in the resulting subscription's items array, I would like to know which type of user each item is for, and metadata at this level would help me do that.

## Describe the solution you'd like

Just like metadata added to the checkout_session itself ends up in the resulting subscription, I would like metadata that's added in a checkout_session's line_items to end up in the resulting subscription's items.

## Describe alternatives you've considered

For now I'm using other information in the price, like unit_label, but it's not very robust

**Comment by jsteele-stripe** [comment]
@sarbogast Can you elaborate on your use case? There's no `metadata` field available on the session [`line_items`](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-line_items).

**Comment by jsteele-stripe** [comment]
This feedback/request is not specific to the extension, but the underlying Checkout product/API. I've relayed this feature request internally.
