### ISSUE TITLE
can not get sessionID

### ISSUE THREAD

**Issue by Tsquared86** [stripe/stripe-firebase-extensions#391]
# Bug report

- Extension name: [e.g. `firestore-stripe-payments`]

## Describe the bug

Whenever I send a customer to checkout it does not capture a session ID for the snapshot creating a checkout session. I also get an error TypeError: undefined is not an object (evaluating 'doc.id')
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1: type in your stripe key homepage.ts
2: login
3: press "donate $4.20"

(https://github.com/smallbatchdevs/sbd-firebase-stripe-extension)

## Expected behavior

The stripe checkout session should pop up.

## Screenshots

<img width="685" alt="Screen Shot 2022-05-17 at 7 42 28 PM" src="https://user-images.githubusercontent.com/77925376/168876748-7c5d5bf7-f59c-47cd-9985-c465355b05f5.png">

<img width="685" alt="Screen Shot 2022-05-17 at 7 43 29 PM" src="https://user-images.githubusercontent.com/77925376/168876898-c83b286d-be0c-43ea-9349-f0b3784f3e12.png">

## System information
mac
safari
- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by dackers86** [comment]
Hi @Tsquared86

There seem to be two issues described above?

The  `checkout_sessions` document has a document with a session_id stored as the `document_id`.

The example above may not have a completed payment yet, I am assuming in the example above that there no successful subscriptions that have yet been added to your users subscription collection?

Let us know if this is still an issue for you.
