### ISSUE TITLE
Run Payments With Stripe; Support Both Live and Test Keys

### ISSUE THREAD

**Issue by ericmorgan1** [stripe/stripe-firebase-extensions#398]
# Feature request
firebase-stripe-payments

## Is your feature request related to a problem? Please describe.

There is not a good way to switch between "live" and "test" modes when using the "Run Payments with Stripe" extension.
Sometimes I want to test on my production Firebase project, but with a Stripe `test` key.

## Describe the solution you'd like

- When configuring the extension, allow us to enter both our `live` and our `test` API keys.
- There should be a way to switch between them, although I am not sure of the best solution based on what the extension is doing behind the scenes.

## Describe alternatives you've considered

My current workaround is to have two Firebase projects and configure the extension with my `live` key on one and my `test` key on the other.

## Additional context
N/A

**Comment by dackers86** [comment]
HI @ericmorgan1 

The extensions work by configuring the keys on installation of the extension, which would be difficult to switch once configured.

Do you have more details for scenario, as my concern here is that you would be mixing `live` and `test` data in the same database/collections/documents.

Quickly switching of config could be useful but more information would help with this request.

**Comment by ericmorgan1** [comment]
Hi @dackers86 

Thanks for the reply.

I agree that polluting the document database could be a concern. I've just started working with Stripe, so I'm not entirely sure what the implications of this might be on a larger scale. I think it's manageable as long as developers understand what's happening.

The primary scenario is for convenience. Reconfiguring an extension is a painful process (it takes around 10 minutes to reinstall each time) and is more prone to risk in the event that any mistakes are made during the re-configuration process.

For larger projects, it may make sense to maintain two Firebase projects (one for prod, one for test) and can just configure them using the Stripe live and test keys. But even in this case, you may want to maintain a few test users in the prod environment in order to make sure things are working properly, but wouldn't want to actually pay for it. (Example: A SaaS product that requires a paid subscription; you'd want to spot-check that the UI, security, backend functions, etc. are all integrating properly)

For smaller projects, it's not worth it to create two Firebase projects and keep them fully synced up. In this case, it's easier to have one live environment and when doing development, you switch over to the Stripe test keys. The only option in this case is to reconfigure the extension, which is annoying. And you still end up mixing `live` and `test` data in this case anyway.

The solution I was thinking was simply to:
- Add a field for the `test key` in the extension configruation
- Add a parameter, `isTestMode`, to the call to `createPortalLink`
  - This is the only callable function (I believe), so this would just be a quick way to pass that info in (but maybe not the most extensible option)

I'm happy to do the dev and testing on this if that approach seems acceptable.

**Comment by dackers86** [comment]
Thanks @ericmorgan1.

Although I understand the need for testing in a production environment, `it is recommended to use two separate instances of the Extension` to store separate keys.

Stripe data ideally should not be mixed between production and testing environments. The Stripe api is designed so that substituting the keys should provide an adequate solution for testing different environment based applications.

Adding an `IsTest` and separate configuration, would be a difficult feature to add as separate installations can handle this and will also provide separate `webhook` secrets for the webhook triggers.

Finally, Firebase Extensions does not currently allow quick reconfiguration, so this Extension will not be able provide that functionality.

**Comment by ericmorgan1** [comment]
Hi @dackers86 

Do you mind clarifying what you mean by "two separate instances of the Extension"? This would have to be done in two separate Firebase projects, right?

In case it wasn't clear, this is what I was thinking for a possible quick workaround:
https://github.com/ericmorgan1/stripe-firebase-extensions/commit/99898910cf8c9f1112457ac4e3307791cbb03385

I agree about the Stripe API being designed nicely for substituting the `live` and `test` keys. It's really convenient how it works. 
However, for Firebase projects specifically (which would be best suited using this extension), in addition to being a big efficiency loss, I feel this is a deviation from the "Stripe way" (i.e. on the Stripe developer console, I can click a toggle button and instantly switch between `live mode` and `test mode`; but for this extension, I've got to run a script and wait several minutes). I think this is an opportunity to save some developer time and also make the extension more consistent with the live/test paradigm.

And although I can understand the recommendation to not mix real and test data, I would be curious how often that principle is actually respected in practice.

Thanks for adding the code to update the extension programmatically. That is helpful!

**Comment by jsteele-stripe** [comment]
The recommended approach here is to roll 2 separate Firebase projects, where each extension is initialised with either the test or live key.

Closing this out as a won't fix.
