### ISSUE TITLE
Support for customers without email addresses

### ISSUE THREAD

**Issue by NickBrecht** [stripe/stripe-firebase-extensions#4]
# Feature request

Add support for webapps not using email authentication. 

## Is your feature request related to a problem? Please describe.

Reliance on email address stops webapps/websites from utilizing firebase's phone authentication feature. The email is (as far as I can tell) not needed for stripe's customer or portal API. Attempting to register a user without an email results in: 

`ext-firestore-stripe-subscriptions-createCustomer
`❗️[Error]: User does not have an email!

This is by design within the function. However, the customer is still created within Stripe. The only real missing piece is retrieving the StripeID and stripeLink fields to store within the customer's individual collection (record? I'm forgetting my noSQL terms here). Doing this manually (copy/pasting IDs) then allows the portal to function normally (the customer would just need to fill in an email address during checkout)

## Describe the solution you'd like

Use the firebaseUID as the matching identifier if possible. Another solution is to use the phone number itself in lieu of an email address. 

I'm not sure if the above is possible. Like I mentioned above, I see specific error handling for this within createCustomer. My attempts of playing around with it haven't yielded much success. This is my only hiccup with the extension so far - otherwise it's perfect.

**Comment by thorsten-stripe** [comment]
Hey @NickBrecht thanks for the kind words, and thanks for flagging this use case! I think I adopted this requirement from the invoices extension where we need the email address to send off the invoice, but you're right, in the context of the subscriptions extension this is not required. 

I'll make this change and aim to get it into the next release on Thursday PT. 👍
