### ISSUE TITLE
Settable the duration of subscription trial at checkout

### ISSUE THREAD

**Issue by nabettu** [stripe/stripe-firebase-extensions#407]
# Feature request

- Extension name: firestore-stripe-payments

## Is your feature request related to a problem? Please describe.

I would like to set the duration of subscription trial at checkout.

## Describe the solution you'd like

I would like to be able to set this up at checkout.

**Comment by jsteele-stripe** [comment]
@nabettu This is not something that this extension is likely to support for reasons previously outlined (#274, #105, #114). You should use the (undocumented) `trial_from_plan` parameter instead.

**Comment by epleaner** [comment]
How exactly does one use the `trial_from_plan` parameter to set a trial? The only documentation is to set it false when one does not want a trial.

**Comment by jsteele-stripe** [comment]
@epleaner Passing the `trial_from_plan` parameter will set the session created Subscription to inherit the trial duration from the Price. You can only set the trial duration on the Price via the Dashboard UI (not the API).

**Comment by YouZag** [comment]
It appears this is now fully depreciated and not available. Is it time to stop using the extension? I use it in a few projects, but this is critical.

**Comment by talalsiddiqui** [comment]
I am facing the exact problem. I am not able to add trial from Dashboard UI in Stripe. and there is no way to add trial days via subscriptions session
