### ISSUE TITLE
[firestore-stripe-subscriptions] Create Stripe customer for pre-existing Firebase users

### ISSUE THREAD

**Issue by ynnoj** [stripe/stripe-firebase-extensions#42]
# Feature request

- `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

I'm using this extension with a pre-existing Firebase project which has ~1,000 users. When using the extension, a Stripe customer is created for these pre-existing Firebase users. However the email address of the Firebase user is not passed to the Stripe customer.

## Describe the solution you'd like

I'd like for the email address of the pre-existing Firebase user to be passed to the created Stripe customer. This will make identifying customers in Stripe a lot easier going forward.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by ynnoj** [comment]
@thorsten-stripe Seems to me like we could have access to the user `email` in the context here:

https://github.com/stripe/stripe-firebase-extensions/blob/ef2d1301b20f00307a7111edbf90bb4ccdd2f5e1/firestore-stripe-subscriptions/functions/lib/index.js#L104-L106

**Comment by thorsten-stripe** [comment]
Thanks for opening this and having a look @ynnoj. I don't think we have the user email in context, but we can retrieve it from the `uid` which we have in context 👍

**Comment by ynnoj** [comment]
> Thanks for opening this and having a look @ynnoj. I don't think we have the user email in context, but we can retrieve it from the `uid` which we have in context 👍

Is it not available on the `customerRecord` lookup from Firebase here?

https://github.com/stripe/stripe-firebase-extensions/blob/ef2d1301b20f00307a7111edbf90bb4ccdd2f5e1/firestore-stripe-subscriptions/functions/lib/index.js#L102

**Comment by thorsten-stripe** [comment]
The customerRecord only has the stripe customer ID and a link to the customer details in the Stripe Dashboard:
![image](https://user-images.githubusercontent.com/23213994/90157367-3b812480-ddc0-11ea-84b0-65eb76a1c360.png)
We don't want for the extension to store any PII.

**Comment by thorsten-stripe** [comment]
This has been added to the next release on Thursday, 2020-08-20.

**Comment by ynnoj** [comment]
@thorsten-stripe Nice, thanks!
