### ISSUE TITLE
adding firestoreRole to products doesn't add userCustomClaims stripeRole

### ISSUE THREAD

**Issue by smpetrey** [stripe/stripe-firebase-extensions#44]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

Not really sure where to report/ask this, so I figured here would be a good place.

If a product has a `firestoreRole` value in Stripe, and there's a customer subscription, that user should have the same value on the user claim key `stripeRole`... right? That's my understanding. If I'm wrong, can someone clear this up for me? If I'm correct in that assumption, something may be up with the extension

## To Reproduce

Here's my setup:
- I have a freshly installed extension, pre-existing products in Stripe: Basic, Pro, Premium.
- each product has a `firestoreRole` value: basic, pro, premium

Retrieving the customClaims on a front-end next.js app with this:

```
export async function getCustomClaimRole() {
  await firebase.auth().currentUser.getIdToken(true);
  const decodedToken = await firebase.auth().currentUser.getIdTokenResult();
  console.log("decodedToken", decodedToken.claims.stripeRole); // output is undefined, stripeRole doesn't exist :( more on that below
  return decodedToken.claims.stripeRole;
}

```

## Expected behavior

`stripeRole` should exist on user custom claims if `firebaseRole` exists on products.
Not really sure _why_ the claim isn't there.

## Screenshots

Here's the entire decodedToken object consoled I mentioned above:

<img width="772" alt="decoded" src="https://user-images.githubusercontent.com/6411509/90321424-6d58cf00-df17-11ea-94e3-bb664a021e33.png">

Here's the metadata `firebaseRole` on a product in stripe:

<img width="797" alt="Screen Shot 2020-08-15 at 4 50 58 PM" src="https://user-images.githubusercontent.com/6411509/90321433-8eb9bb00-df17-11ea-8ed6-e0f009b7e7bc.png">

Happy to provide any further details to help debug this. I've been wracking my brain on this one 😅 hope all of this makes sense

**Comment by smpetrey** [comment]
I have no idea why or how... but i took a beat, and when I came back `getCustomClaimRole` began working as expected and the stripeRole claim appeared 😅

**Comment by thorsten-stripe** [comment]
@smpetrey the metadata key needs to be `firebaseRole` not `firestoreRole`, that might have been the issue. Glad that it's working now :)

**Comment by smpetrey** [comment]
Thanks @thorsten-stripe! I think that may have been the issue 😅
