### ISSUE TITLE
Restricted key not supporting /v1/ephemeral_keys

### ISSUE THREAD

**Issue by Albertbol** [stripe/stripe-firebase-extensions#445]
# Bug report

- Extension name: [e.g. `firestore-stripe-payments`]

## Describe the bug

In the documentation it says:

> We recommend creating a new [restricted key](https://stripe.com/docs/keys#limit-access) with write access only for the “Customers”, “Checkout Sessions” and “Customer portal” resources. And read-only access for the “Subscriptions” and “Plans” resources.

But when I create checkout_session I get the error:
```
Checkout session creation failed for doc [***]: The provided key '***' does not have the required permissions for this endpoint on account '***'.  This is a restricted API key, but the required permissions are not available for use by restricted keys."}
```

In the stripe dashboard I can see:
`403 ERR | POST | /v1/ephemeral_keys` and same error message.

## To Reproduce

Steps above.

## Expected behavior

I want to create a restricted key and not allow everything.

**Comment by jsteele-stripe** [comment]
![image](https://user-images.githubusercontent.com/83410553/199530723-e443e375-c8c3-4839-aea7-0ff689a5535e.png)
You can now create restricted API keys with ephemeral key permissions in your [Dashboard](https://dashboard.stripe.com/apikeys/create), which should alleviate this error!
