### ISSUE TITLE
Error saving rules when following guide

### ISSUE THREAD

**Issue by joshdance** [stripe/stripe-firebase-extensions#447]
# Bug report

- Extension name: [stripe-firebase-extensions](https://github.com/stripe/stripe-firebase-extensions)

## Describe the bug

Following the Cloud Firestore rules as described here: https://github.com/stripe/stripe-firebase-extensions/blob/master/firestore-stripe-payments/POSTINSTALL.md#set-your-cloud-firestore-security-rules - leads to this error when you try to publish the rules. 

**Error saving rules - Line 4: Forward slash '/' found where identifier or binding expected.; Line 4: Missing 'match' keyword before path.; Line 4: Unexpected '$'.; Line 4: Unexpected '$'.; Line 4: mismatched input 'param' expecting {'{', '/', PATH_SEGMENT}; Line 4: Missing 'match' keyword before path.; Line 5: mismatched input 'allow' expecting {'{', '/', PATH_SEGMENT}; Line 18: Unexpected 'match'.**

Either the provided rules syntax need to be updated to work, or this is a user error and a more detailed explanation of how to add your project details into the rules is needed.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Copy the Cloud Firebase Rules from the guide - https://github.com/stripe/stripe-firebase-extensions/blob/master/firestore-stripe-payments/POSTINSTALL.md#set-your-cloud-firestore-security-rules
2. Replace the existing rules in your project - https://console.firebase.google.com/project/PROJECTNAME/firestore/rules
3. Click Publish

## Expected behavior

I would expect the rules provided to work, or to explain what parts to replace with your details if needed.

## Screenshots
![Screen Shot 2022-10-04 at 12 54 25 PM](https://user-images.githubusercontent.com/597887/193902622-57986aec-3c57-437b-b48d-47629c8dcc40.png)

**Comment by joshdance** [comment]
This was clearly user error. As I understand it better now, of course I should replace ${param:CUSTOMERS_COLLECTION} with the collection where my customers are stored.

I would suggest pointing that out in the onboarding doc.

**Comment by nmsdvid** [comment]
Happened with me also, when the extension is installed go to the extensions **How this extension works** page and you can copy and paste the rules with the correct collection names.
