### ISSUE TITLE
Webhooks repeatedly failing

### ISSUE THREAD

**Issue by Samuelote** [stripe/stripe-firebase-extensions#45]
# Bug report

- Extension name: firestore-stripe-subscriptions

## Describe the bug

The webhook associated with this  extension is failing repeatedly when dealing with customer or checkout events. Both price and product creates/updates fire successfully. I can't find any way to review logs on the failing webhooks so I'm not sure how to debug this.
*Fair warning that I'm new to this extension/Stripe in general.

## To Reproduce

This is a private repo so can't share much.

## Expected behavior

I need the webhook to run successfully.

## Screenshots

<img width="1159" alt="Screen Shot 2020-08-16 at 5 58 13 PM" src="https://user-images.githubusercontent.com/27198821/90346016-30f6a300-dfeb-11ea-9122-1effd512d0c2.png">

## System information

- OS: macOS
- Browser (if applies) Chrome

## Additional context

Feel free to get at me with any questions or clarifications.

**Comment by thorsten-stripe** [comment]
@Samuelote can you please review your Cloud Functions logs for error messages: https://console.firebase.google.com/u/0/project/_/functions/logs. They should give you an indicator for what's going wrong. Feel free to also post them here if they aren't clear.

**Comment by Samuelote** [comment]
Ahhh, thank you so much! I forgot to give read access on subscriptions to my restricted key. SO sorry about the trouble. Thanks for pointing me towards the logs!

**Comment by thorsten-stripe** [comment]
No worries, at all glad it was nothing major :) And these will be useful for compiling an FAQ in a bit 👍
