### ISSUE TITLE
The configuration option for region Oregon (us-west1) is missing

### ISSUE THREAD

**Issue by KTOLE18** [stripe/stripe-firebase-extensions#461]
# Bug report

- Extension name: [e.g. `firestore-stripe-payments`]

## Describe the bug

The configuration option for region Oregon (us-west1) is missing.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Attempt install from the Firebase Console
2. Scroll through the list of regions for the config
3. Note that `us-west2`, `us-west3`, `us-west4` are available
4. Cry in frustration because all of your services happen to be in us-west1

Attempt to work around it:
1. Install for the us-central1 region
2. Use the Firebase CLI to export the extension config
3. From the Firebase Console, uninstall the extension
4. Modify the extensions/firestore-stripe-payments.env file in the local project setting LOCATION=us-west1
5. Run firebase deploy --only extensions for the project
6. **See this error:**
Extensions deploy had errors:

- create firestore-stripe-payments
Request had 1 validation errors: `params.LOCATION`: param provided with invalid option `us-west1`, must be one of `us-central1`, `us-east1`, `us-east4`, `us-west2`, `us-west3`, `us-west4`, `europe-central2`, `europe-west1`, `europe-west2`, `europe-west3`, `europe-west6`, `asia-east2`, `asia-northeast1`, `asia-northeast2`, `asia-northeast3`, `asia-south1`, `asia-southeast2`, `northamerica-northeast1`, `southamerica-east1`, `australia-southeast1`.

## Expected behavior

Oregon (us-west1) is an option for installation via the Firebase console and CLI

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by jsteele-stripe** [comment]
We just need to add the option [here](https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-payments/extension.yaml#L123). We'd love to accept a PR that adds support!
