### ISSUE TITLE
Stripe extension not possible to uninstall or install additional instances

### ISSUE THREAD

**Issue by pknuth** [stripe/stripe-firebase-extensions#462]
# Bug report

- firestore-stripe-payments

## Describe the bug

Cannot uninstall stripe extension or configure additional instances. Im pretty sure that i have all of the permissions in IAM that are required, i always get 403 error. After installing additional instances, the setup fails and additional instances are also not possible to uninstall.

0.2.7 version uninstall (primary instance) log:

`; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/createPortalLink: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission 'cloudfunctions.functions.get' denied on resource 'projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-createPortalLink' (or resource may not exist).","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-createPortalLink","httpMethod":"GET"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/onCustomerDataDeleted: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission 'cloudfunctions.functions.get' denied on resource 'projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-onCustomerDataDeleted' (or resource may not exist).","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-onCustomerDataDeleted","httpMethod":"GET"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/createCustomer: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission 'cloudfunctions.functions.get' denied on resource 'projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-createCustomer' (or resource may not exist).","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-createCustomer","httpMethod":"GET"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/onUserDeleted: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission 'cloudfunctions.functions.get' denied on resource 'projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-onUserDeleted' (or resource may not exist).","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-onUserDeleted","httpMethod":"GET"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/handleWebhookEvents: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission 'cloudfunctions.functions.get' denied on resource 'projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-handleWebhookEvents' (or resource may not exist).","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-handleWebhookEvents","httpMethod":"GET"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/createCheckoutSession: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission 'cloudfunctions.functions.get' denied on resource 'projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-createCheckoutSession' (or resource may not exist).","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/project-staging/locations/europe-west1/functions/ext-firestore-stripe-payments-createCheckoutSession","httpMethod":"GET"}}` 

0.3.1v fresh install

`; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments-a07l/resources/mods-api-enable-iam: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [iam.googleapis.com]\nHelp Token: AZWD64rMJklssvo4uTy9ChZpghryHspFpJvvjMDtCMdveemRyyY-YPhtel8sG35R5xcd090xcdyLgCuLjJjDRsrLK0vNOBB2zmMr2-2PXNO7Wvwn","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=project-staging"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"project-staging"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/project-staging/services/iam.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments-a07l/resources/mods-api-enable-cloudbuild: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [cloudbuild.googleapis.com]\nHelp Token: AZWD64rq87XlzSNhE_rRuMjfhnRcA-P_NX8GgYC7As87fMWD-E-MUChJPJLM15UFRvE4kvZs2d-RYnF3xPaAI-WjXk3WIuT2LqJ8rJfuzhImWuCA","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource= project-staging"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"project-staging"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/project-staging/services/cloudbuild.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments-a07l/resources/mods-api-enable-artifactregistry: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [artifactregistry.googleapis.com]\nHelp Token: AZWD64rRrptER0yqSKEJZ0B2pfcl9V67-ofcT80ESyKDDrWa45PmbKw-A2LG5uqfcLGMDucyoocq7Zt_-9I6tva3jlyir9h0fhXyn65w2pKPToAV","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource= project-staging"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"project-staging"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/project-staging/services/artifactregistry.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments-a07l/resources/mods-api-enable-cloudfunctions: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [cloudfunctions.googleapis.com]\nHelp Token: AZWD64p60YMit9pr7xGGR39BQnjGOmFjr3QCuQ3KhEDWi47aobp5mxSi1G1560hVuYfvaYXCj60ykMD100iq9aVUyWxSs1Bvel6YYKuyKy8wbida","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource= project-staging"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"project-staging"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/project-staging/services/cloudfunctions.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments-a07l/resources/mods-api-enable-firebase: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [firebase.googleapis.com]\nHelp Token: AZWD64pns-5NFAVZBZ_A9MErDzj5WvpRndV2lR3YZyImYqE1XVuRzUs5UByohOOGbFxApjZDliTvPNepMNeFbXf13JXKh7-AlvYDV6gvis2-c1ir","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource= project-staging"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"project-staging"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/project-staging/services/firebase.googleapis.com:enable","httpMethod":"POST"}}`

## To Reproduce

1. Old 0.2.7 instance
2. Try to uninstall/update
3. Install new instance when theres one before
4. Try to remove new instance

## Expected behavior

Would be nice for extension to work properly with install/setup/unsintall steps.

## System information

- Firebase
- Stripe Extension 0.2.7
- Stripe Extension 0.3.1

**Comment by warrendodsworth** [comment]
Still seeing the same.

`Use the details below to help resolve this error, then retry uninstalling the extension.

; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/mods-api-enable-artifactregistry: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [artifactregistry.googleapis.com]\nHelp Token: AVUsNs0tgt0qCNJyqcCXdmGT8IYLIlctf6VHMovGTahYwfA2qm9awx9qSsJ0UbboUn-uGb_fvSYh8GqNsS1eCumrHpRrDHUQvgY9ukDKEfOQE8OS","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=linkmateapp"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"linkmateapp"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/linkmateapp/services/artifactregistry.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/mods-api-enable-firebase: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [firebase.googleapis.com]\nHelp Token: AVUsNs0C868LU6anvNOEdeBKK4kJCvW233Y-moIEwlXnTY1CcSO0pybnIEi4rqWNpRjYwIrxIguxC2_swp4gdDvDxiBiAq91JjdFH_cH8u1DcM1C","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=linkmateapp"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"linkmateapp"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/linkmateapp/services/firebase.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/mods-api-enable-iam: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [iam.googleapis.com]\nHelp Token: AVUsNs2KlO1z8tb9NyeDNsftHDoMaGsuxEGRQNnEdgP9csI-LZgzJhYrw5DGpSjzdkiMaecZPTj-TX-YF1QC1J3DEQPDG2d-dRXMZbUpVJNl6PR5","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=linkmateapp"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"linkmateapp"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/linkmateapp/services/iam.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/mods-api-enable-cloudbuild: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [cloudbuild.googleapis.com]\nHelp Token: AVUsNs0nByT_rfpQ_Qqde0p0NstKa0UwKOkQSccENpb3Yvb1j1Lww7e1xp__xcYPtyJ5eBWPV3ODz4_yJWPc3PLS-N9OzLNFKvgmR0tV6U3-UxlD","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=linkmateapp"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"linkmateapp"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/linkmateapp/services/cloudbuild.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-stripe-payments/resources/mods-api-enable-cloudfunctions: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [cloudfunctions.googleapis.com]\nHelp Token: AVUsNs3x67n5JD1JCqp0eQP-E-2bUGc-Wu1z-6B-XPEIywO8YwYTBlyJmgDPkStRT4jjfm2Z0siOLOfvTPNe8DqhIjG3uC-5Ybm09Dbp6eZ4Xasn","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=linkmateapp"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"linkmateapp`
