### ISSUE TITLE
Sample security rules should make subscriptions read-only

### ISSUE THREAD

**Issue by ToddKerpelman** [stripe/stripe-firebase-extensions#47]
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug

The sample security rules in the documentation has the `customers/{uid}/subscription/{id}` documents readable and writable by the client. 

Unless there's something I'm overlooking, I don't think there's any reason for the client to be writing to their `/subscriptions/` document. We should make it read only, so that it's only written to by the Cloud Function.

## To Reproduce

Open up the `firestore-stripe-extensions/POSTINSTALL.md` file. You'll see there's the following sample security rules:

```
    match /${param:CUSTOMERS_COLLECTION}/{uid} {
      allow read, write: if request.auth.uid == uid;

      match /checkout_sessions/{id} {
        allow read, write: if request.auth.uid == uid;
      }
      match /subscriptions/{id} {
        allow read, write: if request.auth.uid == uid;
      }
    }
```

Which would mean that any client could go ahead and update their subscriptions document. I'm assuming we don't want that to happen?

## Expected behavior

I believe that `/subscriptions/{id}` block should be:

```
      match /subscriptions/{id} {
        allow read: if request.auth.uid == uid;
        allow write: if false;
      }
```

**Comment by thorsten-stripe** [comment]
@ToddKerpelman thanks a million for catching this!

**Comment by Pushplaybang** [comment]
the sample app should also be updated to reflect thee changes

**Comment by thorsten-stripe** [comment]
@Pushplaybang I believe it is: https://github.com/stripe-samples/firebase-subscription-payments/blob/master/firestore.rules#L25-L27

Or are you referring to a different sample?
