### ISSUE TITLE
stripeRole is not added to the subscribing user after successfully paying through a checkout session

### ISSUE THREAD

**Issue by ReduxMPX** [stripe/stripe-firebase-extensions#478]
# Bug report

Stripe Extension being used: `firestore-stripe-payments`

## Describe the bug

The stripeRole is not added to the user claims on Firebase after they successfully subscribe to a product in Test Mode, the claims object (see screenshots) does not contain a stripeRole with the value I provided in the product metadata. See screenshots for my product configuration, user claim object, and the code that I'm using to check for the stripeRole.

`Note: I'm using the word Plus as the firebaseRole metadata value to check whether the user is subscribed`

## Expected behavior

I'm expecting to be able to read the user's decodedToken at runtime to see if they are a subscriber.

## Screenshots

`decodedToken`
![image_2022-12-20_220132063](https://user-images.githubusercontent.com/72150451/208832797-5c8aa9d0-9dc8-4949-8e21-dd4c84d7bec8.png)

`Product configuration (test mode)`
![image_2022-12-20_215710892](https://user-images.githubusercontent.com/72150451/208832203-13401cc6-ccbb-4548-a3a2-ca8b4f6f7d35.png)

`Snippet checking whether user is subscribed`
![image_2022-12-20_215536039](https://user-images.githubusercontent.com/72150451/208831988-ee724288-9978-4c33-95e6-1ccaaf594749.png)
## Additional context

``Cloud Logs after subscribing``
![image_2022-12-20_220324114](https://user-images.githubusercontent.com/72150451/208833069-05189237-c148-4c83-adcf-2bb232a82add.png)

## Other details
Relevant technologies in use:

`NextJS 13`  `Firebase`  `Chromium Browser`  `Stripe Test Mode`

**Comment by ReduxMPX** [comment]
Update: The role does get added eventually but it seems to consistently take up to half an hour for it to be added to the user claims.

**Comment by ReduxMPX** [comment]
Nevermind, I have resolved this issue. 

The problem was as simple as me missing the true parameter in the following snippet:
![Uploading Screen Shot 2022-12-21 at 3.08.25 PM.png…]()

**Comment by aviavinas** [comment]
I've tested the code and confirmed that the issue is related to missing metadata on the expanded product object. To fix the issue, I made the following change in the index.ts/index.js file:

> Replaced const role = product.metadata.firebaseRole ?? null; with const role = price.metadata.firebaseRole ?? null;
> Please test this change and let me know if it resolves the issue for you.
