### ISSUE TITLE
Support for Inline price data

### ISSUE THREAD

**Issue by moesalih** [stripe/stripe-firebase-extensions#48]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

Stripe supports Checkout Sessions with inline/custom prices: https://stripe.com/docs/payments/checkout/set-up-a-subscription#creating-prices-inline

Can we get support for that in this extension?

**Comment by moesalih** [comment]
Digging into the next release (2020-08-20) shows that support for multiple line items is there. Does that mean that I can simply pass a single line item with `price_data` instead of `price` to use inline/custom prices?

**Comment by thorsten-stripe** [comment]
@moesalih Yes, this would work via passing `price_data` in `line_items`, however in most cases you should not send price data from the client side, as that information can be manipulated by the sender (e.g. customer opening dev tools and modifying your price data).

You should only use this approach from the client-side if the price is meant to be modifiable by the customer, e.g. they can decide how much they want to pay via an input field etc. In all other cases you should define the price data securely in Stripe beforehand.
