### ISSUE TITLE
Pricing tables code generated on Stripe site causes catastrophic failure w Firebase "integration"

### ISSUE THREAD

**Issue by francisjervis** [stripe/stripe-firebase-extensions#482]
# Bug report

Unclear where this should be posted so I am posting it here
## Describe the bug

Following the instructions at https://stripe.com/docs/payments/checkout/pricing-table causes new customer objects to be created which are not linked to Firebase (or anything else).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Install Firebase stripe "integration"
Add a pricing table using the code generated on the Stripe dashboard
https://stripe.com/docs/payments/checkout/pricing-table
Watch as it becomes impossible to link your user records and checkout sessions or subscriptions.

## Expected behavior

Implementing a pricing table using the code generated on the Stripe dashboard does not cause days of wasted time and hundred of dollars in dispute fees trying to figure out why your customer data is completely messed up. Instead, it works.

## Screenshots
<img width="362" alt="Screenshot 2022-12-21 at 4 34 34 PM" src="https://user-images.githubusercontent.com/10519862/209099128-b05d1158-c894-4ba6-8677-0df52fe14f2d.png">

## System information

Irrelevant

## Additional context

This has cost me hundreds of dollars and I would never recommend Stripe to anyone. Cannot wait to move to another platform. This "feature" should be removed until it is fixed.

**Comment by christiangenco** [comment]
Oh man I just stumbled on this yesterday. The pricing table looks *so nice* and was so easy to integrate but I happened to notice that when I clicked a link from the pricing table it took me to a Stripe billing portal that had forgotten my information from a previous Stripe Checkout session. I was almost in this same boat.

The pricing table is a dangerous feature. I'm curious what the possible use case for creating a paying Stripe Customer that's not connected to a user account might be.

For this to be useful to Firebase users the "subscribe" buttons need to be connected to a callable functionn that can link the Stripe customer with the current logged in Firebase user.

**Comment by francisjervis** [comment]
> The pricing table is a dangerous feature

The phrase considered harmful springs to mind - it's not just the way they implemented it, it's the way it's actively pitched at SaaS startups, but has to be implemented in a way which is entirely unsuitable for that use case and/or with reams of ridiculous code to check if a new sub is actually a duplicate and issue refunds etc.

**Comment by jsteele-stripe** [comment]
The pricing table does not currently support re-use of Customer objects – the default behaviour is to create a _new_ customer for each table initiated session. This is a common point of developer friction that is top of mind for us. This pricing table limitation prevents any direct integration between this extension and the pricing table being possible, and I'm not sure it was ever mentioned as a supported workflow.

If you have any feedback specific to the pricing table, I'd recommend relaying that via our [support teams](https://support.stripe.com/contact).
