### ISSUE TITLE
Purchase using Payment Link results in "User not found!" 

### ISSUE THREAD

**Issue by pbljung** [stripe/stripe-firebase-extensions#485]
# Bug report

- Extension name: firestore-stripe-payments

## Describe the bug

I setup the extension Firestore-Stripe-Payments and can see customers & products in Firestore. Using the Extension provided html I can login and purchase subscriptions which are shown in Firestore. If I purchase a subscription using a Payment Link, that creates a new customer and purchase. The link purchase is sent via the Firestore-Stripe-Payments webhook to Google Functions. Firestore is however NOT updated. Google logs show that the webhook fails with "No user found!"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Fork the CodeSandbox project, complete code as per https://firebase.google.com/codelabs/stripe-firebase-extensions
Verify that you can successfully create subscription orders. 
My forked project is https://codesandbox.io/s/twilight-sun-uiperu
2. Create Payment Link for an existing product as per https://dashboard.stripe.com/payment-links
Use link complete subscription (test) purchase with new email and new name.
My test link is https://buy.stripe.com/test_cN28ze76155Rg0w3cc
3. Observe creation of new customer in https://dashboard.stripe.com/test/customers and successful purchase.
Note EACH use of Payment Link will create a new customer. If using same name and email you get DUPLICATE customers in Stripe.
4. Refresh Firestore expecting to see new customer and checkout sessions, but there are no new entries.
5. Inspect Google Logs (link in Firebase Functions section) to see (red highlighted) errors where function fails on webhook with "User not found!" 

## Expected behavior
Ideally Payment Link can be used in an advertising campaign to find new customers. Stripe-Firebase-Extension webhook should accept Payment Link info and create new customer and subscription entries in Firestore. If new customer has same name & email as an existing customer, ideally the existing customer_id is used to prevent duplicate customers.

## Screenshots

<img width="1840" alt="Screen Shot 2023-01-02 at 9 11 24 PM" src="https://user-images.githubusercontent.com/24781011/210443507-97d15e09-2673-47e8-8eff-663e8409323b.png">

## System information

- OS: macOS
- Browser (if applies) Chrome

**Comment by jsteele-stripe** [comment]
This is expected as there is currently no way to use a pre-existing Customer object (such as the ones created by this extension) with a Payment Link. The default behaviour for Payment Links is to create a new Customer object [when required](https://stripe.com/docs/api/payment_links/payment_links/create#create_payment_link-customer_creation).
