### ISSUE TITLE
Stripe Product Features are not synced to Firestore collection

### ISSUE THREAD

**Issue by fetchhai** [stripe/stripe-firebase-extensions#493]
# Bug report

- Extension name: firestore-stripe-payments

## Describe the bug

In Stripe, we have the option to add features list at the product level. But when syncing, its not carried over to the firestore db.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Stripe
2. Search for a product
3. Add features list in "Additional Options"
4. Check in Firestore DB in the products collection
5. features is not updated in the collection

## Expected behavior

Features list should be successfully synced in the Firestore products collection

## Screenshots

N/A

## System information

N/A

## Additional context

N/A

**Comment by iKK001** [comment]
Do you plan in the future to sync the product's `features` list with the Firebase-Stripe-Extension for Payments/Subscriptions ?

Currently my observation is that the webhook-event at product-creaton fills most of the product fields (including the prices subcollection). However, the product `Feature list` is currently missing.

**Comment by jakehockey10** [comment]
Seems like it is part of the API according to this: https://stripe.com/docs/api/products/object#product_object-features

**Comment by maderesponsively** [comment]
@jakehockey10 Yes - i noticed this. Surely this is an easy update.

**Comment by jakehockey10** [comment]
@maderesponsively Here is the PR for it.  Looks like it has been ready for a while now: https://github.com/invertase/stripe-firebase-extensions/pull/578

But I do believe Invertase will get to it soon.  They've been doing good work on this project lately.
