### ISSUE TITLE
Getting Error: "No payment sheet has been initialized yet"

### ISSUE THREAD

**Issue by alleybellack** [stripe/stripe-firebase-extensions#499]
# Bug report

- Extension name: firestore-stripe-payments

## Describe the bug

Hello, I reached out to stripe support and they told me to open an issue here. I am integrating your extension for one time payments. After following the docs + reading online, I'm not sure how to solve it. 

Docs I've followed: 
1.  https://console.firebase.google.com/u/0/project/crowdsorce-f4be2/extensions/instances/firestore-stripe-payments?tab=usage
2. https://stripe.com/docs/payments/accept-a-payment?platform=react-native&ui=payment-sheet

## To Reproduce

Code

```
// Navigation container 

<AuthProvider>
      <NavigationContainer
        linking={LinkingConfiguration}
        theme={colorScheme === "dark" ? DarkTheme : DefaultTheme}
      >
        <StripeProvider
          publishableKey="pk_test...."
          urlScheme="your-url-scheme" // required for 3D Secure and bank redirects
          merchantIdentifier="merchant.com.{my app name}" // required for Apple Pay //
        >
          <RootNavigator />
        </StripeProvider>
      </NavigationContainer>
    </AuthProvider>


// app screen where I'm wanting the payment sheet

import { useStripe } from "@stripe/stripe-react-native";
const { initPaymentSheet, presentPaymentSheet } = useStripe();

useEffect(() => {
    initializePaymentSheet();
  }, []);

  const initializePaymentSheet = async () => {
    const { paymentIntent, ephemeralKey, customer } = await getCheckoutDetails(
      authUser?.uid,
      20 // dollars which I multiply * 100 in the above function. the function above is succeeding & giving back the correct info 
    );

    const { error } = await initPaymentSheet({
      merchantDisplayName: "My company, Inc.",
      customerId: customer,
      customerEphemeralKeySecret: ephemeralKey,
      paymentIntentClientSecret: paymentIntent,
      allowsDelayedPaymentMethods: false,
      defaultBillingDetails: {
        name: "Jane Doe",
      },
      // customFlow: true,
    });
    if (!error) {
      setLoading(true);
    }
  };

  const openPaymentSheet = async () => {
    const { error } = await presentPaymentSheet();

    if (error) {
      Alert.alert(`Error code: ${error.code}`, error.message); // this is where I'm getting the alert error 
    } else {
      Alert.alert("Success", "Your order is confirmed!");
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <Text>Provider Details</Text>
      <Text>Your booking info</Text>
      <Text>Cancellation Policy</Text>
      <Text>Price details</Text>
      <Text>Pay with</Text>
      <Text>Ground rules</Text>

      <Button
        style={{ marginTop: 40, width: 240 }}
        labelStyle={{ fontFamily: "Avenir", fontSize: 16 }}
        mode="contained"
        onPress={openPaymentSheet}
      >
        Checkout
      </Button>
    </SafeAreaView>
  );
}

// firebase fn 
export async function getCheckoutDetails(buyerId: string, amountDollars: number) {
  try {
    const docRef = await addDoc(
      collection(database, "customers", buyerId, "checkout_sessions"),
      {
        client: "mobile",
        mode: "payment",
        amount: amountDollars * 100, //needs to be in cents
        currency: "USD",
        createdAt: serverTimestamp(),
        // paymentMethod: "",
      }
    );
    console.log("Document written with ID: ", docRef.id);

    const unsub = onSnapshot(
      doc(database, "customers", buyerId, "checkout_sessions", docRef.id),
      (doc) => {
        console.log("Current data: ", doc.data());
        const docData = doc.data();
        if (
          docData?.hasOwnProperty("ephemeralKeySecret") &&
          docData?.hasOwnProperty("paymentIntentClientSecret") &&
          docData?.hasOwnProperty("customer")
        ) {
          const paymentIntent = docData.paymentIntentClientSecret;
          const ephemeralKey = docData.ephemeralKeySecret;
          const customer = docData.customer;
          console.log("payment ", paymentIntent);
          console.log("ephemeralKeySecret ", ephemeralKey);
          console.log("customer ", customer);
          return {
            paymentIntent,
            ephemeralKey,
            customer,
          };
        }
      }
    );
  } catch (e) {
    console.error("Error adding document: ", e);
  }
}
```

## Expected behavior

I would like the payment sheet to render.

## Screenshots

<img width="349" alt="Screenshot 2023-02-13 at 4 12 25 PM" src="https://user-images.githubusercontent.com/118226432/218783369-06527b58-fec9-4658-8be6-b5c99bac7749.png">

## System information

- OS: macOS
- Browser: Chrome
- Expo, firebase firestore 
- React Native

## Additional context

Thanks in advance!

**Comment by alleybellack** [comment]
@jsteele-stripe Hey Jonathan, tagging you to get a pair of eyes on this. Thanks in advance for your help!

**Comment by jsteele-stripe** [comment]
@alleybellack Does your `getCheckoutDetails` function call to the Firebase function resolve and return the fields you expect? I'd wrap some error handling around that as it seems there is likely an unhandled exception.

**Comment by alleybellack** [comment]
Thanks for your response! This is what the doc.data() is returning:

Current data:  {"amount": 2000, "client": "mobile", "created": {"nanoseconds": 767000000, "seconds": 1676391033}, "createdAt": {"nanoseconds": 834000000, "seconds": 1676391031}, "currency": "USD", "customer": "cus_NLoWKf2Yo5XGkC", "ephemeralKeySecret": "ek_test.....", "mode": "payment", "paymentIntentClientSecret": "pi_......", "setupIntentClientSecret": null}

should setupIntentClientSecret be non null?

The warning I'm getting is: "Possible Unhandled Promise Rejection (id: 1):
TypeError: undefined is not an object (evaluating '_yield$getCheckoutDet.paymentIntent')"

**Comment by jsteele-stripe** [comment]
@alleybellack 

> should setupIntentClientSecret be non null?

Yep, that's expected as you're working with Payment Intents (not a Setup Intent).

Can you log out the `error` returned from `initPaymentSheet` call? Also, which version of `@stripe/stripe-react-native` is your project using and which Expo version are your targeting?

**Comment by alleybellack** [comment]
It seems like initPaymentSheet isn't even getting reached. Does stripe have example code for using this extension for one-time payments? 

"@stripe/stripe-react-native": "0.19.0",
"expo": "~47.0.12",

**Comment by alleybellack** [comment]
I think there's something strange happening during getCheckoutDetails because nothing is getting executed after that

**Comment by jsteele-stripe** [comment]
@alleybellack 

> Does stripe have example code for using this extension for one-time payments?

Nothing specific, but following the regular payment guide (like you are) _should_ just work. 

Could you maybe try upgrading your `@stripe/stripe-react-native` dependency? It's pretty [outdated](https://github.com/stripe/stripe-react-native/blob/master/CHANGELOG.md).

**Comment by alleybellack** [comment]
Thanks. Just upgraded

I think it has to do with the onSnapshot call & needing to detach the listener like calling unsub() & figuring out the correct way to return the data (customer, paymentIntent & ephemeralKey) outside the onSnapshot listener. Going to look into this more but making progress.

Docs for this would definitely help, just because they're all for regular stripe usage & not the extension. Not sure how many people use the extension though

**Comment by alleybellack** [comment]
Okay I figured it out. The onSnapshot needs to be called in a useEffect hook (on the screen you want the payment sheet to show) in order to set the docData state which is accessed in initPaymentSheet
Thanks!
