### ISSUE TITLE
Fairly important documentation mistake in Stripe documentation

### ISSUE THREAD

**Issue by joshkautz** [stripe/stripe-firebase-extensions#501]
Right now the live extension in production tells users to create a restricted key with read access limited to the Subscriptions” and “Plans” resources. The _Plans_ resources isn't an option in Stripe; I suspect it is supposed to say _Prices_, but I'm not an expert with Stripe so I could be mistaken on the correct resource.

https://github.com/stripe/stripe-firebase-extensions/blob/785d8a78bf03db4c252cf9173a70df3555137221/firestore-stripe-payments/extension.yaml#L236

![image](https://user-images.githubusercontent.com/17554471/219512789-5d9fc905-0e25-4403-8ebc-df8786d90b86.png)

**Comment by jsteele-stripe** [comment]
This was fixed here (https://github.com/stripe/stripe-firebase-extensions/commit/055d467b3aa9441dae372904818847fb222ba57d). We just haven't cut a new release since those changes.

**Comment by joshkautz** [comment]
Ah, gotcha. Thank you! 😅
