### ISSUE TITLE
CORS issue when calling function

### ISSUE THREAD

**Issue by jettdc** [stripe/stripe-firebase-extensions#504]
# Bug report

- Extension name: `firestore-stripe-payments`

## Describe the bug

When calling `ext-firestore-stripe-payments-createPortalLink` getting the cors error: 
```
Access to fetch at 'https://us-central-1-<myapp>.cloudfunctions.net/ext-firestore-stripe-payments-createPortalLink' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

## Screenshots
```
const functions = getFunctions(firebaseApp, 'us-central1')
const functionRef = httpsCallable(functions, 'ext-firestore-stripe-payments-createPortalLink');
```
As far as I can tell, it's being called correctly.

## System information

- Windows

## Additional context

I am aware of the other issue here #59, but I've double checked that my region and function names are correct!

**Comment by thetwentyseven** [comment]
I do have exactly the same issue in local and production.

**Comment by thetwentyseven** [comment]
I got it working. My problem was the name of the function:
```
        const functions = getFunctions();
        const functionRef = httpsCallable(functions, 'ext-firestore-stripe-payments-createPortalLink');
        const { data } = await functionRef({
            returnUrl: window.location.origin,
            locale: "auto", // Optional, defaults to "auto"
        });
        window.location.assign(data.url);
```

**Comment by jelling** [comment]
Had the same issue due to the name of the function. Root cause is that the documentation is out of date:

Doc page: https://firebase.google.com/codelabs/stripe-firebase-extensions#4

![image](https://github.com/stripe/stripe-firebase-extensions/assets/1887486/6f4fb0fc-f5ff-4fb4-9ca7-ff44c7507121)

**Comment by VukIG** [comment]
I am having the same issue


`const functions = getFunctions(app, 'us-central1');
    const functionRef = httpsCallable(functions, 'ext-firestore-stripe-payments-createPortalLink');
    const { data } = await functionRef({
      customerId: user?.uid,
      returnUrl: window.location.origin,
    });`

`Access to fetch at 'https://us-central1-pizzaplace-a31d7.cloudfunctions.net/ext-firestore-stripe-payments-createPortalLink' from origin 'http://localhost:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`
