### ISSUE TITLE
One-time trial

### ISSUE THREAD

**Issue by oshima819** [stripe/stripe-firebase-extensions#52]
# Feature request

`firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

Users who have used the trial once do not want to give the trial again.

1. I canceled a new subscription during the trial period.
1. If I purchase the subscription again after the trial period ends, the trial will start.
1. Therefore, if I set a trial period, you can repeatedly subscribe for free.

## Describe the solution you'd like

Do not give a trial to customers who have `/customers/{uid}/subscriptions`.

## Describe alternatives you've considered

I thought it was possible with line_items, but it was a different feature.

Thanks.

**Comment by thorsten-stripe** [comment]
Thanks, @oshima819, for outlining your use case.

Would setting `trial_from_plan:false` work for you:

```js
const docRef = await db
  .collection("${param:CUSTOMERS_COLLECTION}")
  .doc(currentUser)
  .collection("checkout_sessions")
  .add({
    price: "price_1GqIC8HYgolSBA35zoTTN2Zl",
    trial_from_plan: false,
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
```
This way you can check if they have a previous subscription, and if so you set `trial_from_plan:false`. Would that dynamic work for you?

**Comment by thorsten-stripe** [comment]
Great, I'm planning to add this to the next release early next week.

**Comment by oshima819** [comment]
Thanks

**Comment by thorsten-stripe** [comment]
This has been added to the next release which should go live either Wednesday or Thursday PT time.
