### ISSUE TITLE
Support additional checkout session parameters

### ISSUE THREAD

**Issue by keithkelly31** [stripe/stripe-firebase-extensions#541]
# Feature request

- Extension name: firestore-stripe-payments

## Is your feature request related to a problem? Please describe.

I need additional parameters to be passed to the Stripe subscription through the checkout session.
- **description**: A single user can have multiple subscriptions in my app. The description parameter is necessary to differentiate between the subscriptions in the customer portal.
- **trial_period_days**: The trial period on the product price is now legacy, and Stripe suggests not using that option. I will need to set the trial period days in the checkout session.

## Describe the solution you'd like

Have the parameters described or possibly all of the parameters listed [here](https://stripe.com/docs/api/subscriptions/create) added to the function that handles the checkout sessions.

## Describe alternatives you've considered

The only alternative is to write my own functions, but I am using this extension so I do not have to do that.

## Additional context

N / A

**Comment by matheusbaumgart** [comment]
Massive plus one here
