### ISSUE TITLE
403 Webhook Error on multiple events

### ISSUE THREAD

**Issue by preconception** [stripe/stripe-firebase-extensions#55]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

Getting 403 Error from Stripe Dashboard for the following events:

price.created
product.created

## Expected behavior

Would write products and prices to firestore

This message is what the webhook is getting back in response from firestore.

Status code is 403

```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/ext-firestore-stripe-subscriptions-handleWebhookEvents</code> from this server.</h2>
<h2></h2>
</body></html>
```

**Comment by preconception** [comment]
I am not sure how firestore/stripe would authenticate and I do not remember seeing any instructions on this?

is it supposed to be automatic?

**Comment by thorsten-stripe** [comment]
Hi @preconception, these functions should be automatically configures as public unauthenticated access. Can you check the cloud functions for your project: https://console.cloud.google.com/functions/list

It should look like this stating `Allow unauthenticated` for the webhook handler function.
![image](https://user-images.githubusercontent.com/23213994/91698164-d6da0e00-eba4-11ea-8c4b-fd0dd592693d.png)

**Comment by untouch** [comment]
Same Issue here

`<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/ext-firestore-stripe-subscriptions-handleWebhookEvents</code> from this server.</h2>
<h2></h2>
</body></html>`

**Comment by accessdeniedIT** [comment]
1. Go to the cloud function list
2. Select the two above demonstrated by thorsten-stripe
3. Click "Add members" under Permissions tab in the right side
4. Enter "allUsers" under "New members"
5. Select Role as "Cloud Functions --> Cloud Functions Invoker"
6. Save

**Comment by preconception** [comment]
That worked! @accessdeniedIT 

Is this something I did wrong on my end that I could have avoided or a misconfiguration somewhere else?

**Comment by accessdeniedIT** [comment]
no it's google, or stripe im their update.

**Comment by preconception** [comment]
I got it.

All I have to say is **wow** - thank you so much!

**Comment by joehan** [comment]
If anyone else is running into this - these functions should be made public by default, but the Extensions team broke that with a bad config rollout recently. It is fixed now, but instances installed between August 27 and August 31 may be affected.

If you are affected by this, you can fix it by reconfiguring the instance or by following the steps to manually make them public that @accessdeniedIT posted above. Sorry for the inconvenience everyone!

**Comment by thorsten-stripe** [comment]
Thanks all. I've checked with the Firebase team and they have confirmed that this was a bug that has now been resolved. Going to leave this issue open for a couple more days in case others encounter it.

**Comment by raghavmri** [comment]
I am facing the same issue now

**Comment by Prasad-Omprakash** [comment]
I am facing the same issue 403 error from web hook. can someone help ? Thanks

**Comment by JaiJaiJordan** [comment]
I am facing the same issue....
