### ISSUE TITLE
Unable to call createCheckoutSession: FirebaseError: Expected first argument to collection() to be a CollectionReference

### ISSUE THREAD

**Issue by logesh2496** [stripe/stripe-firebase-extensions#563]
# Bug report

- Extension name: `firestore-stripe-payments`

## Describe the bug

Tried to call the function `await createCheckoutSession(payments, {
    price: priceId, // One-time price created in Stripe
  });` after setting up the firebase extension. Customer and Product collections are properly set and working as expected except the createCheckSession.
Encountered the error:
` Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore`

## To Reproduce

Simply call the createCheckoutSession by following the "How this extension works" documentation from firebase extensions

## Expected behavior

I should be able to get the session url from the method

## Screenshots

<img width="571" alt="image" src="https://github.com/invertase/stripe-firebase-extensions/assets/55389513/94c07a84-4b5e-4670-878a-6922e3e712dc">

**Comment by antopolskiy** [comment]
What is your version of `firebase`? I get this error when I try to update my `firebase` package to >v10.0.0

Btw, are there plans to update the `firebase` dependency so that it works with the newest version?

**Comment by antopolskiy** [comment]
Yes, using v9 seems to do the trick for me. However, if I use v9, there is another issue that appears which is https://github.com/invertase/stripe-firebase-extensions/issues/509

I describe the workaround I've found that works at the moment. Though I hope the extension SDK will soon be updated to firebase v10.

**Comment by antopolskiy** [comment]
@logesh2496 Actually, I was just able to solve the issue in a better way using this thread https://github.com/invertase/stripe-firebase-extensions/issues/304

Here are the relevant parts of my `package.json`:
  "dependencies": {
    "@invertase/firestore-stripe-payments": "^0.0.7",
    "firebase": "^9.18.0",
  },
  "resolutions": {
    "@firebase/firestore": "3.13.0",
    "@firebase/auth": "0.23.2",
    "@firebase/app": "0.9.13"
  },
```

Then `yarn install` worked like a charm.

**Comment by agoransson** [comment]
This PR helped me https://github.com/invertase/stripe-firebase-extensions/pull/645

**Comment by maztak** [comment]
In my case, dependencies version may affect this.
It seems Firebase JavaScript SDK v10 is not compatible with this package v0.0.7.

- I downgraded firbase to v9, and use `overrides`.
- I use modern `@firebase/firestore`, not `firebase/firestore`.

And it worked.

```json
  "dependencies": {
    "@invertase/firestore-stripe-payments": "^0.0.7",
    "firebase": "^9.23.0",   
  },
  "overrides": {
    "@firebase/app": "^0.11.4",
    "@firebase/auth": "^1.10.0",
    "@firebase/firestore": "^4.7.10"
  },
```
