### ISSUE TITLE
Client can't know if there was a problem in attaching a session id

### ISSUE THREAD

**Issue by GClock** [stripe/stripe-firebase-extensions#57]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

when there is a problem in createCheckoutSession (which can happen because of many reasons --network failure or validation error from stripe), there is no way to know from the client why sessionid wasn't created.
In case of a valid error may be you should create something like "error" so that client can monitor both sessionid as well as "error" and can appropriately handle the situation. 
## To Reproduce
Create a customer and make a successful subscription in one currency .Let's say USD.

When the same customer tries to make another subscription in a different currency ,we get the following error from the function "createCheckoutSession" .
"Checkout session creation failed for doc [xyz]: Customer with currency usd cannot subscribe to price of different currency (inr)."

While this issue can be handled on the client side by checking customer subscription ,the general nature of the problem remains same .Client has to keep waiting for a sessionid in case of an error which may never come.

 
## Expected behavior

 Client should be informed that there was a problem in attaching a session.

**Comment by thorsten-stripe** [comment]
Thanks so much for flagging this! It has been fixed and will roll out with the next release of version 0.1.6 on Thursday.
