### ISSUE TITLE
Seat-based subscription plan

### ISSUE THREAD

**Issue by crouinicrouina** [stripe/stripe-firebase-extensions#58]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

We're a software company. We have monthly subscription plans at a fixed rate for our customers. We have already built a fixed price subscription system on Firebase with PayPal ourselves.

However, we would like to do more B2B and we'd like to allow companies' administrators to manage the subscriptions of all the companies' employees. To do so, we'd need to handle seat-based subscriptions so that administrators can easily add/remove seats for the companies' employees.

## Describe the solution you'd like

We'd like to be able to change the number of seats for a fixed-price subscription on-the-go, based on administrators inputs.

We will also need to manage the claims : 

- `admin` claim to manage the number of seats and to assign the seats to the employees
- `employee` claim to know whether the user has a valid licence to access our software

Managing claims within Stripe extension might be out of scope though ?

## Describe alternatives you've considered

Use the subscriptions APIs offered by PayPal (since we're using this payment gateway at the moment) or Stripe which both have seat-based features. 

The management of licences will likely be done within cloud functions / firestore but we didn't think about the exact implementation yet.

Maybe a workaround with this extension in this current state would be to create many products for 5, 10, 25, 50, 100, ... seats and allow the administrators to update their subscriptions ?

## Additional context

We have limited development resources (manpower/time) to implement this new feature. If this extension could help us achieve our goal more easily, we will likely switch from PayPal to Stripe.

**Comment by thorsten-stripe** [comment]
@crouinicrouina thanks for outlining your use case!

Stripe checkout supports the setting of quantities, however the customer billing portal does not yet. Let me check on the status of that with the team.

Regarding managing the claims for each user/seat, I think that's outside of the scope for the extension. But you can use the customer doc to track the availability of seats as the extension always sets `merge:true` when modifying the customer doc. 

E.g. what I'd do is create a `seats` subcollection on the customer doc and when an admin wants to add a new user to that collection I'd compare the amount of docs in the `seats` collection agains the quantity on their subscription.

One issue is that the extension automatically creates a customer doc when you sign up a new users, which wouldn't be desired in your case. 

How do `employee` users get created? Does the administrator invite them via email?

**Comment by rakeshgoyal** [comment]
I have an angular firebase app. I am adding a premium version where Enterprises can subscribe on a per seat basis. Is there a workaround to achieve this given the extension doesn't support it. Is there a way to do this using vanilla stripe implementation using firebase and angular?

**Comment by thorsten-stripe** [comment]
The Stripe customer portal now allows updating of quantities which can be used to manage seats: https://github.com/stripe/stripe-firebase-extensions/issues/88#issuecomment-720308869

**Comment by Lxstr** [comment]
For anyone interested in cloud function implementation of seats.
Any feedback would be great. 

[https://github.com/Lxstr/stripe-firebase-seats](https://github.com/Lxstr/stripe-firebase-seats)
