### ISSUE TITLE
createPortalLink() failed for return_url like 'chrome-extension://wtrfdnfleobejgjajmgkfahnafphfooa'

### ISSUE THREAD

**Issue by aptash** [stripe/stripe-firebase-extensions#63]
# Bug report

- Extension name: firestore-stripe-subscriptions

## Describe the bug

createPortalLink() failed when used with return_url like this: 'chrome-extension://wtrfdnfleobejgjajmgkfahnafphfooa'.

I try to integrate the checkout process into the Chome extension and I get:
```
Request URL: https://********.cloudfunctions.net/ext-firestore-stripe-subscriptions-createPortalLink
Request Method: POST
Status Code: 500 

Response:
{"error":{"message":"Not a valid URL","status":"INTERNAL"}}
```

## To Reproduce
Short: call the code below from the Chrome extension:
```
		// Call billing portal function
		const functionRef = firebase
			.app()
			.functions(functionLocation)
			.httpsCallable('ext-firestore-stripe-subscriptions-createPortalLink');
		const { data } = await functionRef({ returnUrl: window.location.origin });
```

Long: use the sample:
https://github.com/stripe-samples/firebase-subscription-payments
inside of the Chrome extension.

## Expected behavior

A user accesses the Stripe portal and the return link is like this: 'chrome-extension://wtrfdnfleobejgjajmgkfahnafphfooa/somepage.html'.

I can hardcode the return URL to ANY https://...
`const { data } = await functionRef({ returnUrl: 'https://anyurl.com' });`
then everything is working fine from the Chrome extension.
It's obvious that returnUrl doesn't play any serious role. It's just used in https://billing.stripe.com/session/*********** to allow a user return to the initial page.

Thanks in advance!

**Comment by aptash** [comment]
This line of the code doesn't allow using URLs like this: ''chrome-extension://...'
```
    const session = await stripe.billingPortal.sessions.create({
      customer,
      return_url,
    });
```

**Comment by thorsten-stripe** [comment]
It's not an issue with the extension but rather Stripe doesn't recognize this as a valid URL. 

@aptash would you mind outlining your use case a bit? Do you also create the subscription from within the extension? If so you might see the same error for the checkout session creation. Once I have some more details I can check with the team on this. If you don't want to share these details publicly feel free to [DM me on Twitter](https://twitter.com/thorwebdev).

**Comment by aptash** [comment]
Thanks a lot for the quick response!

You are right - Stripe doesn't recognize chrome-extension:// as a valid URL.

My use case: I need to make a payment process for a premium version of the Chrome extension without the creation of a hosted payment page but right inside of the extension.

Let presume you have "Adblock Plus - free ad blocker" extension installed.
Then you can open this page in your Chrome browser:
chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/options.html

There is an example web client for usage with the Stripe Subscriptions Firebase Extension:
https://github.com/stripe-samples/firebase-subscription-payments

Imagine the process (described in this demo) inside of the page like this:
chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/options.html

That's what I want to do!

As for your question:
I started my development with an already subscribed user. That is why I meet the problem at this step.

`Do you also create the subscription from within the extension? If so you might see the same error for the checkout session creation.`
You are absolutely right! If I create the subscription from within the extension then I get the error:
```
ext-firestore-stripe-subscriptions-createCheckoutSession
❗️[Error]: Checkout session creation failed for doc [nSGzYAXLBWh3S1bDWG6l]: Not a valid URL
```
But if I pass some random https:// URLs then everything is fine.

Can we do something about adding chrome-extension:// as valid URL for Stripe?

**Comment by thorsten-stripe** [comment]
Thanks for outlining your use case @aptash! I'm discussing with the team to see if we can enable this, but not yet sure where this falls in terms of prioritization. 

In the meantime a potential workaround might be to host a "proxy redirect page" (e.g. with Firebase hosting), provide the URL for that to checkout and the billing portal and have that page redirect back into your extension.

**Comment by aptash** [comment]
May I know what you decide?

**Comment by jsteele-stripe** [comment]
@aptash This is not something the Customer Portal supports right now. The feature request is independent of this extension, so closing out this issue for now.
