### ISSUE TITLE
Checkout without internationalization option

### ISSUE THREAD

**Issue by crosskpixel** [stripe/stripe-firebase-extensions#64]
# Feature request

- enable you to inform the location and internal checkout of the stripe to work with this

## Is your feature request related to a problem? Please describe.

- Is your feature request related to a problem? Please describe.

## Describe the solution you'd like

- When inserting the session creation document, enable the creation of the checkout session with internationalization

## Describe alternatives you've considered

Do not use the extension

**Comment by thorsten-stripe** [comment]
Both Stripe checkout and the customer portal are automatically localized based on the customer's browser locale: https://stripe.com/docs/payments/checkout/customization#localization
