### ISSUE TITLE
How do I disable a function that I do not want to use from the extension

### ISSUE THREAD

**Issue by GClock** [stripe/stripe-firebase-extensions#66]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

I have two different set of users and I do not need to create customers always .I have looked at extension and wrote a conditional customer creation function that is working as expected .I have commented out the code  inside function create customer. The question I have is when I upgrade the extension it will override the commented code .If I delete the unwanted function will it help? If not ,is there a way to select what function to deploy during upgrade.

Without these options I always have to manually delete/comment the function and deploy and unwanted things can happen during the same window.

Appreciate any suggestion you may have.

**Comment by thorsten-stripe** [comment]
Unfortunately deleting the `createCustomer` function via the Firebase console will cause future updates to error (see https://github.com/stripe/stripe-firebase-extensions/issues/51#issuecomment-682275324).

@jhuleatt are there any plans to allow on/off toggles per function during the installation of the extension? If not we'd have to build that in via some configuration dropdown for example?

**Comment by JakeMalis** [comment]
Related to this question: I would love if there weren't two separate collections for customers and users. I have each Firebase auth user saved as Firestore doc with their uid as their name. I think most people also have it that way, it would be nice if all the stripe data was stored within their user doc.

**Comment by GClock** [comment]
Thank you @thorsten-stripe for your reply .It would be nice to have the ability to have on/off toggle functions during extension deployment/upgrade in future. 

One more question I have on the integration. Stripe checkout does not support billing_cycle_anchor .I would have liked to have this so that I can consistently follow a single cycle for every customer.Without this we have to have complicated logic of resetting things every day based on users subscription .Appreciate any suggestion you may have on this.

**Comment by ajbarry** [comment]
@JakeMalis I wasn't aware either but it sounds like a single user/customer collection is supported: https://github.com/stripe/stripe-firebase-extensions/issues/51#issuecomment-679767272

I'm going to test this out myself and will post back if I find anything adverse.

**Comment by JakeMalis** [comment]
@ajbarry Thank you so much for sending me this, that helps a lot!

**Comment by thorsten-stripe** [comment]
While this doesn't allow enabling/disabling of functions per se (that would be a feature request to the Firebase Extensions team), #77 allows the disabling of syncing customers on creation, which should solve most of the issues reported here. This will roll out with the next release v. 0.1.7, hopefully on Thursday PT.

**Comment by ajbarry** [comment]
Noice. Thanks @thorsten-stripe! Looking forward to the release... We will need it for sure...

@JakeMalis I just ran into the first issue that this fix will solve for us (if you are also combining the user/customer collection).
Since the `createCustomer` is triggered from a Firebase Auth hook, I just hit a race condition where my own `createUser` function fails because `createCustomer` triggered before my call to `firestore.collection('users').doc(uid).create(props)`.

I could simply change the firestore call from `create(props)` to `set(props, {merge: true})` but then I loose the strong semantics I have around create vs update on my users collection without guarding every call myself.

It's a race so I don't always get this error and my logic could be refactored to account for it but I will opt to disable `createCustomer` when it is available. Thanks again @thorsten-stripe.

**Comment by ajbarry** [comment]
Hey @thorsten-stripe ... any word on the 0.1.7 release for this fix?

**Comment by thorwebdev** [comment]
@ajbarry sorry for the delay, the Firebase team has moved to a biweekly (every other week) release schedule. I checked with @jhuleat and he let me know that it's scheduled for release on Thursday Oct 22nd PT time.

**Comment by ajbarry** [comment]
Ok great. Thanks for the update @thorsten-stripe

**Comment by Renkon117** [comment]
> Noice. Thanks @thorsten-stripe! Looking forward to the release... We will need it for sure...
> 
> @JakeMalis I just ran into the first issue that this fix will solve for us (if you are also combining the user/customer collection).
> Since the `createCustomer` is triggered from a Firebase Auth hook, I just hit a race condition where my own `createUser` function fails because `createCustomer` triggered before my call to `firestore.collection('users').doc(uid).create(props)`.
> 
> I could simply change the firestore call from `create(props)` to `set(props, {merge: true})` but then I loose the strong semantics I have around create vs update on my users collection without guarding every call myself.
> 
> It's a race so I don't always get this error and my logic could be refactored to account for it but I will opt to disable `createCustomer` when it is available. Thanks again @thorsten-stripe.

I have been looking for someone who had the same issue like this!!
