### ISSUE TITLE
Custom title in the line item of the invoice

### ISSUE THREAD

**Issue by HerbertBodner** [stripe/stripe-firebase-extensions#67]
# Feature request

## feature request

My web app has users and teams,. Users can be part of multiple teams.
Then I offer a "Premium Plan" subscription for my users, but the subscription applies to a whole team. When a user buys a subscription for a team, then the whole team gets access to the premium features.
So one user can buy 2 subscriptions for 2 separate teams. Then they don´t know which invoice is for which subscription, as both invoices just state "Premium Plan" in the description of the line item.

## Possible solution
Similar to the *metadata* field in the *checkout_sessions* collection, I would like to be able to overwrite the description in the line item of the invoice via the *checkout_session* object. 

## Current workaround
Right now I use the *metadata* from the *subscription* collection (the metadata info is passed via the *checkout_session* into the *subscription* object). So I am at least able to display relevant subscription info to the user in the web app.

**Comment by brendanm-stripe** [comment]
Hi Herbert, thanks for submitting this. The subscription line item descriptions map to the name of the Product used by the Price/Plan. While we don't have a way of supporting today exactly what you describe, I can offer two options as workarounds:

1. Using the Subscription `metadata` you already have, you can [listen to `invoice.created` events with webhooks](https://stripe.com/docs/billing/subscriptions/webhooks#understand) and use that opportunity to [add a `memo`](https://stripe.com/docs/billing/invoices/customize#memo) or [footer](https://stripe.com/docs/billing/invoices/customize#footer) to the invoice indicating which "Team" it corresponds to.
2. When creating your Subscriptions, you could define ad-hoc Prices with `price_data` allowing you to also supply `product_data` that includes a `name` that will be shown on the Invoices. See API ref here: https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-line_items-price_data-product_data-name

Would one of those suit your needs?

**Comment by HerbertBodner** [comment]
Great, both are viable solutions. Thanks @brendanm-stripe

**Comment by brendanm-stripe** [comment]
Excellent! My pleasure, glad it gets you what you need :)
