### ISSUE TITLE
Can not sync up user id with stripe user id.

### ISSUE THREAD

**Issue by Nyceane** [stripe/stripe-firebase-extensions#70]
# Feature request

- Extension name: [e.g. `firestore-stripe-subscriptions`, or leave empty if suggesting a new extension]

## Is your feature request related to a problem? Please describe.

Can not sync up user id with stripe user id.  What if I want the user Id to be the same as stripe userid?  and also I can't add names to the thing as well.

## Describe the solution you'd like

Using same firebase userid as stripe user id

## Describe alternatives you've considered

rewrite the entire thing

## Additional context

I also can't add display name to the stripe users.  This is a big  problem for syncing up stripe, android and iOS payment.  There is always more steps to check whether user have paid through one way or another (in app purchase or stripe over the web), if it's just using one set of userId we can sync this up much more easier.

**Comment by Nyceane** [comment]
I ended up rewriting the code into my own functions...

**Comment by thorsten-stripe** [comment]
I'm afraid I'm not sure what you're asking. Your last comment indicates that you have found a solution so I'm going to close this out. If that's not correct, please elaborate your issue and reopen it.

**Comment by andrewfashion** [comment]
@Nyceane Did you end up finding a solution to keep using this and working with iOS as well?
