### ISSUE TITLE
ERROR Error: Uncaught (in promise): FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app). 

### ISSUE THREAD

**Issue by donemmx** [stripe/stripe-firebase-extensions#72]
This is the error i get when i try to click on customer portal function i created in Angular
Below is the code.

 async createPortalLink() {
    const functionRef =  firebase
      .app()
      .functions('us-east4')
      .httpsCallable('ext-firestore-stripe-subscriptions-createPortalLink');
    const { data } = await functionRef({ returnUrl: window.location.origin });
    window.location.assign(data.url);
  }

please help.

**Comment by thorsten-stripe** [comment]
This looks like a problem with the your firebase app configuration and is unrelated to the extension: https://stackoverflow.com/questions/40563140/error-no-firebase-app-default-has-been-created-call-firebase-app-initiali
