### ISSUE TITLE
subscription Collection not created. 

### ISSUE THREAD

**Issue by donemmx** [stripe/stripe-firebase-extensions#73]
after successfully paying in stripe it redirects me to my app and i can't access customer portal.

**Comment by thorsten-stripe** [comment]
Please only open issues here that are feature requests or actual bugs with the extension. For help with your integration you can chat with our support eng team on IRC: https://webchat.freenode.net/#stripe or email: https://support.stripe.com/

**Comment by thorsten-stripe** [comment]
Also make sure you follow the documentation in the Firebase console: 
![image](https://user-images.githubusercontent.com/23213994/95423512-cb33f100-0973-11eb-8aa5-77ae352aaddc.png)

You can also find the docs here: 
1. https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#configure-the-stripe-customer-portal
1. https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#redirect-to-the-customer-portal

**Comment by donemmx** [comment]
thanks for the response. i have everything setup and working just that error that's the problem. But thanks for the help.
