### ISSUE TITLE
Checkout session created twice results in customers paying but not recognised. Please support ASAP.

### ISSUE THREAD

**Issue by mogwely** [stripe/stripe-firebase-extensions#80]
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug

Upon checkout, constantly 2 checkout_sessions get created. 
This ends up sometimes (not everytime) with 2 customers on stripe with the same email address. Customer A would have the active subscription, while customer B has no subscriptions. i.e. Subscription would be connected to only one of those 2 stripe customers.
On Firestore end, there is always only 1 customer document that gets created in the customers collection and so far it sometimes has the stripeId of customer A or B. 
As a result when the customer document has the stripeId of Customer B, customer document would NOT have the subscription, although they successfully paid.

The checkout session is constantly created twice. But the new customer on stripe is not always created twice and I suspect that it gets created twice, when the user was already an existing authenticated user on firebase, before they proceeded to buy a subscription. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup `firestore-stripe-subscriptions` on an existing firebase project with firestore collections.
2. Setup your product and pricings on stripe

## This is the function that gets called upon clicking on checkout button 
```

async function subscribe(event) {
  event.preventDefault();
  $('#loader-spinner').show();
  document.querySelectorAll('button').forEach((b) => (b.disabled = true));
  const selectedPrice = document.querySelector('input[name="plans"]:checked').value;

  const docRef = await db
    .collection('customers')
    .doc(currentUser)
    .collection('checkout_sessions')
    .add({
      price: selectedPrice,
      allow_promotion_codes: true,
      success_url: 'https://www.example.com/subscription-redirect',
      cancel_url: window.location.origin,
      metadata: {
        tax_rate: '10% sales tax exclusive',
      },
   });

  // Wait for the CheckoutSession to get attached by the extension
  docRef.onSnapshot((snap) => {
    const { error, sessionId } = snap.data();

    if (error) {
      // Show an error to your customer and then inspect your function logs.
      alert(`An error occured: ${error.message}`);
      console.log("error happened" + error.message);
      document.querySelectorAll('button').forEach((b) => (b.disabled = false));
    }
    if (sessionId) {
      // We have a session, let's redirect to Checkout
      // Init Stripe
      const stripe = Stripe(STRIPE_PUBLISHABLE_KEY);
      stripe.redirectToCheckout({ sessionId });
    }
  });
}

```

## Expected behavior

A checkout session should be created only once per session, a stripe customer should be created once for every user, regardless if the user is a new user or existing user.

## System information

- Browser [Chrome]

## Additional information

I attached the relevant cloud function logs from one of these incidents.

**Comment by mogwely** [comment]
Turned out to be an issue on our side. Sorry for disturbing.

**Comment by thorsten-stripe** [comment]
@mogwely no worries, glad you got it resolved. If you think this is something others might run into as well, feel free to post the resolution here 👍

**Comment by padioca** [comment]
I am running into the exact same issue and would certainly appreciate some guidance to get it resolved.  Been trying to figure it out for several days now...
