### ISSUE TITLE
Customer object is not created when users are imported

### ISSUE THREAD

**Issue by mikeoaklet** [stripe/stripe-firebase-extensions#82]
# Bug report

`firestore-stripe-subscriptions

## To Reproduce

I used Firebase CLI command `firebase auth:import users.json`.

## Expected behavior

Customer objects to be created in Firestore.

## System information

- OS: Windows
- Browser Chrome

Also I would like to ask, if there is some chance to write script to create these customer objects using Admin SDK. So I don't need to delete and import users again. Thank you.

**Comment by thorsten-stripe** [comment]
They default behavior has been changed to create customer objects on the fly when you create the first checkout_session for a given user, see https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-017---2020-10-15
