### ISSUE TITLE
Only Standard Pricing model is updating in Firebase

### ISSUE THREAD

**Issue by RezaRahmati** [stripe/stripe-firebase-extensions#83]
# Bug report

- Extension name: Run Subscription Payments with Stripe

## Describe the bug

There are 4 pricing model in stripe, but only Standard is synching

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1- create a product in stripe
2- create standard pricing
3- verify pricing data is synched to firestore
4- edit product>price and change pricing model to volume or graduated
5- save changes

## Expected behavior
information stored in firestore

## Actual behavior
Nothing is synched

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari]

**Comment by thorsten-stripe** [comment]
> The extension currently supports pricing plans that bill a predefined amount at a specific interval. More complex plans (e.g. different pricing tiers or seats) are not yet supported. If you'd like to see support for these, please open a feature request issue with details about your business model and pricing plans.

https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#create-product-and-pricing-information
