### ISSUE TITLE
Support other pricing models

### ISSUE THREAD

**Issue by RezaRahmati** [stripe/stripe-firebase-extensions#84]
# Feature request

- Extension name: `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

There are 4 types of pricing model, but seems only standard is supported.

## Describe the solution you'd like

Being able to use any of that pricing model and data be synched to firebase

## Additional context

Related to https://github.com/stripe/stripe-firebase-extensions/issues/83

**Comment by thorsten-stripe** [comment]
@RezaRahmati as mentioned before, please provide details about your use case so we can evaluate prioritization of this. A generic feature request like this is not helpful. I'm going to leave this open, so others can submit their use cases here, but please do provide details!

**Comment by RezaRahmati** [comment]
@thorsten-stripe Sure, My use case is we are going to have monthly subscription for 10K api call (let's say 500$), and if user exceeds that 10K we want to charge more per packages of 10K (for 250$). Not sure what kind of pricing I have defined, I tried to figure it out but then I saw this extension doesn't support, so some kind of blocked.

**Comment by thorsten-stripe** [comment]
@RezaRahmati thanks for outlining your use case. At the moment, Stripe Checkout and the Stripe customer portal do not support tiered & metered billing. For your business model you will need to build your own integration with Stripe Elements: https://stripe.com/docs/billing/subscriptions/metered

**Comment by t-kaufmann** [comment]
@thorsten-stripe I am an in a similar situation right now as I want to implement a volume based pricing model. The documtentation link you sent regarding Stripe Element mentions that it is also possible to use Stripe Checkout for metered billing - is there any more information to this? I only got the checkout page to work with standard pricing (e.g. 10$/month).

**Comment by t-kaufmann** [comment]
@thorsten-stripe While we're at it, for the checkout page the beta for metered billing is already available, though the customer portal does not support plans with metered billing. Does something similar exist for the customer portal or will this be implemented in the future?
