### ISSUE TITLE
Provide the product link in the subscription

### ISSUE THREAD

**Issue by RezaRahmati** [stripe/stripe-firebase-extensions#85]
# Feature request

- Extension name:  `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

After subscribing a new collection is created under customers, and include some information as well as document reference to price, the problem is the product information is missed  

## Describe the solution you'd like

Adding a new property under subscription containing product DocumentRef.

## Describe alternatives you've considered

The workaround right now is to do some regex to extract product from price document ref

**Comment by thorsten-stripe** [comment]
You can navigate back to the product doc from the price reference using the `parent` param with the Firebase SDK, e.g. 

```js
// Get all subscriptions for the customer
  db.collection('customers')
    .doc(currentUser)
    .collection('subscriptions')
    .where('status', 'in', ['trialing', 'active'])
    .onSnapshot(async (snapshot) => {
      const subscription = snapshot.docs[0].data();
      const productData = (await subscription.price.parent.parent.get()).data();
      const priceData = (await subscription.price.get()).data();
// [...]
```

**Comment by thorsten-stripe** [comment]
You do have a point though, it might be valuable to have the product data directly within the subscription doc.
