### ISSUE TITLE
Pass metadata down from product / price to subscription.

### ISSUE THREAD

**Issue by ogulcantumdogan** [stripe/stripe-firebase-extensions#89]
# Feature request

 `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

I need to pass down metadata from my Products / Prices down to the subscription object. 

My products have a monthly Quota, which I keep the quota number data in Price metadata. My customers' accounts need to have this data to operate correctly. Just like the firebaseRole metadata, I believe it should be possible to pass down additional metadata to the subscription object.

## Describe the solution you'd like

Maybe adding a prefix like 'firebase' to the metadata would trigger the passing down, so that other irrelevant metadata is not passed down from the product to the subscription object. I see that firebaseRole is already passed down, so I see no reason not to be able to pass down extra metadata. I think passing down metadata from a Price object would be better because it's the most granular option that someone could specify metadata.

## Describe alternatives you've considered

I have tried using both Product and Price metadata, without luck.

I have considered using the metadata sync before checkout, ( #13 )  but that means that I can only handle this when the users are subscribing from the customer portal, and this solution would fail when I create a assign a custom Price for one of my customers with custom metadata.

I could also keep the Quota values in my database and hard-code them, but then my product managers wouldn't be able to change these values from Stripe dashboard. Also managing custom Products & Prices would be really painful.

**Comment by thorsten-stripe** [comment]
There is a PR open (#87) that will add product and price metadata to the product and price docs in Firestore. This however would not add the metadata to the subscription doc itself, but the subscription doc has a reference to the price doc. Will that be sufficient for you?

**Comment by ogulcantumdogan** [comment]
This was very helpful on my part, thank you!
