### ISSUE TITLE
Sort products data in Firestore

### ISSUE THREAD

**Issue by shidcordero** [stripe/stripe-firebase-extensions#90]
# Feature request

Add sorting of products since the properties on products does not have the ability to be sorted

## Is your feature request related to a problem? Please describe.

A problem for me is that when the client wants to add new price for their subscription then when viewed in the app it won't show it properly because there is no way to sort it out.

## Describe the solution you'd like

Add ability on stripe to sort products so that the value on Firestore will have a property of `order`

## Additional context

Please implement this asap as this is really needed for our app

**Comment by thorsten-stripe** [comment]
Products and prices are collections in Firestore that can be sorted via the Firebase SDK https://firebase.google.com/docs/firestore/query-data/order-limit-data.

**Comment by shidcordero** [comment]
I know what you mean but for example. I want to add a new product let say Premium Plan. I already have Basic Plan and Enterprise Plan in my Firestore. I need to show to the user the subscription plan in the following order: Basic Plan > Premium Plan > Enterprise Plan. Tell me, how I can sort the following given the only properties of Product sync in Firestore?

**Comment by thorsten-stripe** [comment]
There is a PR open ( #87 ) that will sync product metadata to Firestore. This way you can set an `index` key in the product metadata in the Stripe Dashboard and then use that to sort the products on the client. Does that work for you?

**Comment by shidcordero** [comment]
Yeah, that would be cool. Hope that PR gets approved and released sooner
