### ISSUE TITLE
Deleting a product was not sync in Firestore

### ISSUE THREAD

**Issue by shidcordero** [stripe/stripe-firebase-extensions#92]
# Bug report

## Describe the bug

Deleting a product does not delete the data in Firestore nor it change the status to active = false

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Stripe > Products
2. Create test products
3. Delete test products
4. check Firestore if the data is deleted

## Expected behavior

The data should be deleted or active status change to false

## Screenshots

Created a test product 
![image](https://user-images.githubusercontent.com/26376208/98242638-b9139580-1fa7-11eb-9ad5-2303e2ece56e.png)

Screenshot from firestore that proves the data is added
![image](https://user-images.githubusercontent.com/26376208/98242703-d2b4dd00-1fa7-11eb-964c-8ad779a74708.png)

Delete the test product
![image](https://user-images.githubusercontent.com/26376208/98242776-ef511500-1fa7-11eb-84ee-05c1fbb7d9ed.png)

Screenshot from firestore that proves the data is still not deleted nor changed active status to false. also price data has active status to true
![image](https://user-images.githubusercontent.com/26376208/98242868-10196a80-1fa8-11eb-9de8-a81494456dcf.png)

## System information

- OS: Windows 10
- Browser (if applies): Edge

## Additional context

Please apply a fix asap as I will be needed it sooner.

**Comment by thorsten-stripe** [comment]
Once a product has been used for a transaction it can't be deleted anymore in Stripe, that's why we didn't implement this sync. Rather it is recommended to archive the product/price which will update the `active` parameter to false.
