### ISSUE TITLE
Sync current users with Stripe

### ISSUE THREAD

**Issue by perryjsteward** [stripe/stripe-firebase-extensions#93]
I've done some googling and havent been able to come up with much for this. Is there a way to sync existing users that have already signed up (using Firebase Auth) to Stripe user objects?

New users seem to be able to create stripe user objects which means i can update subscriptions manually if needed via the stripe dashboard. I have a user support use case that i may need to do this for existing customers that signed up before stripe integration was created.

**Comment by thorsten-stripe** [comment]
The extension creates a customer object on the fly when the user in Firestore doesn't yet have a customer ID: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-017---2020-10-15

This means you don't need to sync all Firebase users with Stripe, but can be ensured that a customer object is created in Stripe for them the first time you create a `checkout_session` for the user.
