### ISSUE TITLE
Only create user objects in Stripe that are NOT Anonymous

### ISSUE THREAD

**Issue by perryjsteward** [stripe/stripe-firebase-extensions#94]
I create Anonymous users to make sure users dont lose data when using my app prior to sign up. however i probably dont want to create an objec in stripe until they upgrade their account. 

Could you please add an option to filter out anonymous users?

**Comment by thorsten-stripe** [comment]
When configuring the extension you can select "Do not sync": 
![image](https://user-images.githubusercontent.com/23213994/98522315-802d3680-22af-11eb-82ad-4d1a7d04711b.png)

This way the extension only creates a Stripe customer object when you create the first `checkout_session` for the user.

**Comment by perryjsteward** [comment]
Sorry this isn't quite what im looking for as i want to sync those users that have provided an email...

The solution you suggest means that i can not manually upgrade users from Stripe. I will have to get each sign up to create a checkout session so that their userId is in stripe

**Comment by thorsten-stripe** [comment]
@perryjsteward that seems like a somewhat niche use-case. Two options:

1. You set the extension to "Do not sync" and write your own separate function that handles your specific sign up and customer creation logic.
2. You open a PR to add the functionality to the extension.
