### ISSUE TITLE
Error: You must provide at least one recurring price in `subscription` mode when using prices.

### ISSUE THREAD

**Issue by shidcordero** [stripe/stripe-firebase-extensions#98]
# Bug report
I am getting an error: You must provide at least one recurring price in `subscription` mode when using prices.

## Describe the bug
I am getting that error when I checkout of product which has Price of one time payment.
Product:
![image](https://user-images.githubusercontent.com/26376208/98776881-c35fe480-242a-11eb-932f-0255f49fa208.png)

Price:
![image](https://user-images.githubusercontent.com/26376208/98776927-d8d50e80-242a-11eb-88c1-9eeec441ae09.png)

## To Reproduce

Just checkout a product which has a one time payment.

## Expected behavior

Should allow checking out one time payment

## System information

- OS: Windows 64bit
- Browser (if applies) Edge latest

**Comment by thorsten-stripe** [comment]
The extension is for subscription payments. One time products are only allowed in combination with a recurring product, e.g. for an initial setup fee: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#adding-multiple-prices-including-one-time-setup-fees

For pure one-time payments use case, we generally recommend using https://github.com/firebase/functions-samples/tree/master/stripe
